/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check API dependency connectivity.
         * @description Performs lightweight PostgreSQL and Redis checks for the trace proof.
         */
        get: operations["systemPing"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check process liveness.
         * @description Returns success when the API process is able to serve requests.
         */
        get: operations["systemHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check dependency readiness.
         * @description Returns success only when every hard dependency is usable.
         */
        get: operations["systemReady"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the deployed API version.
         * @description Returns the version associated with the running API build.
         */
        get: operations["systemVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the caller's own account.
         * @description Returns the account belonging to the access token. There is deliberately no `/users/{id}` counterpart in this version: the actor comes from the token, so one user cannot read another by changing a path segment.
         */
        get: operations["userGetMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update the caller's own profile.
         * @description Partially updates the profile. Omitted fields are left alone; unknown and null fields are rejected with 422.
         */
        patch: operations["userUpdateMe"];
        trace?: never;
    };
    "/me/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the caller's own effective permissions.
         * @description Resolves the caller's roles to the flat set of named permissions they grant. Advisory only: it exists so the interface can hide actions that would fail, and every server call re-checks regardless of what the client believes.
         */
        get: operations["rbacGetMyPermissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the caller's preferences.
         * @description Returns the full preference set. Every account has one from registration onwards, so this never returns an empty body.
         */
        get: operations["userGetMyPreferences"];
        /**
         * Replace the caller's preferences.
         * @description Replaces the whole preference set. A field left out is not "unchanged", it is a validation failure -- which is what makes this idempotent.
         */
        put: operations["userReplaceMyPreferences"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List roles and the permissions they grant.
         * @description The catalogue is small and fixed, so it is returned whole rather than paginated.
         */
        get: operations["rbacListRoles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The user whose roles are being changed. */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Grant a role to a user.
         * @description Granting is idempotent: a role the user already holds is not an error. An actor cannot grant themselves a role they do not already hold.
         */
        post: operations["rbacAssignRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}/roles/{role}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The user whose roles are being changed. */
                id: string;
                /** @description The role to revoke. */
                role: components["schemas"]["RoleName"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke a role from a user.
         * @description Revoking is idempotent. Two revocations are refused: an actor removing their own `admin` role, and any revocation that would leave the system with no administrator.
         */
        delete: operations["rbacRevokeRole"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description RFC 9457 Problem Details response. */
        Problem: {
            /**
             * Format: uri-reference
             * @description Stable URI identifying the problem type.
             * @example https://fluentra.dev/errors/validation-failed
             */
            type: string;
            /**
             * @description A short, safe, human-readable summary.
             * @example Validation failed
             */
            title: string;
            /**
             * @description HTTP status code for this occurrence.
             * @example 422
             */
            status: number;
            /**
             * @description A safe explanation of this occurrence.
             * @example One or more request fields are invalid.
             */
            detail?: string;
            /**
             * @description Request path that produced the problem.
             * @example /api/v1/auth/register
             */
            instance?: string;
            /**
             * @description Stable machine-readable error code.
             * @example VALIDATION_FAILED
             */
            code: string;
            /**
             * @description Correlation identifier for support and observability.
             * @example 01J8XQ7Z9K3M4N5P6Q7R8S9T0V
             */
            request_id: string;
            /** @description Safe, problem-specific metadata. */
            meta?: {
                [key: string]: unknown;
            };
        };
        ValidationProblem: components["schemas"]["Problem"] & {
            /** @description Field-level validation failures. */
            errors: components["schemas"]["ValidationError"][];
        };
        /** @description One invalid request field. */
        ValidationError: {
            /**
             * @description JSON field path that failed validation.
             * @example email
             */
            field: string;
            /**
             * @description Stable validation error code.
             * @example REQUIRED
             */
            code: string;
            /**
             * @description Localised, safe explanation of the validation failure.
             * @example Email is required.
             */
            message: string;
        };
        /** @description Cursor pagination metadata returned with every user-facing list. */
        Page: {
            /** @description Opaque cursor for the next page, omitted when there is no next page. */
            next_cursor?: components["schemas"]["Cursor"];
            /**
             * @description Whether another page can be requested using next_cursor.
             * @example true
             */
            has_more: boolean;
            /**
             * @description Number of items requested for this page.
             * @example 20
             */
            limit: number;
        };
        /**
         * @description Opaque, URL-safe cursor encoding a stable sort value and ID.
         * @example eyJjIjoiMjAyNi0wOC0wNlQxMDowMDowMFoiLCJpIjoiMDE5M2E3In0
         */
        Cursor: string;
        /** @description Successful API dependency connectivity result. */
        Ping: {
            /**
             * @description Confirms that PostgreSQL and Redis responded.
             * @enum {string}
             */
            status: "ok";
        };
        /** @description Successful process liveness result. */
        Health: {
            /**
             * @description Confirms that the process is serving requests.
             * @enum {string}
             */
            status: "ok";
        };
        /** @description Successful hard dependency readiness result. */
        Ready: {
            /**
             * @description Confirms that every hard dependency is usable.
             * @enum {string}
             */
            status: "ready";
        };
        /** @description Deployed API build version. */
        Version: {
            /**
             * @description Version associated with the running API build.
             * @example 0.1.0
             */
            version: string;
        };
        /** @description The authenticated caller's own account. There is no operation that returns this shape for anybody else: the server reads the actor from the access token and the path carries no user id. */
        Me: {
            /**
             * Format: uuid
             * @description Stable identifier every other resource references.
             */
            id: string;
            /**
             * Format: email
             * @description Returned only here. No other operation exposes a user's email address.
             * @example learner@example.com
             */
            email: string;
            status: components["schemas"]["UserStatus"];
            /**
             * Format: date-time
             * @description When the address was verified, or null while it is unverified.
             */
            email_verified_at?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            profile: components["schemas"]["MeProfile"];
        };
        /** @description Descriptive data about the caller. Nothing here is used to authenticate. */
        MeProfile: {
            /**
             * @description Shown to other learners. Names that impersonate Fluentra staff are rejected.
             * @example Nghi
             */
            display_name: string;
            /**
             * Format: uri
             * @description Public avatar URL, or null when none has been uploaded.
             */
            avatar_url?: string | null;
            /**
             * @description ISO 3166-1 alpha-2 country code, or null.
             * @example VN
             */
            country?: string | null;
            /**
             * @description IANA timezone name. Every timestamp in the API stays UTC; this is used to place reminders and streak boundaries in the learner's day.
             * @example Asia/Ho_Chi_Minh
             */
            timezone: string;
            /**
             * Format: date
             * @description Used only for the age gate. It is never shown to other learners and never leaves this operation.
             */
            date_of_birth?: string | null;
        };
        /**
         * @description Account lifecycle state. `pending_deletion` is the 30-day grace period, in which the account is unusable but still recoverable by the owner.
         * @enum {string}
         */
        UserStatus: "active" | "suspended" | "pending_deletion" | "deleted";
        /** @description A partial update. Omit a field to leave it unchanged; an unknown field is a validation failure rather than something quietly ignored, because a misspelled field name that returns 200 is indistinguishable from success. */
        UpdateMeRequest: {
            /** @example Nghi Nguyen */
            display_name?: string;
            /** @example VN */
            country?: string;
            /** @example Asia/Ho_Chi_Minh */
            timezone?: string;
            /**
             * Format: date
             * @example 1998-03-04
             */
            date_of_birth?: string;
        };
        /** @description The caller's settings. Replaced as a whole, never patched. */
        Preferences: {
            /**
             * @description BCP 47 language tag, optionally with a region.
             * @example vi
             */
            locale: string;
            /** @enum {string} */
            theme: "light" | "dark" | "system";
            /**
             * @description Minutes of study the learner is aiming for each day.
             * @example 15
             */
            daily_goal_minutes: number;
            /**
             * @description Channels the learner accepts notifications on.
             * @example [
             *       "in_app",
             *       "email"
             *     ]
             */
            notification_channels: ("in_app" | "email" | "push")[];
            /** @description A window in which no notification is delivered, or null for none. It is one object rather than two fields so that half a window cannot be expressed. */
            quiet_hours?: components["schemas"]["QuietHours"] | null;
            /** @description Disables AI grading only. Deterministic exercises keep working, so opting out never costs the learner access to the product. */
            ai_processing_opt_out: boolean;
            /** Format: date-time */
            updated_at: string;
        };
        /** @description Local wall-clock times in the learner's timezone. A window may wrap past midnight, which is the normal case for sleeping hours. */
        QuietHours: {
            /** @example 22:00 */
            start: string;
            /** @example 07:00 */
            end: string;
        };
        /** @description The complete preference set. This is a PUT: every field is required, and what the caller sends is exactly what is stored. */
        ReplacePreferencesRequest: {
            /** @example vi */
            locale: string;
            /** @enum {string} */
            theme: "light" | "dark" | "system";
            /** @example 30 */
            daily_goal_minutes: number;
            /**
             * @example [
             *       "in_app",
             *       "push"
             *     ]
             */
            notification_channels: ("in_app" | "email" | "push")[];
            quiet_hours?: components["schemas"]["QuietHours"] | null;
            /** @example false */
            ai_processing_opt_out: boolean;
        };
        /**
         * @description What the caller is allowed to do, as the server currently sees it.
         *     This is advisory (BR-RBAC-08). It exists so the interface can hide actions that would fail, not so the client can decide anything: every server call re-checks, and a client that has this list is no closer to using a permission it was not granted.
         */
        MyPermissions: {
            /**
             * @description The roles assigned to the caller. There are exactly two in this product.
             * @example [
             *       "user"
             *     ]
             */
            roles: components["schemas"]["RoleName"][];
            /**
             * @description Every named permission the caller's roles grant, resolved and flattened. A learner holds none of these — access to their own data is not a named permission, it is what `/me` means.
             * @example []
             */
            permissions: string[];
        };
        /**
         * @description Exactly two roles exist (BR-RBAC-02). A third is an ADR, not a row: it changes the shape of the product rather than its data.
         * @enum {string}
         */
        RoleName: "admin" | "user";
        /** @description A role and the permissions it grants. */
        Role: {
            name: components["schemas"]["RoleName"];
            /** @example Full administrative access. */
            description: string;
            /**
             * @example [
             *       "rbac.assign",
             *       "rbac.read",
             *       "user.list"
             *     ]
             */
            permissions: string[];
        };
        /** @description The role catalogue. It is small and fixed, so it is not paginated. */
        RoleList: {
            items: components["schemas"]["Role"][];
        };
        /** @description Grant a role to a user. */
        AssignRoleRequest: {
            role: components["schemas"]["RoleName"];
        };
        /** @description The roles held by one user, after the change. */
        UserRoles: {
            /** Format: uuid */
            user_id: string;
            /**
             * @example [
             *       "admin",
             *       "user"
             *     ]
             */
            roles: components["schemas"]["RoleName"][];
        };
    };
    responses: {
        /** @description The request is malformed or has an invalid cursor. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://fluentra.dev/errors/bad-request",
                 *       "title": "Bad request",
                 *       "status": 400,
                 *       "detail": "The request body could not be decoded.",
                 *       "code": "BAD_REQUEST",
                 *       "request_id": "01J8XQ7Z9K3M4N5P6Q7R8S9T0V"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Authentication credentials are missing, invalid, or expired. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://fluentra.dev/errors/unauthenticated",
                 *       "title": "Authentication required",
                 *       "status": 401,
                 *       "detail": "Provide a valid access token.",
                 *       "code": "UNAUTHENTICATED",
                 *       "request_id": "01J8XQ7Z9K3M4N5P6Q7R8S9T0V"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The authenticated actor lacks permission for this operation. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://fluentra.dev/errors/permission-denied",
                 *       "title": "Permission denied",
                 *       "status": 403,
                 *       "detail": "You do not have permission to perform this action.",
                 *       "code": "PERMISSION_DENIED",
                 *       "request_id": "01J8XQ7Z9K3M4N5P6Q7R8S9T0V"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The resource does not exist or is not visible to this actor. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://fluentra.dev/errors/not-found",
                 *       "title": "Not found",
                 *       "status": 404,
                 *       "detail": "The requested resource was not found.",
                 *       "code": "NOT_FOUND",
                 *       "request_id": "01J8XQ7Z9K3M4N5P6Q7R8S9T0V"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The requested operation conflicts with the current resource state. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://fluentra.dev/errors/conflict",
                 *       "title": "Conflict",
                 *       "status": 409,
                 *       "detail": "The operation conflicts with the current resource state.",
                 *       "code": "CONFLICT",
                 *       "request_id": "01J8XQ7Z9K3M4N5P6Q7R8S9T0V"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description One or more request fields failed validation. */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://fluentra.dev/errors/validation-failed",
                 *       "title": "Validation failed",
                 *       "status": 422,
                 *       "detail": "One or more request fields are invalid.",
                 *       "code": "VALIDATION_FAILED",
                 *       "request_id": "01J8XQ7Z9K3M4N5P6Q7R8S9T0V",
                 *       "errors": [
                 *         {
                 *           "field": "email",
                 *           "code": "EMAIL",
                 *           "message": "Enter a valid email address."
                 *         }
                 *       ]
                 *     }
                 */
                "application/problem+json": components["schemas"]["ValidationProblem"];
            };
        };
        /** @description The applicable rate limit has been exceeded. */
        TooManyRequests: {
            headers: {
                "Retry-After": components["headers"]["Retry-After"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://fluentra.dev/errors/rate-limited",
                 *       "title": "Too many requests",
                 *       "status": 429,
                 *       "detail": "Retry after the indicated interval.",
                 *       "code": "RATE_LIMITED",
                 *       "request_id": "01J8XQ7Z9K3M4N5P6Q7R8S9T0V"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description An unexpected server error occurred without exposing internals. */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://fluentra.dev/errors/internal",
                 *       "title": "Internal server error",
                 *       "status": 500,
                 *       "detail": "An unexpected error occurred.",
                 *       "code": "INTERNAL",
                 *       "request_id": "01J8XQ7Z9K3M4N5P6Q7R8S9T0V"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description A hard dependency is not available. */
        ServiceUnavailable: {
            headers: {
                "Retry-After": components["headers"]["Retry-After"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://fluentra.dev/errors/dependency-unavailable",
                 *       "title": "Service unavailable",
                 *       "status": 503,
                 *       "detail": "A required service is temporarily unavailable.",
                 *       "code": "DEPENDENCY_UNAVAILABLE",
                 *       "request_id": "01J8XQ7Z9K3M4N5P6Q7R8S9T0V"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: {
        /**
         * @description Correlation ID supplied by the client or generated by the API.
         * @example 01J8XQ7Z9K3M4N5P6Q7R8S9T0V
         */
        "X-Request-Id": string;
        /**
         * @description Entity tag for a cacheable or mutable resource.
         * @example "v1-01J8XQ7Z9K3M4N5P6Q7R8S9T0V"
         */
        ETag: string;
        /**
         * @description Cache directive; authenticated responses default to no-store.
         * @example no-store
         */
        "Cache-Control": string;
        /**
         * @description Maximum requests permitted in the current rate-limit window.
         * @example 60
         */
        "RateLimit-Limit": number;
        /**
         * @description Requests remaining in the current rate-limit window.
         * @example 59
         */
        "RateLimit-Remaining": number;
        /**
         * @description Unix timestamp when the current rate-limit window resets.
         * @example 1786033260
         */
        "RateLimit-Reset": number;
        /**
         * @description Number of seconds before the request may be retried.
         * @example 30
         */
        "Retry-After": number;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    systemPing: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The API and its immediate dependencies responded. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok"
                     *     }
                     */
                    "application/json": components["schemas"]["Ping"];
                };
            };
        };
    };
    systemHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The API process is live. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok"
                     *     }
                     */
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    systemReady: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All hard dependencies are ready. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ready"
                     *     }
                     */
                    "application/json": components["schemas"]["Ready"];
                };
            };
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    systemVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The deployed API version. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "version": "0.1.0"
                     *     }
                     */
                    "application/json": components["schemas"]["Version"];
                };
            };
        };
    };
    userGetMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's account. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "0199a1c2-3d4e-7f80-9abc-def012345678",
                     *       "email": "learner@example.com",
                     *       "status": "active",
                     *       "email_verified_at": "2026-08-09T04:21:07Z",
                     *       "created_at": "2026-08-01T09:15:00Z",
                     *       "updated_at": "2026-08-09T04:21:07Z",
                     *       "profile": {
                     *         "display_name": "Nghi",
                     *         "avatar_url": null,
                     *         "country": "VN",
                     *         "timezone": "Asia/Ho_Chi_Minh",
                     *         "date_of_birth": "1998-03-04"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    userUpdateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "display_name": "Nghi Nguyen",
                 *       "timezone": "Asia/Ho_Chi_Minh"
                 *     }
                 */
                "application/json": components["schemas"]["UpdateMeRequest"];
            };
        };
        responses: {
            /** @description The updated account. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "0199a1c2-3d4e-7f80-9abc-def012345678",
                     *       "email": "learner@example.com",
                     *       "status": "active",
                     *       "email_verified_at": "2026-08-09T04:21:07Z",
                     *       "created_at": "2026-08-01T09:15:00Z",
                     *       "updated_at": "2026-08-09T04:21:07Z",
                     *       "profile": {
                     *         "display_name": "Nghi",
                     *         "avatar_url": null,
                     *         "country": "VN",
                     *         "timezone": "Asia/Ho_Chi_Minh",
                     *         "date_of_birth": "1998-03-04"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["Me"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    rbacGetMyPermissions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's roles and permissions. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "roles": [
                     *         "user"
                     *       ],
                     *       "permissions": []
                     *     }
                     */
                    "application/json": components["schemas"]["MyPermissions"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    userGetMyPreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's preferences. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "locale": "vi",
                     *       "theme": "dark",
                     *       "daily_goal_minutes": 30,
                     *       "notification_channels": [
                     *         "in_app",
                     *         "push"
                     *       ],
                     *       "quiet_hours": {
                     *         "start": "22:00",
                     *         "end": "07:00"
                     *       },
                     *       "ai_processing_opt_out": false,
                     *       "updated_at": "2026-08-09T04:21:07Z"
                     *     }
                     */
                    "application/json": components["schemas"]["Preferences"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    userReplaceMyPreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "locale": "vi",
                 *       "theme": "dark",
                 *       "daily_goal_minutes": 30,
                 *       "notification_channels": [
                 *         "in_app",
                 *         "push"
                 *       ],
                 *       "quiet_hours": {
                 *         "start": "22:00",
                 *         "end": "07:00"
                 *       },
                 *       "ai_processing_opt_out": false
                 *     }
                 */
                "application/json": components["schemas"]["ReplacePreferencesRequest"];
            };
        };
        responses: {
            /** @description The stored preferences. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "locale": "vi",
                     *       "theme": "dark",
                     *       "daily_goal_minutes": 30,
                     *       "notification_channels": [
                     *         "in_app",
                     *         "push"
                     *       ],
                     *       "quiet_hours": {
                     *         "start": "22:00",
                     *         "end": "07:00"
                     *       },
                     *       "ai_processing_opt_out": false,
                     *       "updated_at": "2026-08-09T04:21:07Z"
                     *     }
                     */
                    "application/json": components["schemas"]["Preferences"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    rbacListRoles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every role, with its permissions. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "items": [
                     *         {
                     *           "name": "admin",
                     *           "description": "Full administrative access.",
                     *           "permissions": [
                     *             "rbac.assign",
                     *             "rbac.read",
                     *             "user.list"
                     *           ]
                     *         },
                     *         {
                     *           "name": "user",
                     *           "description": "A learner. Holds no named permissions.",
                     *           "permissions": []
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["RoleList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    rbacAssignRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The user whose roles are being changed. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "role": "admin"
                 *     }
                 */
                "application/json": components["schemas"]["AssignRoleRequest"];
            };
        };
        responses: {
            /** @description The user's roles after the grant. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "user_id": "0199a1c2-3d4e-7f80-9abc-def012345678",
                     *       "roles": [
                     *         "admin",
                     *         "user"
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["UserRoles"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    rbacRevokeRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The user whose roles are being changed. */
                id: string;
                /** @description The role to revoke. */
                role: components["schemas"]["RoleName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The user's roles after the revocation. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "user_id": "0199a1c2-3d4e-7f80-9abc-def012345678",
                     *       "roles": [
                     *         "admin",
                     *         "user"
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["UserRoles"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
}
