/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check API dependency connectivity.
         * @description Performs lightweight PostgreSQL and Redis checks for the trace proof.
         */
        get: operations["systemPing"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check process liveness.
         * @description Returns success when the API process is able to serve requests.
         */
        get: operations["systemHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check dependency readiness.
         * @description Returns success only when every hard dependency is usable.
         */
        get: operations["systemReady"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the deployed API version.
         * @description Returns the version associated with the running API build.
         */
        get: operations["systemVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description RFC 9457 Problem Details response. */
        Problem: {
            /**
             * Format: uri-reference
             * @description Stable URI identifying the problem type.
             * @example https://fluentra.dev/errors/validation-failed
             */
            type: string;
            /**
             * @description A short, safe, human-readable summary.
             * @example Validation failed
             */
            title: string;
            /**
             * @description HTTP status code for this occurrence.
             * @example 422
             */
            status: number;
            /**
             * @description A safe explanation of this occurrence.
             * @example One or more request fields are invalid.
             */
            detail?: string;
            /**
             * @description Request path that produced the problem.
             * @example /api/v1/auth/register
             */
            instance?: string;
            /**
             * @description Stable machine-readable error code.
             * @example VALIDATION_FAILED
             */
            code: string;
            /**
             * @description Correlation identifier for support and observability.
             * @example 01J8XQ7Z9K3M4N5P6Q7R8S9T0V
             */
            request_id: string;
            /** @description Safe, problem-specific metadata. */
            meta?: {
                [key: string]: unknown;
            };
        };
        ValidationProblem: components["schemas"]["Problem"] & {
            /** @description Field-level validation failures. */
            errors: components["schemas"]["ValidationError"][];
        };
        /** @description One invalid request field. */
        ValidationError: {
            /**
             * @description JSON field path that failed validation.
             * @example email
             */
            field: string;
            /**
             * @description Stable validation error code.
             * @example REQUIRED
             */
            code: string;
            /**
             * @description Localised, safe explanation of the validation failure.
             * @example Email is required.
             */
            message: string;
        };
        /** @description Cursor pagination metadata returned with every user-facing list. */
        Page: {
            /** @description Opaque cursor for the next page, omitted when there is no next page. */
            next_cursor?: components["schemas"]["Cursor"];
            /**
             * @description Whether another page can be requested using next_cursor.
             * @example true
             */
            has_more: boolean;
            /**
             * @description Number of items requested for this page.
             * @example 20
             */
            limit: number;
        };
        /**
         * @description Opaque, URL-safe cursor encoding a stable sort value and ID.
         * @example eyJjIjoiMjAyNi0wOC0wNlQxMDowMDowMFoiLCJpIjoiMDE5M2E3In0
         */
        Cursor: string;
        /** @description Successful API dependency connectivity result. */
        Ping: {
            /**
             * @description Confirms that PostgreSQL and Redis responded.
             * @enum {string}
             */
            status: "ok";
        };
        /** @description Successful process liveness result. */
        Health: {
            /**
             * @description Confirms that the process is serving requests.
             * @enum {string}
             */
            status: "ok";
        };
        /** @description Successful hard dependency readiness result. */
        Ready: {
            /**
             * @description Confirms that every hard dependency is usable.
             * @enum {string}
             */
            status: "ready";
        };
        /** @description Deployed API build version. */
        Version: {
            /**
             * @description Version associated with the running API build.
             * @example 0.1.0
             */
            version: string;
        };
    };
    responses: {
        /** @description The request is malformed or has an invalid cursor. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://fluentra.dev/errors/bad-request",
                 *       "title": "Bad request",
                 *       "status": 400,
                 *       "detail": "The request body could not be decoded.",
                 *       "code": "BAD_REQUEST",
                 *       "request_id": "01J8XQ7Z9K3M4N5P6Q7R8S9T0V"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Authentication credentials are missing, invalid, or expired. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://fluentra.dev/errors/unauthenticated",
                 *       "title": "Authentication required",
                 *       "status": 401,
                 *       "detail": "Provide a valid access token.",
                 *       "code": "UNAUTHENTICATED",
                 *       "request_id": "01J8XQ7Z9K3M4N5P6Q7R8S9T0V"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The authenticated actor lacks permission for this operation. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://fluentra.dev/errors/permission-denied",
                 *       "title": "Permission denied",
                 *       "status": 403,
                 *       "detail": "You do not have permission to perform this action.",
                 *       "code": "PERMISSION_DENIED",
                 *       "request_id": "01J8XQ7Z9K3M4N5P6Q7R8S9T0V"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The resource does not exist or is not visible to this actor. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://fluentra.dev/errors/not-found",
                 *       "title": "Not found",
                 *       "status": 404,
                 *       "detail": "The requested resource was not found.",
                 *       "code": "NOT_FOUND",
                 *       "request_id": "01J8XQ7Z9K3M4N5P6Q7R8S9T0V"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The requested operation conflicts with the current resource state. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://fluentra.dev/errors/conflict",
                 *       "title": "Conflict",
                 *       "status": 409,
                 *       "detail": "The operation conflicts with the current resource state.",
                 *       "code": "CONFLICT",
                 *       "request_id": "01J8XQ7Z9K3M4N5P6Q7R8S9T0V"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description One or more request fields failed validation. */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://fluentra.dev/errors/validation-failed",
                 *       "title": "Validation failed",
                 *       "status": 422,
                 *       "detail": "One or more request fields are invalid.",
                 *       "code": "VALIDATION_FAILED",
                 *       "request_id": "01J8XQ7Z9K3M4N5P6Q7R8S9T0V",
                 *       "errors": [
                 *         {
                 *           "field": "email",
                 *           "code": "EMAIL",
                 *           "message": "Enter a valid email address."
                 *         }
                 *       ]
                 *     }
                 */
                "application/problem+json": components["schemas"]["ValidationProblem"];
            };
        };
        /** @description The applicable rate limit has been exceeded. */
        TooManyRequests: {
            headers: {
                "Retry-After": components["headers"]["Retry-After"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://fluentra.dev/errors/rate-limited",
                 *       "title": "Too many requests",
                 *       "status": 429,
                 *       "detail": "Retry after the indicated interval.",
                 *       "code": "RATE_LIMITED",
                 *       "request_id": "01J8XQ7Z9K3M4N5P6Q7R8S9T0V"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description An unexpected server error occurred without exposing internals. */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://fluentra.dev/errors/internal",
                 *       "title": "Internal server error",
                 *       "status": 500,
                 *       "detail": "An unexpected error occurred.",
                 *       "code": "INTERNAL",
                 *       "request_id": "01J8XQ7Z9K3M4N5P6Q7R8S9T0V"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description A hard dependency is not available. */
        ServiceUnavailable: {
            headers: {
                "Retry-After": components["headers"]["Retry-After"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://fluentra.dev/errors/dependency-unavailable",
                 *       "title": "Service unavailable",
                 *       "status": 503,
                 *       "detail": "A required service is temporarily unavailable.",
                 *       "code": "DEPENDENCY_UNAVAILABLE",
                 *       "request_id": "01J8XQ7Z9K3M4N5P6Q7R8S9T0V"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: {
        /**
         * @description Correlation ID supplied by the client or generated by the API.
         * @example 01J8XQ7Z9K3M4N5P6Q7R8S9T0V
         */
        "X-Request-Id": string;
        /**
         * @description Entity tag for a cacheable or mutable resource.
         * @example "v1-01J8XQ7Z9K3M4N5P6Q7R8S9T0V"
         */
        ETag: string;
        /**
         * @description Cache directive; authenticated responses default to no-store.
         * @example no-store
         */
        "Cache-Control": string;
        /**
         * @description Maximum requests permitted in the current rate-limit window.
         * @example 60
         */
        "RateLimit-Limit": number;
        /**
         * @description Requests remaining in the current rate-limit window.
         * @example 59
         */
        "RateLimit-Remaining": number;
        /**
         * @description Unix timestamp when the current rate-limit window resets.
         * @example 1786033260
         */
        "RateLimit-Reset": number;
        /**
         * @description Number of seconds before the request may be retried.
         * @example 30
         */
        "Retry-After": number;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    systemPing: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The API and its immediate dependencies responded. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok"
                     *     }
                     */
                    "application/json": components["schemas"]["Ping"];
                };
            };
        };
    };
    systemHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The API process is live. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok"
                     *     }
                     */
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    systemReady: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All hard dependencies are ready. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ready"
                     *     }
                     */
                    "application/json": components["schemas"]["Ready"];
                };
            };
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    systemVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The deployed API version. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "version": "0.1.0"
                     *     }
                     */
                    "application/json": components["schemas"]["Version"];
                };
            };
        };
    };
}
