/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check API dependency connectivity.
         * @description Performs lightweight PostgreSQL and Redis checks for the trace proof.
         */
        get: operations["systemPing"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check process liveness.
         * @description Returns success when the API process is able to serve requests.
         */
        get: operations["systemHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check dependency readiness.
         * @description Returns success only when every hard dependency is usable.
         */
        get: operations["systemReady"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the deployed API version.
         * @description Returns the version associated with the running API build.
         */
        get: operations["systemVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Open an account and start email verification.
         * @description Creates the account and issues a `verify_email` challenge. The six-digit code goes to the address by email; the response carries only the challenge handle.
         *
         *     This operation never reveals whether an address is already registered. An address that is already verified gets the same response shape as a fresh registration, and its owner receives a "someone tried to register with your address" email instead of a code -- so a caller probing for accounts learns nothing from either the status or the body.
         *
         *     An address registered but **not yet** verified is treated as a fresh registration: the submitted password replaces the stored one and a new challenge is issued. Reissuing the pending challenge instead would be an account-takeover path -- somebody registers an address they do not own, its real owner registers it too, receives the code, verifies, and ends up with an account whose password the first party chose.
         */
        post: operations["authRegister"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Authenticate a user with email and password.
         * @description Authenticates a user account. Enforces constant-time verification even for unknown emails (BR-AUTH-02) and applies independent per-account and per-IP lockout rate limits (BR-AUTH-08).
         */
        post: operations["authLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/challenges/{id}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The challenge handle returned when it was issued. */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit the code for a challenge.
         * @description Accepts the six digits and consumes the challenge. For a `verify_email` challenge this marks the address verified.
         *
         *     The code is single-use and expires ten minutes after issuance. Five wrong codes burn the challenge permanently -- a new one must be requested rather than retried. A wrong code returns 401 with the number of attempts left in `meta`.
         */
        post: operations["authVerifyChallenge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/challenges/{id}/resend": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The challenge to send a new code for. */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a new code for a challenge.
         * @description Replaces the code and clears the attempt count. It does **not** extend `expires_at`: resending gives the learner a fresh code, not an indefinitely valid challenge.
         *
         *     There is a 60-second cooldown per challenge and a cap on issuances per address per hour. A challenge that is already burned cannot be resent -- request a new one.
         */
        post: operations["authResendChallenge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the caller's own account.
         * @description Returns the account belonging to the access token. There is deliberately no `/users/{id}` counterpart in this version: the actor comes from the token, so one user cannot read another by changing a path segment.
         */
        get: operations["userGetMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update the caller's own profile.
         * @description Partially updates the profile. Omitted fields are left alone; unknown and null fields are rejected with 422.
         */
        patch: operations["userUpdateMe"];
        trace?: never;
    };
    "/me/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the caller's own effective permissions.
         * @description Resolves the caller's roles to the flat set of named permissions they grant. Advisory only: it exists so the interface can hide actions that would fail, and every server call re-checks regardless of what the client believes.
         */
        get: operations["rbacGetMyPermissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the caller's preferences.
         * @description Returns the full preference set. Every account has one from registration onwards, so this never returns an empty body.
         */
        get: operations["userGetMyPreferences"];
        /**
         * Replace the caller's preferences.
         * @description Replaces the whole preference set. A field left out is not "unchanged", it is a validation failure -- which is what makes this idempotent.
         */
        put: operations["userReplaceMyPreferences"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List roles and the permissions they grant.
         * @description The catalogue is small and fixed, so it is returned whole rather than paginated.
         */
        get: operations["rbacListRoles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The user whose roles are being changed. */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Grant a role to a user.
         * @description Granting is idempotent: a role the user already holds is not an error. An actor cannot grant themselves a role they do not already hold.
         */
        post: operations["rbacAssignRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}/roles/{role}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The user whose roles are being changed. */
                id: string;
                /** @description The role to revoke. */
                role: components["schemas"]["RoleName"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke a role from a user.
         * @description Revoking is idempotent. Two revocations are refused: an actor removing their own `admin` role, and any revocation that would leave the system with no administrator.
         */
        delete: operations["rbacRevokeRole"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search the audit trail.
         * @description Returns audit entries newest first, within a bounded time window.
         *
         *     The window is mandatory in effect: `to` defaults to now and `from` to 90 days before `to`. The table is partitioned by month on `created_at`, and a query with no bound on it reads every partition ever created — so the default is a bounded scan rather than an unbounded one that happens to be fast while the table is young.
         */
        get: operations["auditSearchLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/security-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the security event feed.
         * @description Returns security events newest first, within the same bounded window as the audit trail and for the same reason. `resolved=false` is the triage queue.
         */
        get: operations["auditSearchSecurityEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/security-events/{id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The security event being triaged. */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark a security event triaged.
         * @description Records who closed the event and why. Resolving an already-resolved event is a conflict rather than a silent overwrite: the first explanation is the one that describes what was investigated.
         */
        post: operations["auditResolveSecurityEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description RFC 9457 Problem Details response. */
        Problem: {
            /**
             * Format: uri-reference
             * @description Stable URI identifying the problem type.
             * @example https://fluentra.dev/errors/validation-failed
             */
            type: string;
            /**
             * @description A short, safe, human-readable summary.
             * @example Validation failed
             */
            title: string;
            /**
             * @description HTTP status code for this occurrence.
             * @example 422
             */
            status: number;
            /**
             * @description A safe explanation of this occurrence.
             * @example One or more request fields are invalid.
             */
            detail?: string;
            /**
             * @description Request path that produced the problem.
             * @example /api/v1/auth/register
             */
            instance?: string;
            /**
             * @description Stable machine-readable error code.
             * @example VALIDATION_FAILED
             */
            code: string;
            /**
             * @description Correlation identifier for support and observability.
             * @example 01J8XQ7Z9K3M4N5P6Q7R8S9T0V
             */
            request_id: string;
            /** @description Safe, problem-specific metadata. */
            meta?: {
                [key: string]: unknown;
            };
        };
        ValidationProblem: components["schemas"]["Problem"] & {
            /** @description Field-level validation failures. */
            errors: components["schemas"]["ValidationError"][];
        };
        /** @description One invalid request field. */
        ValidationError: {
            /**
             * @description JSON field path that failed validation.
             * @example email
             */
            field: string;
            /**
             * @description Stable validation error code.
             * @example REQUIRED
             */
            code: string;
            /**
             * @description Localised, safe explanation of the validation failure.
             * @example Email is required.
             */
            message: string;
        };
        /** @description Cursor pagination metadata returned with every user-facing list. */
        Page: {
            /** @description Opaque cursor for the next page, omitted when there is no next page. */
            next_cursor?: components["schemas"]["Cursor"];
            /**
             * @description Whether another page can be requested using next_cursor.
             * @example true
             */
            has_more: boolean;
            /**
             * @description Number of items requested for this page.
             * @example 20
             */
            limit: number;
        };
        /**
         * @description Opaque, URL-safe cursor encoding a stable sort value and ID.
         * @example eyJjIjoiMjAyNi0wOC0wNlQxMDowMDowMFoiLCJpIjoiMDE5M2E3In0
         */
        Cursor: string;
        /** @description Successful API dependency connectivity result. */
        Ping: {
            /**
             * @description Confirms that PostgreSQL and Redis responded.
             * @enum {string}
             */
            status: "ok";
        };
        /** @description Successful process liveness result. */
        Health: {
            /**
             * @description Confirms that the process is serving requests.
             * @enum {string}
             */
            status: "ok";
        };
        /** @description Successful hard dependency readiness result. */
        Ready: {
            /**
             * @description Confirms that every hard dependency is usable.
             * @enum {string}
             */
            status: "ready";
        };
        /** @description Deployed API build version. */
        Version: {
            /**
             * @description Version associated with the running API build.
             * @example 0.1.0
             */
            version: string;
        };
        /** @description Everything needed to open an account. There is deliberately no `locale` or `timezone` beyond what is here: the rest of the profile is filled in after the learner is signed in, so that the registration form stays short. */
        RegisterRequest: {
            /**
             * Format: email
             * @description Normalised to lower case and matched case-insensitively. Whether the address is already registered is never revealed by this operation.
             * @example learner@example.com
             */
            email: string;
            /**
             * Format: password
             * @description At least 12 characters, not equal to the local part of the email, and not present in a public breach corpus. The corpus check fails open, so an outage at the breach service does not block registration.
             * @example a perfectly fine passphrase
             */
            password: string;
            /**
             * @description Shown to other learners. Names that impersonate Fluentra staff are rejected.
             * @example Nghi
             */
            display_name: string;
            /**
             * @description Chooses the language the verification email is written in.
             * @default en
             * @example vi
             */
            locale: string;
            /**
             * @description IANA timezone name.
             * @default UTC
             * @example Asia/Ho_Chi_Minh
             */
            timezone: string;
        };
        /**
         * @description A pending one-time code. The code itself is never in this object, or in any response body: it goes to the email channel and nowhere else, which is what makes it prove control of the address.
         *
         *     The `id` is the handle. A code is worthless without it, so an attacker who guesses six digits with no challenge id has guessed nothing.
         */
        Challenge: {
            /**
             * Format: uuid
             * @description Identifies the challenge in the verify and resend operations.
             */
            challenge_id: string;
            purpose: components["schemas"]["ChallengePurpose"];
            /**
             * Format: date-time
             * @description Absolute expiry, ten minutes from issuance. A resend replaces the code but never moves this.
             */
            expires_at: string;
            /**
             * Format: date-time
             * @description The earliest time a resend will be accepted.
             */
            resend_after: string;
            /**
             * @description Verification attempts left before the challenge is burned permanently.
             * @example 5
             */
            attempts_remaining: number;
        };
        /**
         * @description What a challenge proves. One subsystem serves all four; only `verify_email` is reachable in this version of the API.
         * @enum {string}
         */
        ChallengePurpose: "verify_email" | "login_otp" | "password_reset" | "link_oauth";
        VerifyChallengeRequest: {
            /**
             * @description The six digits from the email.
             * @example 482913
             */
            code: string;
        };
        /**
         * @description The outcome of a successful verification.
         *
         *     It carries no tokens yet. Issuing an access token and a refresh cookie here -- so the learner is signed in without a second step -- is P2.4, which adds them to this schema. Clients written against this version must send the learner to sign in after verifying.
         */
        VerifiedChallenge: {
            purpose: components["schemas"]["ChallengePurpose"];
            /**
             * Format: date-time
             * @description The timestamp at which the address was marked verified.
             */
            verified_at: string;
        };
        LoginRequest: {
            /**
             * Format: email
             * @example learner@example.com
             */
            email: string;
            /**
             * Format: password
             * @example a-secret-password
             */
            password: string;
            /** @default false */
            remember_device: boolean;
            device_id?: string;
        };
        /** @description The authenticated caller's own account. There is no operation that returns this shape for anybody else: the server reads the actor from the access token and the path carries no user id. */
        Me: {
            /**
             * Format: uuid
             * @description Stable identifier every other resource references.
             */
            id: string;
            /**
             * Format: email
             * @description Returned only here. No other operation exposes a user's email address.
             * @example learner@example.com
             */
            email: string;
            status: components["schemas"]["UserStatus"];
            /**
             * Format: date-time
             * @description When the address was verified, or null while it is unverified.
             */
            email_verified_at?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            profile: components["schemas"]["MeProfile"];
        };
        /** @description Descriptive data about the caller. Nothing here is used to authenticate. */
        MeProfile: {
            /**
             * @description Shown to other learners. Names that impersonate Fluentra staff are rejected.
             * @example Nghi
             */
            display_name: string;
            /**
             * Format: uri
             * @description Public avatar URL, or null when none has been uploaded.
             */
            avatar_url?: string | null;
            /**
             * @description ISO 3166-1 alpha-2 country code, or null.
             * @example VN
             */
            country?: string | null;
            /**
             * @description IANA timezone name. Every timestamp in the API stays UTC; this is used to place reminders and streak boundaries in the learner's day.
             * @example Asia/Ho_Chi_Minh
             */
            timezone: string;
            /**
             * Format: date
             * @description Used only for the age gate. It is never shown to other learners and never leaves this operation.
             */
            date_of_birth?: string | null;
        };
        /**
         * @description Account lifecycle state. `pending_deletion` is the 30-day grace period, in which the account is unusable but still recoverable by the owner.
         * @enum {string}
         */
        UserStatus: "active" | "suspended" | "pending_deletion" | "deleted";
        /** @description A partial update. Omit a field to leave it unchanged; an unknown field is a validation failure rather than something quietly ignored, because a misspelled field name that returns 200 is indistinguishable from success. */
        UpdateMeRequest: {
            /** @example Nghi Nguyen */
            display_name?: string;
            /** @example VN */
            country?: string;
            /** @example Asia/Ho_Chi_Minh */
            timezone?: string;
            /**
             * Format: date
             * @example 1998-03-04
             */
            date_of_birth?: string;
        };
        /** @description The caller's settings. Replaced as a whole, never patched. */
        Preferences: {
            /**
             * @description BCP 47 language tag, optionally with a region.
             * @example vi
             */
            locale: string;
            /** @enum {string} */
            theme: "light" | "dark" | "system";
            /**
             * @description Minutes of study the learner is aiming for each day.
             * @example 15
             */
            daily_goal_minutes: number;
            /**
             * @description Channels the learner accepts notifications on.
             * @example [
             *       "in_app",
             *       "email"
             *     ]
             */
            notification_channels: ("in_app" | "email" | "push")[];
            /** @description A window in which no notification is delivered, or null for none. It is one object rather than two fields so that half a window cannot be expressed. */
            quiet_hours?: components["schemas"]["QuietHours"] | null;
            /** @description Disables AI grading only. Deterministic exercises keep working, so opting out never costs the learner access to the product. */
            ai_processing_opt_out: boolean;
            /** Format: date-time */
            updated_at: string;
        };
        /** @description Local wall-clock times in the learner's timezone. A window may wrap past midnight, which is the normal case for sleeping hours. */
        QuietHours: {
            /** @example 22:00 */
            start: string;
            /** @example 07:00 */
            end: string;
        };
        /** @description The complete preference set. This is a PUT: every field is required, and what the caller sends is exactly what is stored. */
        ReplacePreferencesRequest: {
            /** @example vi */
            locale: string;
            /** @enum {string} */
            theme: "light" | "dark" | "system";
            /** @example 30 */
            daily_goal_minutes: number;
            /**
             * @example [
             *       "in_app",
             *       "push"
             *     ]
             */
            notification_channels: ("in_app" | "email" | "push")[];
            quiet_hours?: components["schemas"]["QuietHours"] | null;
            /** @example false */
            ai_processing_opt_out: boolean;
        };
        /**
         * @description What the caller is allowed to do, as the server currently sees it.
         *     This is advisory (BR-RBAC-08). It exists so the interface can hide actions that would fail, not so the client can decide anything: every server call re-checks, and a client that has this list is no closer to using a permission it was not granted.
         */
        MyPermissions: {
            /**
             * @description The roles assigned to the caller. There are exactly two in this product.
             * @example [
             *       "user"
             *     ]
             */
            roles: components["schemas"]["RoleName"][];
            /**
             * @description Every named permission the caller's roles grant, resolved and flattened. A learner holds none of these — access to their own data is not a named permission, it is what `/me` means.
             * @example []
             */
            permissions: string[];
        };
        /**
         * @description Exactly two roles exist (BR-RBAC-02). A third is an ADR, not a row: it changes the shape of the product rather than its data.
         * @enum {string}
         */
        RoleName: "admin" | "user";
        /** @description A role and the permissions it grants. */
        Role: {
            name: components["schemas"]["RoleName"];
            /** @example Full administrative access. */
            description: string;
            /**
             * @example [
             *       "rbac.assign",
             *       "rbac.read",
             *       "user.list"
             *     ]
             */
            permissions: string[];
        };
        /** @description The role catalogue. It is small and fixed, so it is not paginated. */
        RoleList: {
            items: components["schemas"]["Role"][];
        };
        /** @description Grant a role to a user. */
        AssignRoleRequest: {
            role: components["schemas"]["RoleName"];
        };
        /** @description The roles held by one user, after the change. */
        UserRoles: {
            /** Format: uuid */
            user_id: string;
            /**
             * @example [
             *       "admin",
             *       "user"
             *     ]
             */
            roles: components["schemas"]["RoleName"][];
        };
        /**
         * @description One recorded action: who did it, to what, and which fields moved.
         *     It deliberately does not carry the values that changed (BR-AUDIT-04). An audit trail that stored the old and new display name would be a second copy of personal data with a longer retention period than the first, which is the opposite of what an audit trail is for.
         */
        AuditLog: {
            /**
             * Format: uuid
             * @description Stable identifier for this entry.
             */
            id: string;
            /**
             * Format: date-time
             * @description When the action happened, taken from the emitting module's event rather than from when this row was written. It is also the partition key, so every search is bounded by it.
             * @example 2026-08-10T09:15:00Z
             */
            created_at: string;
            /**
             * Format: uuid
             * @description The account that performed the action, or null when the system did it or when the actor's account has since been erased. Entries outlive the people in them (BR-AUDIT-06).
             */
            actor_id?: string | null;
            actor_role?: components["schemas"]["ActorRole"];
            action: components["schemas"]["AuditAction"];
            /**
             * @description The kind of thing acted on, such as `user` or `role_assignment`.
             * @example user
             */
            target_type?: string | null;
            /**
             * @description Identifier of the thing acted on. It is a string rather than a uuid because not every auditable target is keyed by one.
             * @example 0199a1c2-3d4e-7f80-9abc-def012345678
             */
            target_id?: string | null;
            /**
             * @description Names of the fields the action moved, sorted. Empty when the action changed no fields — a read, a grant, a revocation.
             * @example [
             *       "display_name",
             *       "timezone"
             *     ]
             */
            changed_fields: string[];
            /** @description Prior values for the changed fields, with anything on the PII deny-list replaced by `[redacted]`. Null when the emitting module sent field names only, which is the Phase 1 default. */
            before?: {
                [key: string]: unknown;
            } | null;
            /** @description New values, redacted on the same terms as `before`. */
            after?: {
                [key: string]: unknown;
            } | null;
            /**
             * @description Context that is not a field of the target — the reason an administrator gave, the outbox event that produced the entry. Redacted on the same deny-list as the diff.
             * @example {
             *       "source": "outbox"
             *     }
             */
            meta: {
                [key: string]: unknown;
            };
            /**
             * @description The W3C trace this action belongs to (BR-AUDIT-07), so an entry links straight through to the distributed trace that produced it.
             * @example 4bf92f3577b34da6a3ce929d0e0e4736
             */
            trace_id?: string | null;
        };
        /**
         * @description What happened, named `<module>.<verb>_<object>`. The catalogue lives in `internal/modules/audit/AGENT.md`; unknown names are stored rather than rejected, because refusing an entry loses the record of the very thing that was unexpected.
         * @example user.profile_updated
         */
        AuditAction: string;
        /**
         * @description The role the actor held at the time, recorded rather than resolved: a revoked admin must still show as an admin in the entries they left behind.
         * @enum {string|null}
         */
        ActorRole: "admin" | "user" | "system" | null;
        /** @description One page of audit entries, newest first. */
        AuditLogPage: {
            items: components["schemas"]["AuditLog"][];
            page: components["schemas"]["Page"];
        };
        /** @description A security-relevant occurrence: a failed permission check, a lockout, a token reuse. Separate from the audit trail because these are triaged rather than merely recorded, and because they are not always attributable to a known actor. */
        SecurityEvent: {
            /** Format: uuid */
            id: string;
            /**
             * Format: date-time
             * @description When the event occurred. Also the partition key.
             * @example 2026-08-10T09:15:00Z
             */
            created_at: string;
            /**
             * @description What happened, named `<module>.<event>`.
             * @example rbac.access_denied
             */
            kind: string;
            severity: components["schemas"]["SecurityEventSeverity"];
            /**
             * Format: uuid
             * @description The account involved, when one is known. Null for events observed before authentication succeeded.
             */
            user_id?: string | null;
            /**
             * @description Structured context for triage, redacted on the same terms as an audit diff. It never carries the request body: an event raised by an attacker would otherwise store whatever they chose to send.
             * @example {
             *       "permission": "user.suspend"
             *     }
             */
            detail: {
                [key: string]: unknown;
            };
            /**
             * @description The trace the event was raised in.
             * @example 4bf92f3577b34da6a3ce929d0e0e4736
             */
            trace_id?: string | null;
            /**
             * Format: date-time
             * @description When an administrator marked the event triaged, or null while it is open.
             */
            resolved_at?: string | null;
            /**
             * Format: uuid
             * @description The administrator who triaged it.
             */
            resolved_by?: string | null;
            /**
             * @description Why it was closed. Required when resolving, so a closed event explains itself.
             * @example Known load test, permission denial expected.
             */
            resolution_note?: string | null;
        };
        /**
         * @description How much attention the event deserves. `critical` is reserved for events that indicate a compromise in progress, such as refresh-token reuse.
         * @enum {string}
         */
        SecurityEventSeverity: "low" | "medium" | "high" | "critical";
        /** @description One page of security events, newest first. */
        SecurityEventPage: {
            items: components["schemas"]["SecurityEvent"][];
            page: components["schemas"]["Page"];
        };
        /** @description Mark a security event triaged. The note is required: an event closed with no reason is indistinguishable from one closed by accident. */
        ResolveSecurityEventRequest: {
            /** @example Known load test, permission denial expected. */
            note: string;
        };
    };
    responses: {
        /** @description The request is malformed or has an invalid cursor. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://fluentra.dev/errors/bad-request",
                 *       "title": "Bad request",
                 *       "status": 400,
                 *       "detail": "The request body could not be decoded.",
                 *       "code": "BAD_REQUEST",
                 *       "request_id": "01J8XQ7Z9K3M4N5P6Q7R8S9T0V"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Authentication credentials are missing, invalid, or expired. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://fluentra.dev/errors/unauthenticated",
                 *       "title": "Authentication required",
                 *       "status": 401,
                 *       "detail": "Provide a valid access token.",
                 *       "code": "UNAUTHENTICATED",
                 *       "request_id": "01J8XQ7Z9K3M4N5P6Q7R8S9T0V"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The authenticated actor lacks permission for this operation. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://fluentra.dev/errors/permission-denied",
                 *       "title": "Permission denied",
                 *       "status": 403,
                 *       "detail": "You do not have permission to perform this action.",
                 *       "code": "PERMISSION_DENIED",
                 *       "request_id": "01J8XQ7Z9K3M4N5P6Q7R8S9T0V"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The resource does not exist or is not visible to this actor. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://fluentra.dev/errors/not-found",
                 *       "title": "Not found",
                 *       "status": 404,
                 *       "detail": "The requested resource was not found.",
                 *       "code": "NOT_FOUND",
                 *       "request_id": "01J8XQ7Z9K3M4N5P6Q7R8S9T0V"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The requested operation conflicts with the current resource state. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://fluentra.dev/errors/conflict",
                 *       "title": "Conflict",
                 *       "status": 409,
                 *       "detail": "The operation conflicts with the current resource state.",
                 *       "code": "CONFLICT",
                 *       "request_id": "01J8XQ7Z9K3M4N5P6Q7R8S9T0V"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description One or more request fields failed validation. */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://fluentra.dev/errors/validation-failed",
                 *       "title": "Validation failed",
                 *       "status": 422,
                 *       "detail": "One or more request fields are invalid.",
                 *       "code": "VALIDATION_FAILED",
                 *       "request_id": "01J8XQ7Z9K3M4N5P6Q7R8S9T0V",
                 *       "errors": [
                 *         {
                 *           "field": "email",
                 *           "code": "EMAIL",
                 *           "message": "Enter a valid email address."
                 *         }
                 *       ]
                 *     }
                 */
                "application/problem+json": components["schemas"]["ValidationProblem"];
            };
        };
        /** @description The applicable rate limit has been exceeded. */
        TooManyRequests: {
            headers: {
                "Retry-After": components["headers"]["Retry-After"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://fluentra.dev/errors/rate-limited",
                 *       "title": "Too many requests",
                 *       "status": 429,
                 *       "detail": "Retry after the indicated interval.",
                 *       "code": "RATE_LIMITED",
                 *       "request_id": "01J8XQ7Z9K3M4N5P6Q7R8S9T0V"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description An unexpected server error occurred without exposing internals. */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://fluentra.dev/errors/internal",
                 *       "title": "Internal server error",
                 *       "status": 500,
                 *       "detail": "An unexpected error occurred.",
                 *       "code": "INTERNAL",
                 *       "request_id": "01J8XQ7Z9K3M4N5P6Q7R8S9T0V"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description A hard dependency is not available. */
        ServiceUnavailable: {
            headers: {
                "Retry-After": components["headers"]["Retry-After"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://fluentra.dev/errors/dependency-unavailable",
                 *       "title": "Service unavailable",
                 *       "status": 503,
                 *       "detail": "A required service is temporarily unavailable.",
                 *       "code": "DEPENDENCY_UNAVAILABLE",
                 *       "request_id": "01J8XQ7Z9K3M4N5P6Q7R8S9T0V"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: {
        /**
         * @description Correlation ID supplied by the client or generated by the API.
         * @example 01J8XQ7Z9K3M4N5P6Q7R8S9T0V
         */
        "X-Request-Id": string;
        /**
         * @description Entity tag for a cacheable or mutable resource.
         * @example "v1-01J8XQ7Z9K3M4N5P6Q7R8S9T0V"
         */
        ETag: string;
        /**
         * @description Cache directive; authenticated responses default to no-store.
         * @example no-store
         */
        "Cache-Control": string;
        /**
         * @description Maximum requests permitted in the current rate-limit window.
         * @example 60
         */
        "RateLimit-Limit": number;
        /**
         * @description Requests remaining in the current rate-limit window.
         * @example 59
         */
        "RateLimit-Remaining": number;
        /**
         * @description Unix timestamp when the current rate-limit window resets.
         * @example 1786033260
         */
        "RateLimit-Reset": number;
        /**
         * @description Number of seconds before the request may be retried.
         * @example 30
         */
        "Retry-After": number;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    systemPing: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The API and its immediate dependencies responded. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok"
                     *     }
                     */
                    "application/json": components["schemas"]["Ping"];
                };
            };
        };
    };
    systemHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The API process is live. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok"
                     *     }
                     */
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    systemReady: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All hard dependencies are ready. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ready"
                     *     }
                     */
                    "application/json": components["schemas"]["Ready"];
                };
            };
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    systemVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The deployed API version. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "version": "0.1.0"
                     *     }
                     */
                    "application/json": components["schemas"]["Version"];
                };
            };
        };
    };
    authRegister: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "email": "learner@example.com",
                 *       "password": "a perfectly fine passphrase",
                 *       "display_name": "Nghi",
                 *       "locale": "vi",
                 *       "timezone": "Asia/Ho_Chi_Minh"
                 *     }
                 */
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description A challenge was issued. This is also the response when the address was already registered -- deliberately indistinguishable. */
            201: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "challenge_id": "0199a1c2-3d4e-7f80-9abc-def012345678",
                     *       "purpose": "verify_email",
                     *       "expires_at": "2026-08-10T09:10:00Z",
                     *       "resend_after": "2026-08-10T09:01:00Z",
                     *       "attempts_remaining": 5
                     *     }
                     */
                    "application/json": components["schemas"]["Challenge"];
                };
            };
            400: components["responses"]["BadRequest"];
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    authLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "email": "learner@example.com",
                 *       "password": "a-secret-password"
                 *     }
                 */
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description User authenticated successfully. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        user_id: string;
                        verified: boolean;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    authVerifyChallenge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The challenge handle returned when it was issued. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "code": "482913"
                 *     }
                 */
                "application/json": components["schemas"]["VerifyChallengeRequest"];
            };
        };
        responses: {
            /** @description The code was accepted and the challenge consumed. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "purpose": "verify_email",
                     *       "verified_at": "2026-08-10T09:03:12Z"
                     *     }
                     */
                    "application/json": components["schemas"]["VerifiedChallenge"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    authResendChallenge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The challenge to send a new code for. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A new code was sent. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "challenge_id": "0199a1c2-3d4e-7f80-9abc-def012345678",
                     *       "purpose": "verify_email",
                     *       "expires_at": "2026-08-10T09:10:00Z",
                     *       "resend_after": "2026-08-10T09:01:00Z",
                     *       "attempts_remaining": 5
                     *     }
                     */
                    "application/json": components["schemas"]["Challenge"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    userGetMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's account. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "0199a1c2-3d4e-7f80-9abc-def012345678",
                     *       "email": "learner@example.com",
                     *       "status": "active",
                     *       "email_verified_at": "2026-08-09T04:21:07Z",
                     *       "created_at": "2026-08-01T09:15:00Z",
                     *       "updated_at": "2026-08-09T04:21:07Z",
                     *       "profile": {
                     *         "display_name": "Nghi",
                     *         "avatar_url": null,
                     *         "country": "VN",
                     *         "timezone": "Asia/Ho_Chi_Minh",
                     *         "date_of_birth": "1998-03-04"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    userUpdateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "display_name": "Nghi Nguyen",
                 *       "timezone": "Asia/Ho_Chi_Minh"
                 *     }
                 */
                "application/json": components["schemas"]["UpdateMeRequest"];
            };
        };
        responses: {
            /** @description The updated account. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "0199a1c2-3d4e-7f80-9abc-def012345678",
                     *       "email": "learner@example.com",
                     *       "status": "active",
                     *       "email_verified_at": "2026-08-09T04:21:07Z",
                     *       "created_at": "2026-08-01T09:15:00Z",
                     *       "updated_at": "2026-08-09T04:21:07Z",
                     *       "profile": {
                     *         "display_name": "Nghi",
                     *         "avatar_url": null,
                     *         "country": "VN",
                     *         "timezone": "Asia/Ho_Chi_Minh",
                     *         "date_of_birth": "1998-03-04"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["Me"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    rbacGetMyPermissions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's roles and permissions. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "roles": [
                     *         "user"
                     *       ],
                     *       "permissions": []
                     *     }
                     */
                    "application/json": components["schemas"]["MyPermissions"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    userGetMyPreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's preferences. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "locale": "vi",
                     *       "theme": "dark",
                     *       "daily_goal_minutes": 30,
                     *       "notification_channels": [
                     *         "in_app",
                     *         "push"
                     *       ],
                     *       "quiet_hours": {
                     *         "start": "22:00",
                     *         "end": "07:00"
                     *       },
                     *       "ai_processing_opt_out": false,
                     *       "updated_at": "2026-08-09T04:21:07Z"
                     *     }
                     */
                    "application/json": components["schemas"]["Preferences"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    userReplaceMyPreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "locale": "vi",
                 *       "theme": "dark",
                 *       "daily_goal_minutes": 30,
                 *       "notification_channels": [
                 *         "in_app",
                 *         "push"
                 *       ],
                 *       "quiet_hours": {
                 *         "start": "22:00",
                 *         "end": "07:00"
                 *       },
                 *       "ai_processing_opt_out": false
                 *     }
                 */
                "application/json": components["schemas"]["ReplacePreferencesRequest"];
            };
        };
        responses: {
            /** @description The stored preferences. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "locale": "vi",
                     *       "theme": "dark",
                     *       "daily_goal_minutes": 30,
                     *       "notification_channels": [
                     *         "in_app",
                     *         "push"
                     *       ],
                     *       "quiet_hours": {
                     *         "start": "22:00",
                     *         "end": "07:00"
                     *       },
                     *       "ai_processing_opt_out": false,
                     *       "updated_at": "2026-08-09T04:21:07Z"
                     *     }
                     */
                    "application/json": components["schemas"]["Preferences"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    rbacListRoles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every role, with its permissions. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "items": [
                     *         {
                     *           "name": "admin",
                     *           "description": "Full administrative access.",
                     *           "permissions": [
                     *             "rbac.assign",
                     *             "rbac.read",
                     *             "user.list"
                     *           ]
                     *         },
                     *         {
                     *           "name": "user",
                     *           "description": "A learner. Holds no named permissions.",
                     *           "permissions": []
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["RoleList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    rbacAssignRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The user whose roles are being changed. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "role": "admin"
                 *     }
                 */
                "application/json": components["schemas"]["AssignRoleRequest"];
            };
        };
        responses: {
            /** @description The user's roles after the grant. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "user_id": "0199a1c2-3d4e-7f80-9abc-def012345678",
                     *       "roles": [
                     *         "admin",
                     *         "user"
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["UserRoles"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    rbacRevokeRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The user whose roles are being changed. */
                id: string;
                /** @description The role to revoke. */
                role: components["schemas"]["RoleName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The user's roles after the revocation. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "user_id": "0199a1c2-3d4e-7f80-9abc-def012345678",
                     *       "roles": [
                     *         "admin",
                     *         "user"
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["UserRoles"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    auditSearchLogs: {
        parameters: {
            query?: {
                /** @description Only entries recorded against this actor. */
                actor_id?: string;
                /** @description Exact action name, such as `user.profile_updated`. */
                action?: components["schemas"]["AuditAction"];
                /** @description Only entries whose target is of this kind. */
                target_type?: string;
                /** @description Only entries against this target. Combined with `target_type` it is the "who touched this record" query. */
                target_id?: string;
                /** @description Inclusive lower bound on `created_at`. Defaults to 90 days before `to`. */
                from?: string;
                /** @description Exclusive upper bound on `created_at`. Defaults to now. */
                to?: string;
                /** @description Opaque cursor from the previous page's `next_cursor`. */
                cursor?: components["schemas"]["Cursor"];
                /** @description Maximum entries to return. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of audit entries. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "items": [
                     *         {
                     *           "id": "0199a1c2-3d4e-7f80-9abc-def012345678",
                     *           "created_at": "2026-08-10T09:15:00Z",
                     *           "actor_id": "0199a1c2-3d4e-7f80-9abc-def012345679",
                     *           "actor_role": "user",
                     *           "action": "user.profile_updated",
                     *           "target_type": "user",
                     *           "target_id": "0199a1c2-3d4e-7f80-9abc-def012345679",
                     *           "changed_fields": [
                     *             "display_name",
                     *             "timezone"
                     *           ],
                     *           "before": null,
                     *           "after": null,
                     *           "meta": {
                     *             "source": "outbox"
                     *           },
                     *           "trace_id": "4bf92f3577b34da6a3ce929d0e0e4736"
                     *         }
                     *       ],
                     *       "page": {
                     *         "has_more": false,
                     *         "limit": 20
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["AuditLogPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    auditSearchSecurityEvents: {
        parameters: {
            query?: {
                /** @description Exact event kind, such as `rbac.access_denied`. */
                kind?: string;
                /** @description Only events at this severity. */
                severity?: components["schemas"]["SecurityEventSeverity"];
                /** @description `false` returns only open events, `true` only triaged ones. Omitted returns both. */
                resolved?: boolean;
                /** @description Only events involving this account. */
                user_id?: string;
                /** @description Inclusive lower bound on `created_at`. Defaults to 90 days before `to`. */
                from?: string;
                /** @description Exclusive upper bound on `created_at`. Defaults to now. */
                to?: string;
                /** @description Opaque cursor from the previous page's `next_cursor`. */
                cursor?: components["schemas"]["Cursor"];
                /** @description Maximum events to return. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of security events. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "items": [
                     *         {
                     *           "id": "0199a1c2-3d4e-7f80-9abc-def01234567a",
                     *           "created_at": "2026-08-10T09:15:00Z",
                     *           "kind": "rbac.access_denied",
                     *           "severity": "medium",
                     *           "user_id": "0199a1c2-3d4e-7f80-9abc-def012345679",
                     *           "detail": {
                     *             "permission": "user.suspend"
                     *           },
                     *           "trace_id": "4bf92f3577b34da6a3ce929d0e0e4736",
                     *           "resolved_at": null,
                     *           "resolved_by": null,
                     *           "resolution_note": null
                     *         }
                     *       ],
                     *       "page": {
                     *         "has_more": false,
                     *         "limit": 20
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["SecurityEventPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    auditResolveSecurityEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The security event being triaged. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "note": "Known load test, permission denial expected."
                 *     }
                 */
                "application/json": components["schemas"]["ResolveSecurityEventRequest"];
            };
        };
        responses: {
            /** @description The resolved event. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "0199a1c2-3d4e-7f80-9abc-def01234567a",
                     *       "created_at": "2026-08-10T09:15:00Z",
                     *       "kind": "rbac.access_denied",
                     *       "severity": "medium",
                     *       "user_id": "0199a1c2-3d4e-7f80-9abc-def012345679",
                     *       "detail": {
                     *         "permission": "user.suspend"
                     *       },
                     *       "trace_id": "4bf92f3577b34da6a3ce929d0e0e4736",
                     *       "resolved_at": "2026-08-10T10:02:00Z",
                     *       "resolved_by": "0199a1c2-3d4e-7f80-9abc-def012345678",
                     *       "resolution_note": "Known load test, permission denial expected."
                     *     }
                     */
                    "application/json": components["schemas"]["SecurityEvent"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationFailed"];
        };
    };
}
