package service

import (
	"math/rand/v2"
	"strings"

	learningcontract "github.com/fluentra/fluentra/internal/modules/learning/contract"
)

// examTopics are the subjects an exam item is written about, one drawn at
// random per item. Without one the model returned the same two reading
// passages (night trains, urban beekeeping) six times over, so a composed test
// read three texts on one subject. With sixty, a VSTEP bank of some hundred
// items still drew tea and farmers' markets three times each, so there are
// now a hundred and fifty. The list mixes the workplace (TOEIC), the
// academic (IELTS) and everyday life (VSTEP), and avoids subjects a learner
// could be upset by.
var examTopics = []string{
	"a company moving to a new office building",
	"hiring and training new staff at a small firm",
	"a product launch that was delayed",
	"customer complaints at a hotel",
	"planning a trade fair or conference",
	"a supplier changing its delivery schedule",
	"working from home and hybrid offices",
	"a restaurant changing its menu",
	"an airline updating its baggage rules",
	"a bank opening a digital-only branch",
	"repairs to a public swimming pool",
	"a city introducing bike-sharing",
	"a museum reopening after renovation",
	"a local farmers' market",
	"volunteering at an animal shelter",
	"learning a musical instrument as an adult",
	"a community theatre production",
	"a family moving to a new city",
	"renting a first flat",
	"saving money for a holiday",
	"the history of the printing press",
	"how glaciers shape landscapes",
	"the migration of Arctic terns",
	"coral reefs and ocean temperature",
	"the invention of refrigeration",
	"why some languages disappear",
	"how sleep affects memory",
	"early human use of fire",
	"the science of weather forecasting",
	"desert plants that survive without rain",
	"how bridges are designed to resist wind",
	"the economics of fast fashion",
	"traditional crafts in the digital age",
	"the development of the bicycle",
	"how children learn to read",
	"the design of public libraries",
	"recycling electronic waste",
	"the spread of tea as a drink around the world",
	"volcanoes and the soil around them",
	"the architecture of ancient Rome",
	"space telescopes and distant planets",
	"the psychology of first impressions",
	"food waste in supermarkets",
	"the rise of electric buses",
	"rice farming in river deltas",
	"the role of bees and other pollinators in farming",
	"street food cultures in Asian cities",
	"how maps were made before satellites",
	"noise pollution in cities",
	"the benefits of learning a second language",
	"a school sports day",
	"a weekend camping trip",
	"choosing a university course",
	"a new public park opening",
	"a problem with an online order",
	"a guided tour of a factory",
	"a health clinic changing its opening hours",
	"a science museum's summer programme",
	"a cooking class for beginners",
	"a lost property office at a railway station",
	"a start-up choosing its first office",
	"a customer loyalty programme at a bookshop",
	"a hospital introducing online appointments",
	"a delivery company testing electric vans",
	"a staff survey about the canteen",
	"a hotel training receptionists",
	"a factory changing its shift patterns",
	"a charity organising a fun run",
	"an office introducing a four-day week",
	"a car-sharing scheme for commuters",
	"a company sponsoring a local football team",
	"a printing firm switching to recycled paper",
	"a cinema reopening with new seats",
	"a travel agency planning a group tour",
	"a building society's new savings account",
	"a gym changing its membership fees",
	"a supermarket removing plastic bags",
	"an internship at a newspaper",
	"a conference moving online",
	"a bakery expanding into a second shop",
	"a language school opening evening classes",
	"a university library extending its hours",
	"a student choosing between two part-time jobs",
	"a school trip to a nature reserve",
	"a first day at a new job",
	"preparing for a driving test",
	"learning to swim as an adult",
	"a neighbourhood clean-up day",
	"a family reunion abroad",
	"buying a second-hand car",
	"a wedding planned on a small budget",
	"looking after a neighbour's pet",
	"a birthday party that went wrong",
	"joining a hiking club",
	"a photography competition",
	"growing vegetables on a balcony",
	"a power cut in an apartment building",
	"a community radio station",
	"a book club choosing its next book",
	"a village festival",
	"a bus route being cancelled",
	"a lost passport before a flight",
	"the history of the postal service",
	"how honeybees communicate",
	"why cities build green roofs",
	"the invention of the telephone",
	"how deserts expand",
	"the life cycle of a star",
	"how vaccines are tested",
	"the history of chocolate",
	"why some animals hibernate",
	"how earthquakes are measured",
	"the science of rainbows",
	"the history of the Olympic Games",
	"how tides work",
	"the discovery of penicillin",
	"how paper is made",
	"the migration of monarch butterflies",
	"how salt was once used as money",
	"the history of public clocks",
	"how solar panels produce electricity",
	"why the sea is salty",
	"the building of the Suez Canal",
	"how wolves live in packs",
	"the history of the umbrella",
	"how rivers change course",
	"the origin of board games",
	"how bats find their way in the dark",
	"the history of street lighting",
	"how bamboo grows so quickly",
	"the role of museums in education",
	"the effect of advertising on children",
	"the growth of online shopping",
	"why people collect things",
	"the value of learning history at school",
	"the rise of cycling to work",
	"tourism in small islands",
	"the benefits of team sports",
	"the use of mobile phones in classrooms",
	"volunteering among older people",
	"the future of printed newspapers",
	"the popularity of home cooking",
	"living in a shared house",
	"the effect of music on concentration",
	"the rise of second-hand clothing",
	"why people move from villages to cities",
	"the importance of city parks for health",
	"gap years before university",
	"the role of grandparents in childcare",
	"traffic congestion in growing cities",
}

// workplaceTopics are the subjects a TOEIC item may take. TOEIC tests English
// at work and in daily life; drawn from the whole list, Part 2 came back as
// general-knowledge quizzes ("Why is the sea salty?", "How far do Arctic
// terns migrate?").
var workplaceTopics = []string{
	"a company moving to a new office building",
	"hiring and training new staff at a small firm",
	"a product launch that was delayed",
	"customer complaints at a hotel",
	"planning a trade fair or conference",
	"a supplier changing its delivery schedule",
	"working from home and hybrid offices",
	"a restaurant changing its menu",
	"an airline updating its baggage rules",
	"a bank opening a digital-only branch",
	"repairs to a public swimming pool",
	"a city introducing bike-sharing",
	"a museum reopening after renovation",
	"a health clinic changing its opening hours",
	"a problem with an online order",
	"a guided tour of a factory",
	"a start-up choosing its first office",
	"a customer loyalty programme at a bookshop",
	"a hospital introducing online appointments",
	"a delivery company testing electric vans",
	"a staff survey about the canteen",
	"a hotel training receptionists",
	"a factory changing its shift patterns",
	"a charity organising a fun run",
	"an office introducing a four-day week",
	"a car-sharing scheme for commuters",
	"a company sponsoring a local football team",
	"a printing firm switching to recycled paper",
	"a cinema reopening with new seats",
	"a travel agency planning a group tour",
	"a gym changing its membership fees",
	"a supermarket removing plastic bags",
	"an internship at a newspaper",
	"a conference moving online",
	"a bakery expanding into a second shop",
	"a language school opening evening classes",
	"a first day at a new job",
	"a bus route being cancelled",
	"a lost passport before a flight",
	"a power cut in an apartment building",
	// Part 7 alone needs 270 texts; with the forty subjects above, a round
	// wrote the same canteen survey and van trial three times over.
	"an accounting firm changing its expense-claim rules",
	"a warehouse installing a new stock-tracking system",
	"a hotel chain launching a guest mobile app",
	"a software company opening a support centre abroad",
	"a city marathon changing its route",
	"a dental clinic moving to a new address",
	"a furniture store offering free assembly",
	"a car rental agency adding electric cars",
	"a public library lending laptops",
	"an office building upgrading its lifts",
	"a food delivery app adding new restaurants",
	"a pharmacy extending its opening hours",
	"an art gallery hiring weekend guides",
	"a coffee chain introducing reusable cups",
	"a manufacturer recalling a faulty kettle",
	"a real estate agent listing a new office space",
	"a university career fair for employers",
	"a telecom company upgrading its network",
	"a farm shop starting home delivery",
	"a law firm offering free advice sessions",
	"a publisher launching an online magazine",
	"a sports centre adding yoga classes",
	"a train operator changing its timetable",
	"a hardware store running a DIY workshop",
	"a catering company planning a wedding reception",
	"a clothing brand opening a pop-up shop",
	"a tech firm hosting a hackathon",
	"a museum shop selling local crafts online",
	"a city council repairing a main road",
	"a company introducing flexible start times",
	"a department store holding a clearance sale",
	"an electronics shop offering trade-in discounts",
	"a restaurant hiring seasonal staff",
	"an insurance company changing its claims process",
	"a water company planning maintenance work",
	"a school recruiting part-time tutors",
	"a gardening firm offering winter services",
	"a hotel hosting a business awards dinner",
	"a start-up seeking investors",
	"an office recycling programme",
	"a company holiday party",
	"a new staff parking policy",
	"an employee wellness programme",
	"a shipping company delaying a container",
	"a translation agency hiring freelancers",
	"a zoo opening a new exhibit",
	"a theatre selling season tickets",
	"a design agency winning a new client",
	"a cleaning service changing its prices",
	"a printing shop offering same-day orders",
	"a bicycle repair shop expanding",
	"a farmers' cooperative selling to supermarkets",
	"a technology conference call for speakers",
	"a cooking school offering corporate team events",
	"a newspaper changing its subscription plans",
	"a customer survey about a delivery service",
	"a company moving its payroll online",
	"an airport opening a new lounge",
	"a solar panel installer offering free quotes",
	"a supermarket extending self-checkout",
	"a construction firm finishing a housing project",
	"a music school hosting a student concert",
	"a garage offering winter car checks",
	"an office cafeteria changing supplier",
	"a courier company opening a parcel locker network",
	"a photography studio offering business portraits",
	"a campsite taking early bookings",
	"a local radio station seeking sponsors",
	"a stationery supplier discontinuing a product",
	"an event venue installing new sound equipment",
	"a volunteer programme at a food bank",
	"a hotel renovating its conference rooms",
	"a job applicant following up after an interview",
	"a manager confirming a client meeting",
	"a customer requesting a refund",
	"an employee requesting time off",
	"a supplier sending a revised invoice",
	"a team rescheduling a project deadline",
	"a landlord announcing building repairs",
	"a company announcing a new branch manager",
}

// toeicForms are the kinds of document a TOEIC reading text may take (Parts 6
// and 7): two texts on one subject read differently when one is a memo and the
// other an online review.
var toeicForms = []string{
	"an email", "an internal memo", "a public notice", "an advertisement", "a news article",
	"an online customer review", "a text-message chain between colleagues", "a letter",
	"a web page", "a schedule or itinerary", "an invoice or order confirmation", "a form with notes",
	"a job advertisement", "a product description", "a press release",
}

// toeicSource marks a TOEIC part in the format table's source note.
const toeicSource = "TOEIC"

// examTopic draws the subject for one exam item: from the workplace list for a
// TOEIC part, from the whole list otherwise.
//
// A TOEIC reading text also draws its form ("… written as a memo").
func examTopic(c *learningcontract.ExamPartConstraints, kind string) string {
	//nolint:gosec // topic draws, not secrets
	if c != nil && strings.Contains(c.Source, toeicSource) {
		topic := workplaceTopics[rand.IntN(len(workplaceTopics))]
		if kind == kindReadingComprehension || kind == kindTextCompletion {
			topic += ", written as " + toeicForms[rand.IntN(len(toeicForms))]
		}
		return topic
	}
	return examTopics[rand.IntN(len(examTopics))] //nolint:gosec // a topic draw, not a secret
}
