FROM golang:1.25-alpine

RUN apk add --no-cache git ca-certificates tzdata

RUN go install github.com/air-verse/air@latest

WORKDIR /app

COPY go.mod go.sum ./
RUN --mount=type=cache,target=/go/pkg/mod go mod download

COPY . .

CMD ["air"]
