package main

type seedCourse struct {
	Slug           string
	Title          string
	Description    string
	CEFRFrom       string
	CEFRTo         string
	EstimatedHours int
	Units          []seedUnit
}

type seedUnit struct {
	Position    int
	Title       string
	Description string
	Lessons     []seedLesson
}

type seedLesson struct {
	Position         int
	Title            string
	SkillFocus       string
	EstimatedMinutes int
	Activities       []seedActivity
}

type seedActivity struct {
	Position int
	Kind     string // vocab_multiple_choice, vocab_gap_fill, vocab_flashcard
	Config   map[string]any
	Body     map[string]any
}

type seedWordSense struct {
	Lemma        string
	POS          string
	CEFRLevel    string
	IPA          string
	Definition   string
	DefinitionVI string
	Examples     []string
}

// The vocabulary the seed data is written in. They are constants because a
// string repeated forty times is a name waiting to be given, and because the
// config keys below are the contract the lesson runner reads.
const (
	skillVocabulary = "vocabulary"

	kindMultipleChoice = "vocab_multiple_choice"
	kindGapFill        = "vocab_gap_fill"
	kindFlashcard      = "vocab_flashcard"

	cfgOptions         = "options"
	cfgOptionID        = "id"
	cfgOptionText      = "text"
	cfgCorrectOptionID = "correct_option_id"
	cfgSentenceBefore  = "sentence_before"
	cfgSentenceAfter   = "sentence_after"
	cfgExpectedAnswer  = "expected_answer"
	cfgTargetWord      = "target_word"
	cfgIPA             = "ipa"
	cfgDefinition      = "definition"
	cfgExampleSentence = "example_sentence"
)

// acceptable is the authored list of answers a grader will accept. It exists so
// the data below reads as data rather than as a wall of []string{}.
func acceptable(values ...string) []string { return values }

// courseSeedData defines the A2-B1 English Foundations curriculum.
var courseSeedData = seedCourse{
	Slug:  "everyday-english-a2-b1",
	Title: "Everyday English: A2–B1 Foundations",
	Description: "Master core everyday English communication, essential vocabulary, " +
		"and functional expressions from A2 to B1.",
	CEFRFrom:       "A2",
	CEFRTo:         "B1",
	EstimatedHours: 24,
	Units: []seedUnit{
		{
			Position:    1,
			Title:       "Daily Life & Communication",
			Description: "Foundational vocabulary and routines for personal and social daily life.",
			Lessons: []seedLesson{
				{
					Position:         1,
					Title:            "Morning Routines & Habits",
					SkillFocus:       skillVocabulary,
					EstimatedMinutes: 15,
					Activities: []seedActivity{
						{
							Position: 1,
							Kind:     kindMultipleChoice,
							Config: map[string]any{
								bodyKeyPrompt: "What is the best word to describe something you do regularly every day without thinking?",
								cfgOptions: []map[string]string{
									{cfgOptionID: "opt_habit", cfgOptionText: "Habit"},
									{cfgOptionID: "opt_barrier", cfgOptionText: "Barrier"},
									{cfgOptionID: "opt_damage", cfgOptionText: "Damage"},
									{cfgOptionID: "opt_custom", cfgOptionText: "Custom"},
								},
								cfgCorrectOptionID: "opt_habit",
							},
							Body: map[string]any{
								bodyKeyPrompt: "What is the best word to describe something " +
									"you do regularly every day without thinking?",
								bodyKeyCorrectAnswer: "opt_habit",
								bodyKeyAcceptable:    acceptable("habit", "opt_habit"),
							},
						},
						{
							Position: 2,
							Kind:     kindGapFill,
							Config: map[string]any{
								bodyKeyPrompt:     "Fill in the missing word:",
								cfgSentenceBefore: "I try to maintain a healthy",
								cfgSentenceAfter:  "by exercising 30 minutes every morning.",
								cfgExpectedAnswer: "habit",
							},
							Body: map[string]any{
								bodyKeyPrompt:        "Fill in the missing word:",
								bodyKeyCorrectAnswer: "habit",
								bodyKeyAcceptable:    acceptable("habit", "routine"),
							},
						},
						{
							Position: 3,
							Kind:     kindFlashcard,
							Config: map[string]any{
								bodyKeyPrompt:      "Review this essential habit vocabulary:",
								cfgTargetWord:      "Habit",
								cfgIPA:             "/ˈhæb.ɪt/",
								cfgDefinition:      "A settled or regular tendency or practice, especially one that is hard to give up.",
								cfgExampleSentence: "Drinking a glass of water first thing in the morning is a great habit.",
							},
							Body: map[string]any{
								bodyKeyPrompt:        "Flashcard review for habit",
								bodyKeyCorrectAnswer: "habit",
								bodyKeyAcceptable:    acceptable("habit", "good"),
							},
						},
					},
				},
				{
					Position:         2,
					Title:            "Food, Dining & Restaurants",
					SkillFocus:       skillVocabulary,
					EstimatedMinutes: 15,
					Activities: []seedActivity{
						{
							Position: 1,
							Kind:     kindMultipleChoice,
							Config: map[string]any{
								bodyKeyPrompt: "Which word means to ask someone politely for a meal in a restaurant?",
								cfgOptions: []map[string]string{
									{cfgOptionID: "opt_order", cfgOptionText: "Order"},
									{cfgOptionID: "opt_cancel", cfgOptionText: "Cancel"},
									{cfgOptionID: "opt_borrow", cfgOptionText: "Borrow"},
									{cfgOptionID: "opt_escape", cfgOptionText: "Escape"},
								},
								cfgCorrectOptionID: "opt_order",
							},
							Body: map[string]any{
								bodyKeyPrompt:        "Which word means to ask someone politely for a meal in a restaurant?",
								bodyKeyCorrectAnswer: "opt_order",
								bodyKeyAcceptable:    acceptable("order", "opt_order"),
							},
						},
						{
							Position: 2,
							Kind:     kindGapFill,
							Config: map[string]any{
								bodyKeyPrompt:     "Complete the sentence:",
								cfgSentenceBefore: "Are you ready to",
								cfgSentenceAfter:  "your dinner now, or do you need a few more minutes?",
								cfgExpectedAnswer: "order",
							},
							Body: map[string]any{
								bodyKeyPrompt:        "Complete the sentence:",
								bodyKeyCorrectAnswer: "order",
								bodyKeyAcceptable:    acceptable("order"),
							},
						},
						{
							Position: 3,
							Kind:     kindFlashcard,
							Config: map[string]any{
								bodyKeyPrompt:      "Flashcard Review:",
								cfgTargetWord:      "Delicious",
								cfgIPA:             "/dɪˈlɪʃ.əs/",
								cfgDefinition:      "Highly pleasant to the taste.",
								cfgExampleSentence: "The pasta we had for dinner yesterday was absolutely delicious.",
							},
							Body: map[string]any{
								bodyKeyPrompt:        "Flashcard review for delicious",
								bodyKeyCorrectAnswer: "delicious",
								bodyKeyAcceptable:    acceptable("delicious", "good"),
							},
						},
					},
				},
				{
					Position:         3,
					Title:            "Navigating the City & Transport",
					SkillFocus:       skillVocabulary,
					EstimatedMinutes: 15,
					Activities: []seedActivity{
						{
							Position: 1,
							Kind:     kindMultipleChoice,
							Config: map[string]any{
								bodyKeyPrompt: "What do you call the total space or length between two places in a city?",
								cfgOptions: []map[string]string{
									{cfgOptionID: "opt_distance", cfgOptionText: "Distance"},
									{cfgOptionID: "opt_frequency", cfgOptionText: "Frequency"},
									{cfgOptionID: "opt_climate", cfgOptionText: "Climate"},
									{cfgOptionID: "opt_barrier", cfgOptionText: "Barrier"},
								},
								cfgCorrectOptionID: "opt_distance",
							},
							Body: map[string]any{
								bodyKeyPrompt:        "What do you call the total space or length between two places in a city?",
								bodyKeyCorrectAnswer: "opt_distance",
								bodyKeyAcceptable:    acceptable("distance", "opt_distance"),
							},
						},
						{
							Position: 2,
							Kind:     kindGapFill,
							Config: map[string]any{
								bodyKeyPrompt:     "Fill in the blank:",
								cfgSentenceBefore: "The walking",
								cfgSentenceAfter:  "from the hotel to the subway station is only 500 meters.",
								cfgExpectedAnswer: "distance",
							},
							Body: map[string]any{
								bodyKeyPrompt:        "Fill in the blank:",
								bodyKeyCorrectAnswer: "distance",
								bodyKeyAcceptable:    acceptable("distance"),
							},
						},
						{
							Position: 3,
							Kind:     kindFlashcard,
							Config: map[string]any{
								bodyKeyPrompt:      "Review vocabulary:",
								cfgTargetWord:      "Journey",
								cfgIPA:             "/ˈdʒɜː.ni/",
								cfgDefinition:      "An act of travelling from one place to another.",
								cfgExampleSentence: "We had a smooth train journey to the capital city.",
							},
							Body: map[string]any{
								bodyKeyPrompt:        "Flashcard review for journey",
								bodyKeyCorrectAnswer: "journey",
								bodyKeyAcceptable:    acceptable("journey", "good"),
							},
						},
					},
				},
				{
					Position:         4,
					Title:            "Shopping & Everyday Transactions",
					SkillFocus:       skillVocabulary,
					EstimatedMinutes: 15,
					Activities: []seedActivity{
						{
							Position: 1,
							Kind:     kindMultipleChoice,
							Config: map[string]any{
								bodyKeyPrompt: "Which term describes a thing bought or offered for sale more cheaply than is usual?",
								cfgOptions: []map[string]string{
									{cfgOptionID: "opt_bargain", cfgOptionText: "Bargain"},
									{cfgOptionID: "opt_expense", cfgOptionText: "Expense"},
									{cfgOptionID: "opt_balance", cfgOptionText: "Balance"},
									{cfgOptionID: "opt_damage", cfgOptionText: "Damage"},
								},
								cfgCorrectOptionID: "opt_bargain",
							},
							Body: map[string]any{
								bodyKeyPrompt:        "Which term describes a thing bought or offered for sale more cheaply than is usual?",
								bodyKeyCorrectAnswer: "opt_bargain",
								bodyKeyAcceptable:    acceptable("bargain", "opt_bargain"),
							},
						},
						{
							Position: 2,
							Kind:     kindGapFill,
							Config: map[string]any{
								bodyKeyPrompt:     "Fill in the blank:",
								cfgSentenceBefore: "At only ten dollars, this warm coat was a real",
								cfgSentenceAfter:  "during the winter clearance sale.",
								cfgExpectedAnswer: "bargain",
							},
							Body: map[string]any{
								bodyKeyPrompt:        "Fill in the blank:",
								bodyKeyCorrectAnswer: "bargain",
								bodyKeyAcceptable:    acceptable("bargain"),
							},
						},
						{
							Position: 3,
							Kind:     kindFlashcard,
							Config: map[string]any{
								bodyKeyPrompt:      "Flashcard Review:",
								cfgTargetWord:      "Afford",
								cfgIPA:             "/əˈfɔːd/",
								cfgDefinition:      "Have enough money to pay for something.",
								cfgExampleSentence: "After saving for six months, she can easily afford the new laptop.",
							},
							Body: map[string]any{
								bodyKeyPrompt:        "Flashcard review for afford",
								bodyKeyCorrectAnswer: "afford",
								bodyKeyAcceptable:    acceptable("afford", "good"),
							},
						},
					},
				},
			},
		},
		{
			Position:    2,
			Title:       "Work, Travel & Leisure",
			Description: "Vocabulary for professional settings, holiday planning, and recreational activities.",
			Lessons: []seedLesson{
				{
					Position:         1,
					Title:            "At the Workplace & Office Talk",
					SkillFocus:       skillVocabulary,
					EstimatedMinutes: 20,
					Activities: []seedActivity{
						{
							Position: 1,
							Kind:     kindMultipleChoice,
							Config: map[string]any{
								bodyKeyPrompt: "What do you call a person with whom one works in a profession or business?",
								cfgOptions: []map[string]string{
									{cfgOptionID: "opt_colleague", cfgOptionText: "Colleague"},
									{cfgOptionID: "opt_candidate", cfgOptionText: "Candidate"},
									{cfgOptionID: "opt_champion", cfgOptionText: "Champion"},
									{cfgOptionID: "opt_neighbor", cfgOptionText: "Neighbor"},
								},
								cfgCorrectOptionID: "opt_colleague",
							},
							Body: map[string]any{
								bodyKeyPrompt:        "What do you call a person with whom one works in a profession or business?",
								bodyKeyCorrectAnswer: "opt_colleague",
								bodyKeyAcceptable:    acceptable("colleague", "opt_colleague"),
							},
						},
						{
							Position: 2,
							Kind:     kindGapFill,
							Config: map[string]any{
								bodyKeyPrompt:     "Complete the sentence:",
								cfgSentenceBefore: "I asked my senior",
								cfgSentenceAfter:  "for constructive feedback on the new project proposal.",
								cfgExpectedAnswer: "colleague",
							},
							Body: map[string]any{
								bodyKeyPrompt:        "Complete the sentence:",
								bodyKeyCorrectAnswer: "colleague",
								bodyKeyAcceptable:    acceptable("colleague", "coworker"),
							},
						},
						{
							Position: 3,
							Kind:     kindFlashcard,
							Config: map[string]any{
								bodyKeyPrompt:      "Flashcard Review:",
								cfgTargetWord:      "Manage",
								cfgIPA:             "/ˈmæn.ɪdʒ/",
								cfgDefinition:      "Be in charge of or successfully deal with a challenging situation or team.",
								cfgExampleSentence: "She has to manage a team of five software engineers.",
							},
							Body: map[string]any{
								bodyKeyPrompt:        "Flashcard review for manage",
								bodyKeyCorrectAnswer: "manage",
								bodyKeyAcceptable:    acceptable("manage", "good"),
							},
						},
					},
				},
				{
					Position:         2,
					Title:            "Travel Plans & Airport Navigation",
					SkillFocus:       skillVocabulary,
					EstimatedMinutes: 20,
					Activities: []seedActivity{
						{
							Position: 1,
							Kind:     kindMultipleChoice,
							Config: map[string]any{
								bodyKeyPrompt: "Which word means to discover or travel through an unfamiliar area in order to learn about it?",
								cfgOptions: []map[string]string{
									{cfgOptionID: "opt_explore", cfgOptionText: "Explore"},
									{cfgOptionID: "opt_destroy", cfgOptionText: "Destroy"},
									{cfgOptionID: "opt_hesitate", cfgOptionText: "Hesitate"},
									{cfgOptionID: "opt_exhaust", cfgOptionText: "Exhaust"},
								},
								cfgCorrectOptionID: "opt_explore",
							},
							Body: map[string]any{
								bodyKeyPrompt: "Which word means to discover or travel through " +
									"an unfamiliar area in order to learn about it?",
								bodyKeyCorrectAnswer: "opt_explore",
								bodyKeyAcceptable:    acceptable("explore", "opt_explore"),
							},
						},
						{
							Position: 2,
							Kind:     kindGapFill,
							Config: map[string]any{
								bodyKeyPrompt:     "Fill in the blank:",
								cfgSentenceBefore: "We rented bicycles so we could freely",
								cfgSentenceAfter:  "the historical center of the old town.",
								cfgExpectedAnswer: "explore",
							},
							Body: map[string]any{
								bodyKeyPrompt:        "Fill in the blank:",
								bodyKeyCorrectAnswer: "explore",
								bodyKeyAcceptable:    acceptable("explore"),
							},
						},
						{
							Position: 3,
							Kind:     kindFlashcard,
							Config: map[string]any{
								bodyKeyPrompt:      "Flashcard Review:",
								cfgTargetWord:      "Arrival",
								cfgIPA:             "/əˈraɪ.vəl/",
								cfgDefinition:      "The action or process of arriving at a destination.",
								cfgExampleSentence: "Flight attendants greeted passengers warmly upon arrival at Tokyo airport.",
							},
							Body: map[string]any{
								bodyKeyPrompt:        "Flashcard review for arrival",
								bodyKeyCorrectAnswer: "arrival",
								bodyKeyAcceptable:    acceptable("arrival", "good"),
							},
						},
					},
				},
				{
					Position:         3,
					Title:            "Health, Fitness & Well-being",
					SkillFocus:       skillVocabulary,
					EstimatedMinutes: 20,
					Activities: []seedActivity{
						{
							Position: 1,
							Kind:     kindMultipleChoice,
							Config: map[string]any{
								bodyKeyPrompt: "Which adjective means in a good physical or mental condition?",
								cfgOptions: []map[string]string{
									{cfgOptionID: "opt_healthy", cfgOptionText: "Healthy"},
									{cfgOptionID: "opt_anxious", cfgOptionText: "Anxious"},
									{cfgOptionID: "opt_exhausted", cfgOptionText: "Exhausted"},
									{cfgOptionID: "opt_fragile", cfgOptionText: "Fragile"},
								},
								cfgCorrectOptionID: "opt_healthy",
							},
							Body: map[string]any{
								bodyKeyPrompt:        "Which adjective means in a good physical or mental condition?",
								bodyKeyCorrectAnswer: "opt_healthy",
								bodyKeyAcceptable:    acceptable("healthy", "opt_healthy"),
							},
						},
						{
							Position: 2,
							Kind:     kindGapFill,
							Config: map[string]any{
								bodyKeyPrompt:     "Fill in the blank:",
								cfgSentenceBefore: "Drinking enough water and sleeping eight hours helps you stay",
								cfgSentenceAfter:  "and energetic all day.",
								cfgExpectedAnswer: "healthy",
							},
							Body: map[string]any{
								bodyKeyPrompt:        "Fill in the blank:",
								bodyKeyCorrectAnswer: "healthy",
								bodyKeyAcceptable:    acceptable("healthy", "fit"),
							},
						},
						{
							Position: 3,
							Kind:     kindFlashcard,
							Config: map[string]any{
								bodyKeyPrompt:      "Flashcard Review:",
								cfgTargetWord:      "Breathe",
								cfgIPA:             "/briːð/",
								cfgDefinition:      "Take air into the lungs and expel it.",
								cfgExampleSentence: "Remember to breathe deeply and stay calm before giving a presentation.",
							},
							Body: map[string]any{
								bodyKeyPrompt:        "Flashcard review for breathe",
								bodyKeyCorrectAnswer: "breathe",
								bodyKeyAcceptable:    acceptable("breathe", "good"),
							},
						},
					},
				},
				{
					Position:         4,
					Title:            "Hobbies, Weekend & Social Life",
					SkillFocus:       skillVocabulary,
					EstimatedMinutes: 20,
					Activities: []seedActivity{
						{
							Position: 1,
							Kind:     kindMultipleChoice,
							Config: map[string]any{
								bodyKeyPrompt: "Which word describes having or showing imagination and original ideas?",
								cfgOptions: []map[string]string{
									{cfgOptionID: "opt_creative", cfgOptionText: "Creative"},
									{cfgOptionID: "opt_curious", cfgOptionText: "Curious"},
									{cfgOptionID: "opt_formal", cfgOptionText: "Formal"},
									{cfgOptionID: "opt_elderly", cfgOptionText: "Elderly"},
								},
								cfgCorrectOptionID: "opt_creative",
							},
							Body: map[string]any{
								bodyKeyPrompt:        "Which word describes having or showing imagination and original ideas?",
								bodyKeyCorrectAnswer: "opt_creative",
								bodyKeyAcceptable:    acceptable("creative", "opt_creative"),
							},
						},
						{
							Position: 2,
							Kind:     kindGapFill,
							Config: map[string]any{
								bodyKeyPrompt:     "Fill in the blank:",
								cfgSentenceBefore: "Photography and painting are wonderful",
								cfgSentenceAfter:  "hobbies that allow people to express themselves.",
								cfgExpectedAnswer: "creative",
							},
							Body: map[string]any{
								bodyKeyPrompt:        "Fill in the blank:",
								bodyKeyCorrectAnswer: "creative",
								bodyKeyAcceptable:    acceptable("creative"),
							},
						},
						{
							Position: 3,
							Kind:     kindFlashcard,
							Config: map[string]any{
								bodyKeyPrompt:      "Flashcard Review:",
								cfgTargetWord:      "Leisure",
								cfgIPA:             "/ˈleʒ.ər/",
								cfgDefinition:      "Time when one is not working or occupied; free time.",
								cfgExampleSentence: "He enjoys reading science fiction novels in his leisure time.",
							},
							Body: map[string]any{
								bodyKeyPrompt:        "Flashcard review for leisure",
								bodyKeyCorrectAnswer: "leisure",
								bodyKeyAcceptable:    acceptable("leisure", "good"),
							},
						},
					},
				},
			},
		},
	},
}

// wordSenseSeedData contains 200 curated A2-B1 word senses.
var wordSenseSeedData = []seedWordSense{
	{
		Lemma:        "achieve",
		POS:          "verb",
		CEFRLevel:    "B1",
		IPA:          "/əˈtʃiːv/",
		Definition:   "Successfully bring about or reach by effort, skill, or courage.",
		DefinitionVI: "Đạt được",
		Examples:     []string{"She worked hard to achieve her lifelong dream."},
	},
	{
		Lemma:        "admire",
		POS:          "verb",
		CEFRLevel:    "A2",
		IPA:          "/ədˈmaɪər/",
		Definition:   "Regard an object or person with respect or warm approval.",
		DefinitionVI: "Ngưỡng mộ",
		Examples:     []string{"I deeply admire his dedication to helping others."},
	},
	{
		Lemma:        "afford",
		POS:          "verb",
		CEFRLevel:    "A2",
		IPA:          "/əˈfɔːd/",
		Definition:   "Have enough money to pay for something.",
		DefinitionVI: "Đủ khả năng chi trả",
		Examples:     []string{"Can we afford to go on holiday this summer?"},
	},
	{
		Lemma:        "ancient",
		POS:          "adjective",
		CEFRLevel:    "B1",
		IPA:          "/ˈeɪn.ʃənt/",
		Definition:   "Belonging to the very distant past and no longer in existence.",
		DefinitionVI: "Cổ xưa",
		Examples:     []string{"We visited the ancient ruins in Rome."},
	},
	{
		Lemma:        "anxious",
		POS:          "adjective",
		CEFRLevel:    "B1",
		IPA:          "/ˈæŋk.ʃəs/",
		Definition:   "Feeling or showing worry, nervousness, or unease.",
		DefinitionVI: "Lo lắng",
		Examples:     []string{"He felt anxious about the upcoming job interview."},
	},
	{
		Lemma:        "apology",
		POS:          "noun",
		CEFRLevel:    "A2",
		IPA:          "/əˈpɒl.ə.dʒi/",
		Definition:   "A regretful acknowledgment of an offence or failure.",
		DefinitionVI: "Lời xin lỗi",
		Examples:     []string{"Please accept my sincere apology for the delay."},
	},
	{
		Lemma:        "appoint",
		POS:          "verb",
		CEFRLevel:    "B1",
		IPA:          "/əˈpɔɪnt/",
		Definition:   "Assign a job or role to someone.",
		DefinitionVI: "Bổ nhiệm",
		Examples:     []string{"They appointed a new director yesterday."},
	},
	{
		Lemma:        "approach",
		POS:          "noun",
		CEFRLevel:    "B1",
		IPA:          "/əˈprəʊtʃ/",
		Definition:   "A way of dealing with a situation or problem.",
		DefinitionVI: "Cách tiếp cận",
		Examples:     []string{"We need a fresh approach to solve this issue."},
	},
	{
		Lemma:        "arrange",
		POS:          "verb",
		CEFRLevel:    "A2",
		IPA:          "/əˈreɪndʒ/",
		Definition:   "Put things in a neat, attractive, or required order.",
		DefinitionVI: "Sắp xếp",
		Examples:     []string{"She arranged the books alphabetically on the shelf."},
	},
	{
		Lemma:        "attempt",
		POS:          "verb",
		CEFRLevel:    "B1",
		IPA:          "/əˈtempt/",
		Definition:   "Make an effort to achieve or complete something.",
		DefinitionVI: "Cố gắng, thử",
		Examples:     []string{"He will attempt to run his first marathon."},
	},
	{
		Lemma:        "attitude",
		POS:          "noun",
		CEFRLevel:    "B1",
		IPA:          "/ˈæt.ɪ.tʃuːd/",
		Definition:   "A settled way of thinking or feeling about something.",
		DefinitionVI: "Thái độ",
		Examples:     []string{"A positive attitude makes any challenge easier."},
	},
	{
		Lemma:        "attract",
		POS:          "verb",
		CEFRLevel:    "A2",
		IPA:          "/əˈtrækt/",
		Definition:   "Cause to come to a place or participate by offering something.",
		DefinitionVI: "Thu hút",
		Examples:     []string{"The festival attracts thousands of visitors every year."},
	},
	{
		Lemma:        "average",
		POS:          "noun",
		CEFRLevel:    "A2",
		IPA:          "/ˈæv.ər.ɪdʒ/",
		Definition:   "A number expressing the central or typical value in a set of data.",
		DefinitionVI: "Trung bình",
		Examples:     []string{"His grades are well above the class average."},
	},
	{
		Lemma:        "balance",
		POS:          "noun",
		CEFRLevel:    "B1",
		IPA:          "/ˈbæl.əns/",
		Definition:   "An even distribution of weight or equilibrium.",
		DefinitionVI: "Sự cân bằng",
		Examples:     []string{"It is important to maintain work-life balance."},
	},
	{
		Lemma:        "bargain",
		POS:          "noun",
		CEFRLevel:    "A2",
		IPA:          "/ˈbɑː.ɡɪn/",
		Definition:   "A thing bought or offered for sale more cheaply than usual.",
		DefinitionVI: "Món hời",
		Examples:     []string{"This leather jacket was a great bargain."},
	},
	{
		Lemma:        "barrier",
		POS:          "noun",
		CEFRLevel:    "B1",
		IPA:          "/ˈbær.i.ər/",
		Definition:   "A fence or obstacle that prevents movement or access.",
		DefinitionVI: "Rào cản",
		Examples:     []string{"Language should never be a barrier to friendship."},
	},
	{
		Lemma:        "benefit",
		POS:          "noun",
		CEFRLevel:    "B1",
		IPA:          "/ˈben.ɪ.fɪt/",
		Definition:   "An advantage or profit gained from something.",
		DefinitionVI: "Lợi ích",
		Examples:     []string{"Regular exercise offers numerous health benefits."},
	},
	{
		Lemma:        "borrow",
		POS:          "verb",
		CEFRLevel:    "A2",
		IPA:          "/ˈbɒr.əʊ/",
		Definition:   "Take and use something that belongs to someone else with the intention of returning it.",
		DefinitionVI: "Vay, mượn",
		Examples:     []string{"May I borrow your umbrella for the afternoon?"},
	},
	{
		Lemma:        "breathe",
		POS:          "verb",
		CEFRLevel:    "A2",
		IPA:          "/briːð/",
		Definition:   "Take air into the lungs and expel it.",
		DefinitionVI: "Thở",
		Examples:     []string{"Take a moment to breathe deeply and relax."},
	},
	{
		Lemma:        "brilliant",
		POS:          "adjective",
		CEFRLevel:    "A2",
		IPA:          "/ˈbrɪl.jənt/",
		Definition:   "Exceptionally clever, talented, or bright.",
		DefinitionVI: "Xuất sắc",
		Examples:     []string{"That was a brilliant solution to the puzzle."},
	},
	{
		Lemma:        "candidate",
		POS:          "noun",
		CEFRLevel:    "B1",
		IPA:          "/ˈkæn.dɪ.dət/",
		Definition:   "A person who applies for a job or is nominated for election.",
		DefinitionVI: "Ứng viên",
		Examples:     []string{"She is the strongest candidate for the position."},
	},
	{
		Lemma:        "capture",
		POS:          "verb",
		CEFRLevel:    "B1",
		IPA:          "/ˈkæp.tʃər/",
		Definition:   "Take into one's possession or control by force.",
		DefinitionVI: "Bắt giữ, ghi lại",
		Examples:     []string{"The photographer captured the sunset beautifully."},
	},
	{
		Lemma:        "category",
		POS:          "noun",
		CEFRLevel:    "B1",
		IPA:          "/ˈkæt.ə.ɡri/",
		Definition:   "A class or division of people or things regarded as having shared characteristics.",
		DefinitionVI: "Danh mục",
		Examples:     []string{"The books are divided into five distinct categories."},
	},
	{
		Lemma:        "certain",
		POS:          "adjective",
		CEFRLevel:    "A2",
		IPA:          "/ˈsɜː.tən/",
		Definition:   "Known for sure; established beyond doubt.",
		DefinitionVI: "Chắc chắn",
		Examples:     []string{"Are you certain that the meeting starts at nine?"},
	},
	{
		Lemma:        "challenge",
		POS:          "noun",
		CEFRLevel:    "B1",
		IPA:          "/ˈtʃæl.ɪndʒ/",
		Definition:   "A call to take part in a contest or demanding task.",
		DefinitionVI: "Thử thách",
		Examples:     []string{"Learning a new language is a rewarding challenge."},
	},
	{
		Lemma:        "champion",
		POS:          "noun",
		CEFRLevel:    "A2",
		IPA:          "/ˈtʃæm.pi.ən/",
		Definition:   "A person who has surpassed all rivals in a sporting contest.",
		DefinitionVI: "Nhà vô địch",
		Examples:     []string{"They celebrated the championship victory together."},
	},
	{
		Lemma:        "character",
		POS:          "noun",
		CEFRLevel:    "A2",
		IPA:          "/ˈkær.ək.tər/",
		Definition:   "The mental and moral qualities distinctive to an individual.",
		DefinitionVI: "Tính cách",
		Examples:     []string{"He is a man of honest character."},
	},
	{
		Lemma:        "climate",
		POS:          "noun",
		CEFRLevel:    "A2",
		IPA:          "/ˈklaɪ.mət/",
		Definition:   "The weather conditions prevailing in an area in general.",
		DefinitionVI: "Khí hậu",
		Examples:     []string{"The island has a warm and sunny climate."},
	},
	{
		Lemma:        "colleague",
		POS:          "noun",
		CEFRLevel:    "A2",
		IPA:          "/ˈkɒl.iːɡ/",
		Definition:   "A person with whom one works in a profession or business.",
		DefinitionVI: "Đồng nghiệp",
		Examples:     []string{"I had lunch with my colleagues at work."},
	},
	{
		Lemma:        "combine",
		POS:          "verb",
		CEFRLevel:    "B1",
		IPA:          "/kəmˈbaɪn/",
		Definition:   "Join or merge to form a single unit or substance.",
		DefinitionVI: "Kết hợp",
		Examples:     []string{"Combine all the ingredients in a large bowl."},
	},
	{
		Lemma:        "comfort",
		POS:          "noun",
		CEFRLevel:    "A2",
		IPA:          "/ˈkʌm.fət/",
		Definition:   "A state of physical ease and freedom from pain.",
		DefinitionVI: "Sự thoải mái",
		Examples:     []string{"These new running shoes provide great comfort."},
	},
	{
		Lemma:        "command",
		POS:          "noun",
		CEFRLevel:    "B1",
		IPA:          "/kəˈmɑːnd/",
		Definition:   "An authoritative order.",
		DefinitionVI: "Mệnh lệnh, chỉ huy",
		Examples:     []string{"He has excellent command of the English language."},
	},
	{
		Lemma:        "compare",
		POS:          "verb",
		CEFRLevel:    "A2",
		IPA:          "/kəmˈpeər/",
		Definition:   "Estimate, measure, or note the similarity or dissimilarity between.",
		DefinitionVI: "So sánh",
		Examples:     []string{"Let's compare the prices before making a decision."},
	},
	{
		Lemma:        "complain",
		POS:          "verb",
		CEFRLevel:    "A2",
		IPA:          "/kəmˈpleɪn/",
		Definition:   "Express dissatisfaction or annoyance about something.",
		DefinitionVI: "Phàn nàn",
		Examples:     []string{"Customers rarely complain about our service."},
	},
	{
		Lemma:        "condition",
		POS:          "noun",
		CEFRLevel:    "B1",
		IPA:          "/kənˈdɪʃ.ən/",
		Definition:   "The state of something with regard to its appearance, quality, or working order.",
		DefinitionVI: "Điều kiện, tình trạng",
		Examples:     []string{"The vintage car is in excellent condition."},
	},
	{
		Lemma:        "connect",
		POS:          "verb",
		CEFRLevel:    "A2",
		IPA:          "/kəˈnekt/",
		Definition:   "Bring together or into contact so that a link is established.",
		DefinitionVI: "Kết nối",
		Examples:     []string{"This bridge connects the two sides of the river."},
	},
	{
		Lemma:        "consider",
		POS:          "verb",
		CEFRLevel:    "B1",
		IPA:          "/kənˈsɪd.ər/",
		Definition:   "Think carefully about something, typically before making a decision.",
		DefinitionVI: "Cân nhắc",
		Examples:     []string{"Please consider all available options carefully."},
	},
	{
		Lemma:        "contact",
		POS:          "noun",
		CEFRLevel:    "A2",
		IPA:          "/ˈkɒn.tækt/",
		Definition:   "The state or condition of physical touching or communicating.",
		DefinitionVI: "Liên hệ",
		Examples:     []string{"Keep in close contact with your team members."},
	},
	{
		Lemma:        "contain",
		POS:          "verb",
		CEFRLevel:    "A2",
		IPA:          "/kənˈteɪn/",
		Definition:   "Have or hold someone or something within.",
		DefinitionVI: "Chứa đựng",
		Examples:     []string{"This box contains fresh tropical fruit."},
	},
	{
		Lemma:        "continue",
		POS:          "verb",
		CEFRLevel:    "A2",
		IPA:          "/kənˈtɪn.juː/",
		Definition:   "Persist in an activity or process.",
		DefinitionVI: "Tiếp tục",
		Examples:     []string{"The rain will continue throughout the night."},
	},
	{
		Lemma:        "convince",
		POS:          "verb",
		CEFRLevel:    "B1",
		IPA:          "/kənˈvɪns/",
		Definition:   "Cause someone to believe firmly in the truth of something.",
		DefinitionVI: "Thuyết phục",
		Examples:     []string{"I managed to convince him to join our study group."},
	},
	{
		Lemma:        "creative",
		POS:          "adjective",
		CEFRLevel:    "A2",
		IPA:          "/kriˈeɪ.tɪv/",
		Definition:   "Relating to or involving the imagination or original ideas.",
		DefinitionVI: "Sáng tạo",
		Examples:     []string{"She found a creative solution to the design problem."},
	},
	{
		Lemma:        "curious",
		POS:          "adjective",
		CEFRLevel:    "A2",
		IPA:          "/ˈkjʊə.ri.əs/",
		Definition:   "Eager to know or learn something.",
		DefinitionVI: "Tò mò",
		Examples:     []string{"Children are naturally curious about the world."},
	},
	{
		Lemma:        "custom",
		POS:          "noun",
		CEFRLevel:    "B1",
		IPA:          "/ˈkʌs.təm/",
		Definition:   "A traditional and widely accepted way of behaving or doing something.",
		DefinitionVI: "Phong tục",
		Examples:     []string{"It is a local custom to remove shoes before entering."},
	},
	{
		Lemma:        "damage",
		POS:          "noun",
		CEFRLevel:    "A2",
		IPA:          "/ˈdæm.ɪdʒ/",
		Definition:   "Physical harm caused to something in such a way as to impair its value.",
		DefinitionVI: "Sự hư hại",
		Examples:     []string{"The storm caused minor damage to the roof."},
	},
	{
		Lemma:        "declare",
		POS:          "verb",
		CEFRLevel:    "B1",
		IPA:          "/dɪˈkleər/",
		Definition:   "Say something in a solemn and emphatic manner.",
		DefinitionVI: "Tuyên bố",
		Examples:     []string{"They declared the opening of the exhibition."},
	},
	{
		Lemma:        "deliver",
		POS:          "verb",
		CEFRLevel:    "A2",
		IPA:          "/dɪˈlɪv.ər/",
		Definition:   "Bring and hand over a letter, parcel, or goods to the proper addressee.",
		DefinitionVI: "Giao hàng",
		Examples:     []string{"The courier delivered the package this morning."},
	},
	{
		Lemma:        "depend",
		POS:          "verb",
		CEFRLevel:    "A2",
		IPA:          "/dɪˈpend/",
		Definition:   "Be controlled or determined by.",
		DefinitionVI: "Phụ thuộc",
		Examples:     []string{"Our weekend plans depend on the weather."},
	},
	{
		Lemma:        "describe",
		POS:          "verb",
		CEFRLevel:    "A2",
		IPA:          "/dɪˈskraɪb/",
		Definition:   "Give a detailed account in words of someone or something.",
		DefinitionVI: "Miêu tả",
		Examples:     []string{"Can you describe what the suspect looked like?"},
	},
	{
		Lemma:        "design",
		POS:          "verb",
		CEFRLevel:    "A2",
		IPA:          "/dɪˈzaɪn/",
		Definition:   "Decide upon the look and functioning of a building, garment, or other object.",
		DefinitionVI: "Thiết kế",
		Examples:     []string{"She designs modern mobile applications."},
	},
	{
		Lemma:        "destroy",
		POS:          "verb",
		CEFRLevel:    "A2",
		IPA:          "/dɪˈstrɔɪ/",
		Definition:   "End the existence of something by damaging or attacking it.",
		DefinitionVI: "Phá hủy",
		Examples:     []string{"Fire destroyed the old wooden warehouse."},
	},
	{
		Lemma:        "develop",
		POS:          "verb",
		CEFRLevel:    "B1",
		IPA:          "/dɪˈvel.əp/",
		Definition:   "Grow or cause to grow and become more mature, advanced, or elaborate.",
		DefinitionVI: "Phát triển",
		Examples:     []string{"They are developing a new learning platform."},
	},
	{
		Lemma:        "disagree",
		POS:          "verb",
		CEFRLevel:    "A2",
		IPA:          "/ˌdɪs.əˈɡriː/",
		Definition:   "Have or express a different opinion.",
		DefinitionVI: "Không đồng ý",
		Examples:     []string{"I respectfully disagree with your conclusion."},
	},
	{
		Lemma:        "discover",
		POS:          "verb",
		CEFRLevel:    "A2",
		IPA:          "/dɪˈskʌv.ər/",
		Definition:   "Find unexpectedly or in the course of a search.",
		DefinitionVI: "Khám phá",
		Examples:     []string{"Scientists discovered a new species of frog."},
	},
	{
		Lemma:        "discuss",
		POS:          "verb",
		CEFRLevel:    "A2",
		IPA:          "/dɪˈskʌs/",
		Definition:   "Talk about something with another person or group of people.",
		DefinitionVI: "Thảo luận",
		Examples:     []string{"We need to discuss the project timeline."},
	},
	{
		Lemma:        "display",
		POS:          "verb",
		CEFRLevel:    "B1",
		IPA:          "/dɪˈspleɪ/",
		Definition:   "Put something in a prominent place in order that it may readily be seen.",
		DefinitionVI: "Trưng bày",
		Examples:     []string{"The gallery displays contemporary paintings."},
	},
	{
		Lemma:        "distance",
		POS:          "noun",
		CEFRLevel:    "A2",
		IPA:          "/ˈdɪs.təns/",
		Definition:   "An amount of space between two things or people.",
		DefinitionVI: "Khoảng cách",
		Examples:     []string{"The distance between the two cities is 100 kilometers."},
	},
	{
		Lemma:        "divide",
		POS:          "verb",
		CEFRLevel:    "A2",
		IPA:          "/dɪˈvaɪd/",
		Definition:   "Separate or be separated into parts.",
		DefinitionVI: "Chia",
		Examples:     []string{"Divide the cake into eight equal slices."},
	},
	{
		Lemma:        "doubt",
		POS:          "noun",
		CEFRLevel:    "B1",
		IPA:          "/daʊt/",
		Definition:   "A feeling of uncertainty or lack of conviction.",
		DefinitionVI: "Sự nghi ngờ",
		Examples:     []string{"I have no doubt that she will succeed."},
	},
	{
		Lemma:        "dramatic",
		POS:          "adjective",
		CEFRLevel:    "B1",
		IPA:          "/drəˈmæt.ɪk/",
		Definition:   "Sudden and striking.",
		DefinitionVI: "Ấn tượng, kịch tính",
		Examples:     []string{"There was a dramatic improvement in sales."},
	},
	{
		Lemma:        "eager",
		POS:          "adjective",
		CEFRLevel:    "B1",
		IPA:          "/ˈiː.ɡər/",
		Definition:   "Strongly wanting to do or have something.",
		DefinitionVI: "Háo hức",
		Examples:     []string{"He was eager to start his new job."},
	},
	{
		Lemma:        "economic",
		POS:          "adjective",
		CEFRLevel:    "B1",
		IPA:          "/ˌiː.kəˈnɒm.ɪk/",
		Definition:   "Relating to economics or the economy.",
		DefinitionVI: "Kinh tế",
		Examples:     []string{"The country is experiencing rapid economic growth."},
	},
	{
		Lemma:        "educate",
		POS:          "verb",
		CEFRLevel:    "A2",
		IPA:          "/ˈedʒ.u.keɪt/",
		Definition:   "Give intellectual, moral, and social instruction to someone.",
		DefinitionVI: "Giáo dục",
		Examples:     []string{"Schools aim to educate future generations."},
	},
	{
		Lemma:        "effective",
		POS:          "adjective",
		CEFRLevel:    "B1",
		IPA:          "/ɪˈfek.tɪv/",
		Definition:   "Successful in producing a desired or intended result.",
		DefinitionVI: "Hiệu quả",
		Examples:     []string{"This is an effective strategy for learning vocabulary."},
	},
	{
		Lemma:        "efficient",
		POS:          "adjective",
		CEFRLevel:    "B1",
		IPA:          "/ɪˈfɪʃ.ənt/",
		Definition:   "Achieving maximum productivity with minimum wasted effort or expense.",
		DefinitionVI: "Năng suất, hiệu quả",
		Examples:     []string{"Modern engines are much more fuel efficient."},
	},
	{
		Lemma:        "elderly",
		POS:          "adjective",
		CEFRLevel:    "A2",
		IPA:          "/ˈel.dəl.i/",
		Definition:   "Of a person, old or aging.",
		DefinitionVI: "Cao tuổi",
		Examples:     []string{"We should always respect elderly people."},
	},
	{
		Lemma:        "element",
		POS:          "noun",
		CEFRLevel:    "B1",
		IPA:          "/ˈel.ɪ.mənt/",
		Definition:   "An essential or characteristic part of something abstract.",
		DefinitionVI: "Yếu tố",
		Examples:     []string{"Trust is a crucial element in any relationship."},
	},
	{
		Lemma:        "emerge",
		POS:          "verb",
		CEFRLevel:    "B1",
		IPA:          "/ɪˈmɜːdʒ/",
		Definition:   "Move out of or away from something and become visible.",
		DefinitionVI: "Nổi lên, xuất hiện",
		Examples:     []string{"New opportunities emerge during times of change."},
	},
	{
		Lemma:        "emotion",
		POS:          "noun",
		CEFRLevel:    "A2",
		IPA:          "/ɪˈməʊ.ʃən/",
		Definition:   "A strong feeling deriving from one's circumstances or mood.",
		DefinitionVI: "Cảm xúc",
		Examples:     []string{"Music can evoke powerful emotions."},
	},
	{
		Lemma:        "encourage",
		POS:          "verb",
		CEFRLevel:    "B1",
		IPA:          "/ɪnˈkʌr.ɪdʒ/",
		Definition:   "Give support, confidence, or hope to someone.",
		DefinitionVI: "Khuyến khích, động viên",
		Examples:     []string{"Her parents encouraged her to study abroad."},
	},
	{
		Lemma:        "energy",
		POS:          "noun",
		CEFRLevel:    "A2",
		IPA:          "/ˈen.ə.dʒi/",
		Definition:   "The strength and vitality required for sustained activity.",
		DefinitionVI: "Năng lượng",
		Examples:     []string{"Kids have an incredible amount of energy."},
	},
	{
		Lemma:        "engage",
		POS:          "verb",
		CEFRLevel:    "B1",
		IPA:          "/ɪnˈɡeɪdʒ/",
		Definition:   "Occupy, attract, or involve someone's interest or attention.",
		DefinitionVI: "Thu hút, tham gia",
		Examples:     []string{"The teacher knows how to engage students in lessons."},
	},
	{
		Lemma:        "enhance",
		POS:          "verb",
		CEFRLevel:    "B1",
		IPA:          "/ɪnˈhɑːns/",
		Definition:   "Intensify, increase, or further improve the quality of.",
		DefinitionVI: "Nâng cao",
		Examples:     []string{"Good lighting enhances the atmosphere of the room."},
	},
	{
		Lemma:        "enormous",
		POS:          "adjective",
		CEFRLevel:    "A2",
		IPA:          "/ɪˈnɔː.məs/",
		Definition:   "Very large in size, quantity, or extent.",
		DefinitionVI: "To lớn, khổng lồ",
		Examples:     []string{"They spent an enormous amount of money on renovations."},
	},
	{
		Lemma:        "ensure",
		POS:          "verb",
		CEFRLevel:    "B1",
		IPA:          "/ɪnˈʃɔːr/",
		Definition:   "Make certain that something will occur or be the case.",
		DefinitionVI: "Đảm bảo",
		Examples:     []string{"Please ensure that all doors are locked before leaving."},
	},
	{
		Lemma:        "entirely",
		POS:          "adverb",
		CEFRLevel:    "B1",
		IPA:          "/ɪnˈtaɪə.li/",
		Definition:   "Completely; solely.",
		DefinitionVI: "Hoàn toàn",
		Examples:     []string{"I entirely agree with your suggestion."},
	},
	{
		Lemma:        "environment",
		POS:          "noun",
		CEFRLevel:    "A2",
		IPA:          "/ɪnˈvaɪ.rən.mənt/",
		Definition:   "The surroundings or conditions in which a person lives.",
		DefinitionVI: "Môi trường",
		Examples:     []string{"We must protect the natural environment."},
	},
	{
		Lemma:        "escape",
		POS:          "verb",
		CEFRLevel:    "A2",
		IPA:          "/ɪˈskeɪp/",
		Definition:   "Break free from confinement or control.",
		DefinitionVI: "Trốn thoát",
		Examples:     []string{"The birds escaped from the cage."},
	},
	{
		Lemma:        "essential",
		POS:          "adjective",
		CEFRLevel:    "B1",
		IPA:          "/ɪˈsen.ʃəl/",
		Definition:   "Absolutely necessary; extremely important.",
		DefinitionVI: "Thiết yếu",
		Examples:     []string{"Water is essential for all living things."},
	},
	{
		Lemma:        "establish",
		POS:          "verb",
		CEFRLevel:    "B1",
		IPA:          "/ɪˈstæb.lɪʃ/",
		Definition:   "Set up an organization, system, or set of rules on a firm basis.",
		DefinitionVI: "Thiết lập",
		Examples:     []string{"The company was established in 2010."},
	},
	{
		Lemma:        "evaluate",
		POS:          "verb",
		CEFRLevel:    "B1",
		IPA:          "/ɪˈvæl.ju.eɪt/",
		Definition:   "Form an idea of the amount, number, or value of; assess.",
		DefinitionVI: "Đánh giá",
		Examples:     []string{"Teachers evaluate student progress through regular tests."},
	},
	{
		Lemma:        "eventual",
		POS:          "adjective",
		CEFRLevel:    "B1",
		IPA:          "/ɪˈven.tʃu.əl/",
		Definition:   "Occurring or existing at the end of or as a result of a process.",
		DefinitionVI: "Cuối cùng",
		Examples:     []string{"Their patience led to their eventual success."},
	},
	{
		Lemma:        "evidence",
		POS:          "noun",
		CEFRLevel:    "B1",
		IPA:          "/ˈev.ɪ.dəns/",
		Definition:   "The available body of facts indicating whether a belief is true.",
		DefinitionVI: "Bằng chứng",
		Examples:     []string{"There is clear evidence supporting the theory."},
	},
	{
		Lemma:        "exactly",
		POS:          "adverb",
		CEFRLevel:    "A2",
		IPA:          "/ɪɡˈzækt.li/",
		Definition:   "Without discrepancy; used to emphasize accuracy.",
		DefinitionVI: "Chính xác",
		Examples:     []string{"That is exactly what I was trying to say."},
	},
	{
		Lemma:        "examine",
		POS:          "verb",
		CEFRLevel:    "A2",
		IPA:          "/ɪɡˈzæm.ɪn/",
		Definition:   "Inspect someone or something in detail to determine their condition.",
		DefinitionVI: "Kiểm tra",
		Examples:     []string{"The doctor examined the patient carefully."},
	},
	{
		Lemma:        "excellent",
		POS:          "adjective",
		CEFRLevel:    "A2",
		IPA:          "/ˈek.səl.ənt/",
		Definition:   "Extremely good; outstanding.",
		DefinitionVI: "Xuất sắc",
		Examples:     []string{"She gave an excellent presentation this morning."},
	},
	{
		Lemma:        "exchange",
		POS:          "verb",
		CEFRLevel:    "A2",
		IPA:          "/ɪksˈtʃeɪndʒ/",
		Definition:   "Give something and receive something of the same kind in return.",
		DefinitionVI: "Trao đổi",
		Examples:     []string{"They exchanged business cards at the conference."},
	},
	{
		Lemma:        "excite",
		POS:          "verb",
		CEFRLevel:    "A2",
		IPA:          "/ɪkˈsaɪt/",
		Definition:   "Cause strong feelings of enthusiasm and eagerness in.",
		DefinitionVI: "Gây hứng thú",
		Examples:     []string{"The upcoming concert excites music fans everywhere."},
	},
	{
		Lemma:        "excuse",
		POS:          "noun",
		CEFRLevel:    "A2",
		IPA:          "/ɪkˈskjuːs/",
		Definition:   "A reason put forward to defend or justify a fault.",
		DefinitionVI: "Lời biện hộ",
		Examples:     []string{"He always has an excuse for arriving late."},
	},
	{
		Lemma:        "exercise",
		POS:          "noun",
		CEFRLevel:    "A2",
		IPA:          "/ˈek.sə.saɪz/",
		Definition:   "Activity requiring physical effort, carried out to sustain health.",
		DefinitionVI: "Tập thể dục, bài tập",
		Examples:     []string{"Daily exercise helps keep the body and mind fit."},
	},
	{
		Lemma:        "exhaust",
		POS:          "verb",
		CEFRLevel:    "B1",
		IPA:          "/ɪɡˈzɔːst/",
		Definition:   "Drain someone of their physical or mental resources completely.",
		DefinitionVI: "Làm kiệt sức",
		Examples:     []string{"The long mountain hike exhausted everyone."},
	},
	{
		Lemma:        "expand",
		POS:          "verb",
		CEFRLevel:    "B1",
		IPA:          "/ɪkˈspænd/",
		Definition:   "Become or make larger or more extensive.",
		DefinitionVI: "Mở rộng",
		Examples:     []string{"The business plans to expand into new markets."},
	},
	{
		Lemma:        "expect",
		POS:          "verb",
		CEFRLevel:    "A2",
		IPA:          "/ɪkˈspekt/",
		Definition:   "Regard something as likely to happen.",
		DefinitionVI: "Kỳ vọng, mong đợi",
		Examples:     []string{"We expect the flight to land on schedule."},
	},
	{
		Lemma:        "expense",
		POS:          "noun",
		CEFRLevel:    "B1",
		IPA:          "/ɪkˈspens/",
		Definition:   "The cost required for something; the money spent on something.",
		DefinitionVI: "Chi phí",
		Examples:     []string{"Travel expenses will be covered by the company."},
	},
	{
		Lemma:        "experience",
		POS:          "noun",
		CEFRLevel:    "A2",
		IPA:          "/ɪkˈspɪə.ri.əns/",
		Definition:   "Practical contact with and observation of facts or events.",
		DefinitionVI: "Kinh nghiệm",
		Examples:     []string{"She has five years of experience in marketing."},
	},
	{
		Lemma:        "expert",
		POS:          "noun",
		CEFRLevel:    "A2",
		IPA:          "/ˈek.spɜːt/",
		Definition:   "A person who has a comprehensive knowledge in a particular area.",
		DefinitionVI: "Chuyên gia",
		Examples:     []string{"He is a recognized expert in data science."},
	},
	{
		Lemma:        "explain",
		POS:          "verb",
		CEFRLevel:    "A2",
		IPA:          "/ɪkˈspleɪn/",
		Definition:   "Make an idea or situation clear to someone by describing it.",
		DefinitionVI: "Giải thích",
		Examples:     []string{"Can you explain this grammar rule again, please?"},
	},
	{
		Lemma:        "explore",
		POS:          "verb",
		CEFRLevel:    "A2",
		IPA:          "/ɪkˈsplɔːr/",
		Definition:   "Travel through an unfamiliar area in order to learn about it.",
		DefinitionVI: "Khám phá",
		Examples:     []string{"We spent the whole weekend exploring the national park."},
	},
	{
		Lemma:        "express",
		POS:          "verb",
		CEFRLevel:    "B1",
		IPA:          "/ɪkˈspres/",
		Definition:   "Convey a thought or feeling in words or by gestures and conduct.",
		DefinitionVI: "Bày tỏ",
		Examples:     []string{"She found it hard to express her gratitude."},
	},
	{
		Lemma:        "extend",
		POS:          "verb",
		CEFRLevel:    "B1",
		IPA:          "/ɪkˈstend/",
		Definition:   "Cause to cover a wider area; make larger.",
		DefinitionVI: "Kéo dài, mở rộng",
		Examples:     []string{"The deadline was extended by two weeks."},
	},
	{
		Lemma:        "extraordinary",
		POS:          "adjective",
		CEFRLevel:    "B1",
		IPA:          "/ɪkˈstrɔː.dɪn.ri/",
		Definition:   "Very unusual or remarkable.",
		DefinitionVI: "Phi thường",
		Examples:     []string{"She has an extraordinary memory for names and faces."},
	},
	{
		Lemma:        "factory",
		POS:          "noun",
		CEFRLevel:    "A2",
		IPA:          "/ˈfæk.tər.i/",
		Definition:   "A building or group of buildings where goods are manufactured.",
		DefinitionVI: "Nhà máy",
		Examples:     []string{"The factory produces car parts."},
	},
	{
		Lemma:        "failure",
		POS:          "noun",
		CEFRLevel:    "B1",
		IPA:          "/ˈfeɪ.ljər/",
		Definition:   "Lack of success.",
		DefinitionVI: "Sự thất bại",
		Examples:     []string{"Failure is often the best teacher in life."},
	},
	{
		Lemma:        "familiar",
		POS:          "adjective",
		CEFRLevel:    "A2",
		IPA:          "/fəˈmɪl.i.ər/",
		Definition:   "Well known from long or close association.",
		DefinitionVI: "Quen thuộc",
		Examples:     []string{"His voice sounded familiar to me."},
	},
	{
		Lemma:        "famous",
		POS:          "adjective",
		CEFRLevel:    "A2",
		IPA:          "/ˈfeɪ.məs/",
		Definition:   "Known about by many people.",
		DefinitionVI: "Nổi tiếng",
		Examples:     []string{"He is a world-famous pianist."},
	},
	{
		Lemma:        "fantasy",
		POS:          "noun",
		CEFRLevel:    "B1",
		IPA:          "/ˈfæn.tə.si/",
		Definition:   "The faculty or activity of imagining impossible or improbable things.",
		DefinitionVI: "Trí tưởng tượng, điều huyền bí",
		Examples:     []string{"Reading fantasy novels is her favorite pastime."},
	},
	{
		Lemma:        "fashion",
		POS:          "noun",
		CEFRLevel:    "A2",
		IPA:          "/ˈfæʃ.ən/",
		Definition:   "A popular trend, especially in styles of dress and ornament.",
		DefinitionVI: "Thời trang",
		Examples:     []string{"She has a unique sense of fashion."},
	},
	{
		Lemma:        "feature",
		POS:          "noun",
		CEFRLevel:    "B1",
		IPA:          "/ˈfiː.tʃər/",
		Definition:   "A distinctive attribute or aspect of something.",
		DefinitionVI: "Đặc điểm, tính năng",
		Examples:     []string{"The new phone has impressive battery-saving features."},
	},
	{
		Lemma:        "figure",
		POS:          "noun",
		CEFRLevel:    "B1",
		IPA:          "/ˈfɪɡ.ər/",
		Definition:   "A number, especially one which forms part of official statistics.",
		DefinitionVI: "Con số, hình tượng",
		Examples:     []string{"Sales figures exceeded our expectations."},
	},
	{
		Lemma:        "financial",
		POS:          "adjective",
		CEFRLevel:    "B1",
		IPA:          "/faɪˈnæn.ʃəl/",
		Definition:   "Relating to finance or money.",
		DefinitionVI: "Tài chính",
		Examples:     []string{"Seek professional financial advice before investing."},
	},
	{
		Lemma:        "foreign",
		POS:          "adjective",
		CEFRLevel:    "A2",
		IPA:          "/ˈfɒr.ən/",
		Definition:   "Of, from, in, or characteristic of a country or language other than one's own.",
		DefinitionVI: "Nước ngoài",
		Examples:     []string{"Learning a foreign language broadens your perspective."},
	},
	{
		Lemma:        "formal",
		POS:          "adjective",
		CEFRLevel:    "B1",
		IPA:          "/ˈfɔː.məl/",
		Definition:   "Done in accordance with convention or etiquette; suitable for official occasions.",
		DefinitionVI: "Trang trọng",
		Examples:     []string{"Please wear formal attire to the annual gala dinner."},
	},
	{
		Lemma:        "fortunate",
		POS:          "adjective",
		CEFRLevel:    "B1",
		IPA:          "/ˈfɔː.tʃən.ət/",
		Definition:   "Favored by or involving good luck; lucky.",
		DefinitionVI: "May mắn",
		Examples:     []string{"We were fortunate to find a table at the crowded bistro."},
	},
	{
		Lemma:        "freedom",
		POS:          "noun",
		CEFRLevel:    "A2",
		IPA:          "/ˈfriː.dəm/",
		Definition:   "The power or right to act, speak, or think as one wants.",
		DefinitionVI: "Sự tự do",
		Examples:     []string{"Freedom of speech is a fundamental right."},
	},
	{
		Lemma:        "frequent",
		POS:          "adjective",
		CEFRLevel:    "B1",
		IPA:          "/ˈfriː.kwənt/",
		Definition:   "Occurring or done on many occasions with short intervals.",
		DefinitionVI: "Thường xuyên",
		Examples:     []string{"He is a frequent flyer on international routes."},
	},
	{
		Lemma:        "function",
		POS:          "noun",
		CEFRLevel:    "B1",
		IPA:          "/ˈfʌŋk.ʃən/",
		Definition:   "An activity or purpose natural to or intended for a person or thing.",
		DefinitionVI: "Chức năng",
		Examples:     []string{"The main function of this software is file compression."},
	},
	{
		Lemma:        "fundamental",
		POS:          "adjective",
		CEFRLevel:    "B1",
		IPA:          "/ˌfʌn.dəˈmen.təl/",
		Definition:   "Forming a necessary base or core; of central importance.",
		DefinitionVI: "Cơ bản, cốt lõi",
		Examples:     []string{"Clear communication is fundamental to team success."},
	},
	{
		Lemma:        "future",
		POS:          "noun",
		CEFRLevel:    "A2",
		IPA:          "/ˈfjuː.tʃər/",
		Definition:   "The time or a period of time following the moment of speaking.",
		DefinitionVI: "Tương lai",
		Examples:     []string{"She has bright hopes for the future."},
	},
	{
		Lemma:        "gather",
		POS:          "verb",
		CEFRLevel:    "A2",
		IPA:          "/ˈɡæð.ər/",
		Definition:   "Come together; assemble or accumulate.",
		DefinitionVI: "Tập hợp, tụ tập",
		Examples:     []string{"The family gathered around the fireplace for stories."},
	},
	{
		Lemma:        "generate",
		POS:          "verb",
		CEFRLevel:    "B1",
		IPA:          "/ˈdʒen.ə.reɪt/",
		Definition:   "Produce or create.",
		DefinitionVI: "Tạo ra, phát điện",
		Examples:     []string{"Solar panels generate clean renewable energy."},
	},
	{
		Lemma:        "generous",
		POS:          "adjective",
		CEFRLevel:    "A2",
		IPA:          "/ˈdʒen.ər.əs/",
		Definition:   "Showing a readiness to give more of something than is strictly necessary.",
		DefinitionVI: "Hào phóng",
		Examples:     []string{"He made a generous donation to the animal shelter."},
	},
	{
		Lemma:        "genuine",
		POS:          "adjective",
		CEFRLevel:    "B1",
		IPA:          "/ˈdʒen.ju.ɪn/",
		Definition:   "Truly what something is said to be; authentic.",
		DefinitionVI: "Thật, chân thật",
		Examples:     []string{"She offered a genuine smile of gratitude."},
	},
	{
		Lemma:        "gesture",
		POS:          "noun",
		CEFRLevel:    "B1",
		IPA:          "/ˈdʒes.tʃər/",
		Definition:   "A movement of part of the body, especially a hand or the head, to express an idea.",
		DefinitionVI: "Cử chỉ",
		Examples:     []string{"Bringing flowers was a kind gesture."},
	},
	{
		Lemma:        "global",
		POS:          "adjective",
		CEFRLevel:    "A2",
		IPA:          "/ˈɡləʊ.bəl/",
		Definition:   "Relating to the whole world; worldwide.",
		DefinitionVI: "Toàn cầu",
		Examples:     []string{"Climate change is an urgent global issue."},
	},
	{
		Lemma:        "gradual",
		POS:          "adjective",
		CEFRLevel:    "B1",
		IPA:          "/ˈɡrædʒ.u.əl/",
		Definition:   "Taking place or progressing slowly by degrees.",
		DefinitionVI: "Dần dần",
		Examples:     []string{"There was a gradual decrease in temperature."},
	},
	{
		Lemma:        "grateful",
		POS:          "adjective",
		CEFRLevel:    "A2",
		IPA:          "/ˈɡreɪt.fəl/",
		Definition:   "Feeling or showing an appreciation of kindness; thankful.",
		DefinitionVI: "Biết ơn",
		Examples:     []string{"I am very grateful for your assistance."},
	},
	{
		Lemma:        "guarantee",
		POS:          "verb",
		CEFRLevel:    "B1",
		IPA:          "/ˌɡær.ənˈtiː/",
		Definition:   "Provide a formal assurance or promise, especially that certain conditions will be met.",
		DefinitionVI: "Bảo đảm",
		Examples:     []string{"We guarantee customer satisfaction on all items."},
	},
	{
		Lemma:        "guidance",
		POS:          "noun",
		CEFRLevel:    "B1",
		IPA:          "/ˈɡaɪ.dəns/",
		Definition:   "Advice or information aimed at resolving a problem or difficulty.",
		DefinitionVI: "Sự hướng dẫn",
		Examples:     []string{"New employees receive guidance from seasoned mentors."},
	},
	{
		Lemma:        "habit",
		POS:          "noun",
		CEFRLevel:    "A2",
		IPA:          "/ˈhæb.ɪt/",
		Definition:   "A settled or regular tendency or practice.",
		DefinitionVI: "Thói quen",
		Examples:     []string{"Reading before bed is a relaxing habit."},
	},
	{
		Lemma:        "handle",
		POS:          "verb",
		CEFRLevel:    "A2",
		IPA:          "/ˈhæn.dəl/",
		Definition:   "Manage, deal with, or be responsible for.",
		DefinitionVI: "Xử lý",
		Examples:     []string{"She knows how to handle difficult customer complaints."},
	},
	{
		Lemma:        "healthy",
		POS:          "adjective",
		CEFRLevel:    "A2",
		IPA:          "/ˈhel.θi/",
		Definition:   "In good health; promoting health.",
		DefinitionVI: "Khỏe mạnh",
		Examples:     []string{"Eating fresh fruits and vegetables keeps you healthy."},
	},
	{
		Lemma:        "hesitate",
		POS:          "verb",
		CEFRLevel:    "B1",
		IPA:          "/ˈhez.ɪ.teɪt/",
		Definition:   "Pause before saying or doing something through uncertainty.",
		DefinitionVI: "Ngập ngừng, do dự",
		Examples:     []string{"Do not hesitate to contact us if you need help."},
	},
	{
		Lemma:        "history",
		POS:          "noun",
		CEFRLevel:    "A2",
		IPA:          "/ˈhɪs.tər.i/",
		Definition:   "The study of past events, particularly in human affairs.",
		DefinitionVI: "Lịch sử",
		Examples:     []string{"He loves reading about ancient history."},
	},
	{
		Lemma:        "honest",
		POS:          "adjective",
		CEFRLevel:    "A2",
		IPA:          "/ˈɒn.ɪst/",
		Definition:   "Free of deceit and untruthfulness; sincere.",
		DefinitionVI: "Trung thực",
		Examples:     []string{"Always give an honest answer during the review."},
	},
	{
		Lemma:        "horizon",
		POS:          "noun",
		CEFRLevel:    "B1",
		IPA:          "/həˈraɪ.zən/",
		Definition:   "The line at which the earth's surface and the sky appear to meet.",
		DefinitionVI: "Đường chân trời",
		Examples:     []string{"The sun sank slowly below the ocean horizon."},
	},
	{
		Lemma:        "hospital",
		POS:          "noun",
		CEFRLevel:    "A2",
		IPA:          "/ˈhɒs.pɪ.təl/",
		Definition:   "An institution providing medical and surgical treatment and nursing care.",
		DefinitionVI: "Bệnh viện",
		Examples:     []string{"He was treated at the local general hospital."},
	},
	{
		Lemma:        "identity",
		POS:          "noun",
		CEFRLevel:    "B1",
		IPA:          "/aɪˈden.tə.ti/",
		Definition:   "The fact of being who or what a person or thing is.",
		DefinitionVI: "Danh tính, bản sắc",
		Examples:     []string{"Art helps people express their cultural identity."},
	},
	{
		Lemma:        "ignore",
		POS:          "verb",
		CEFRLevel:    "A2",
		IPA:          "/ɪɡˈnɔːr/",
		Definition:   "Refuse to take notice of or acknowledge; disregard intentionally.",
		DefinitionVI: "Phớt lờ",
		Examples:     []string{"You should not ignore warning signals on your dashboard."},
	},
	{
		Lemma:        "illegal",
		POS:          "adjective",
		CEFRLevel:    "B1",
		IPA:          "/ɪˈliː.ɡəl/",
		Definition:   "Contrary to or forbidden by law.",
		DefinitionVI: "Bất hợp pháp",
		Examples:     []string{"Parking in front of a fire hydrant is illegal."},
	},
	{
		Lemma:        "imagine",
		POS:          "verb",
		CEFRLevel:    "A2",
		IPA:          "/ɪˈmædʒ.ɪn/",
		Definition:   "Form a mental image or concept of.",
		DefinitionVI: "Tưởng tượng",
		Examples:     []string{"Can you imagine living on Mars?"},
	},
	{
		Lemma:        "impact",
		POS:          "noun",
		CEFRLevel:    "B1",
		IPA:          "/ˈɪm.pækt/",
		Definition:   "The marked effect or influence of something.",
		DefinitionVI: "Tác động",
		Examples:     []string{"Technology has had a huge impact on education."},
	},
	{
		Lemma:        "import",
		POS:          "verb",
		CEFRLevel:    "B1",
		IPA:          "/ɪmˈpɔːt/",
		Definition:   "Bring goods or services into a country from abroad for sale.",
		DefinitionVI: "Nhập khẩu",
		Examples:     []string{"The country imports coffee from Latin America."},
	},
	{
		Lemma:        "improve",
		POS:          "verb",
		CEFRLevel:    "A2",
		IPA:          "/ɪmˈpruːv/",
		Definition:   "Make or become better.",
		DefinitionVI: "Cải thiện",
		Examples:     []string{"Practicing speaking every day will improve your fluency."},
	},
	{
		Lemma:        "include",
		POS:          "verb",
		CEFRLevel:    "A2",
		IPA:          "/ɪnˈkluːd/",
		Definition:   "Comprise or contain as part of a whole.",
		DefinitionVI: "Bao gồm",
		Examples:     []string{"The tour price includes hotel accommodation and breakfast."},
	},
	{
		Lemma:        "increase",
		POS:          "verb",
		CEFRLevel:    "A2",
		IPA:          "/ɪnˈkriːs/",
		Definition:   "Become or make greater in size, amount, intensity, or degree.",
		DefinitionVI: "Tăng lên",
		Examples:     []string{"Demand for electric vehicles continues to increase."},
	},
	{
		Lemma:        "indicate",
		POS:          "verb",
		CEFRLevel:    "B1",
		IPA:          "/ˈɪn.dɪ.keɪt/",
		Definition:   "Point out; show.",
		DefinitionVI: "Chỉ ra",
		Examples:     []string{"A flashing red light indicates an urgent error."},
	},
	{
		Lemma:        "industry",
		POS:          "noun",
		CEFRLevel:    "B1",
		IPA:          "/ˈɪn.də.stri/",
		Definition:   "Economic activity concerned with the processing of raw materials and manufacture of goods.",
		DefinitionVI: "Ngành công nghiệp",
		Examples:     []string{"The tourism industry employs millions of people worldwide."},
	},
	{
		Lemma:        "inform",
		POS:          "verb",
		CEFRLevel:    "A2",
		IPA:          "/ɪnˈfɔːm/",
		Definition:   "Give someone facts or information; tell.",
		DefinitionVI: "Thông báo",
		Examples:     []string{"Please inform us of any dietary restrictions in advance."},
	},
	{
		Lemma:        "initial",
		POS:          "adjective",
		CEFRLevel:    "B1",
		IPA:          "/ɪˈnɪʃ.əl/",
		Definition:   "Existing or occurring at the beginning.",
		DefinitionVI: "Ban đầu",
		Examples:     []string{"Our initial reaction was one of complete surprise."},
	},
	{
		Lemma:        "innocent",
		POS:          "adjective",
		CEFRLevel:    "B1",
		IPA:          "/ˈɪn.ə.sənt/",
		Definition:   "Not guilty of a crime or offense.",
		DefinitionVI: "Vô tội, ngây thơ",
		Examples:     []string{"The judge declared that the defendant was innocent."},
	},
	{
		Lemma:        "inquire",
		POS:          "verb",
		CEFRLevel:    "B1",
		IPA:          "/ɪnˈkwaɪər/",
		Definition:   "Ask for information from someone.",
		DefinitionVI: "Hỏi thăm, yêu cầu thông tin",
		Examples:     []string{"She called the hotel to inquire about room rates."},
	},
	{
		Lemma:        "inspire",
		POS:          "verb",
		CEFRLevel:    "B1",
		IPA:          "/ɪnˈspaɪər/",
		Definition:   "Fill someone with the urge or ability to do or feel something creative.",
		DefinitionVI: "Truyền cảm hứng",
		Examples:     []string{"Her courageous story inspired millions of readers."},
	},
	{
		Lemma:        "install",
		POS:          "verb",
		CEFRLevel:    "A2",
		IPA:          "/ɪnˈstɔːl/",
		Definition:   "Place or fix equipment or software in position ready for use.",
		DefinitionVI: "Cài đặt",
		Examples:     []string{"Click here to install the latest software updates."},
	},
	{
		Lemma:        "instance",
		POS:          "noun",
		CEFRLevel:    "B1",
		IPA:          "/ˈɪn.stəns/",
		Definition:   "An example or single occurrence of something.",
		DefinitionVI: "Ví dụ, trường hợp",
		Examples:     []string{"In this particular instance, we will make an exception."},
	},
	{
		Lemma:        "intend",
		POS:          "verb",
		CEFRLevel:    "B1",
		IPA:          "/ɪnˈtend/",
		Definition:   "Have in mind as a purpose or plan.",
		DefinitionVI: "Có ý định",
		Examples:     []string{"I intend to finish the report before leaving today."},
	},
	{
		Lemma:        "intense",
		POS:          "adjective",
		CEFRLevel:    "B1",
		IPA:          "/ɪnˈtens/",
		Definition:   "Of extreme force, degree, or strength.",
		DefinitionVI: "Mãnh liệt, dữ dội",
		Examples:     []string{"Athletes underwent intense physical training."},
	},
	{
		Lemma:        "interest",
		POS:          "noun",
		CEFRLevel:    "A2",
		IPA:          "/ˈɪn.trəst/",
		Definition:   "The feeling of wanting to know or learn about something or someone.",
		DefinitionVI: "Sự quan tâm, sở thích",
		Examples:     []string{"He showed a keen interest in computer science."},
	},
	{
		Lemma:        "invent",
		POS:          "verb",
		CEFRLevel:    "A2",
		IPA:          "/ɪnˈvent/",
		Definition:   "Create or design something that has not existed before.",
		DefinitionVI: "Phát minh",
		Examples:     []string{"Alexander Graham Bell invented the telephone."},
	},
	{
		Lemma:        "invest",
		POS:          "verb",
		CEFRLevel:    "B1",
		IPA:          "/ɪnˈvest/",
		Definition:   "Expend money with the expectation of achieving a profit.",
		DefinitionVI: "Đầu tư",
		Examples:     []string{"They decided to invest in solar energy technology."},
	},
	{
		Lemma:        "invite",
		POS:          "verb",
		CEFRLevel:    "A2",
		IPA:          "/ɪnˈvaɪt/",
		Definition:   "Make a polite, formal, or friendly request to someone to go somewhere or do something.",
		DefinitionVI: "Mời",
		Examples:     []string{"We invited all our neighbors to the housewarming party."},
	},
	{
		Lemma:        "involve",
		POS:          "verb",
		CEFRLevel:    "B1",
		IPA:          "/ɪnˈvɒlv/",
		Definition:   "Include something as a necessary part or result.",
		DefinitionVI: "Liên quan, bao gồm",
		Examples:     []string{"The new role involves regular international travel."},
	},
	{
		Lemma:        "isolate",
		POS:          "verb",
		CEFRLevel:    "B1",
		IPA:          "/ˈaɪ.sə.leɪt/",
		Definition:   "Cause a person or place to be or remain alone or apart from others.",
		DefinitionVI: "Cách ly, cô lập",
		Examples:     []string{"Scientists isolated the compound for laboratory testing."},
	},
	{
		Lemma:        "issue",
		POS:          "noun",
		CEFRLevel:    "A2",
		IPA:          "/ˈɪʃ.uː/",
		Definition:   "An important topic or problem for debate or discussion.",
		DefinitionVI: "Vấn đề",
		Examples:     []string{"Pollution is a major environmental issue."},
	},
	{
		Lemma:        "journey",
		POS:          "noun",
		CEFRLevel:    "A2",
		IPA:          "/ˈdʒɜː.ni/",
		Definition:   "An act of travelling from one place to another.",
		DefinitionVI: "Hành trình",
		Examples:     []string{"Their journey across Europe took three weeks."},
	},
	{
		Lemma:        "judge",
		POS:          "verb",
		CEFRLevel:    "B1",
		IPA:          "/dʒʌdʒ/",
		Definition:   "Form an opinion or conclusion about.",
		DefinitionVI: "Phán đoán, đánh giá",
		Examples:     []string{"Do not judge a book by its cover."},
	},
	{
		Lemma:        "justice",
		POS:          "noun",
		CEFRLevel:    "B1",
		IPA:          "/ˈdʒʌs.tɪs/",
		Definition:   "Just behaviour or treatment; fairness.",
		DefinitionVI: "Công lý, sự công bằng",
		Examples:     []string{"The citizens demanded justice for the victims."},
	},
	{
		Lemma:        "justify",
		POS:          "verb",
		CEFRLevel:    "B1",
		IPA:          "/ˈdʒʌs.tɪ.faɪ/",
		Definition:   "Show or prove to be right or reasonable.",
		DefinitionVI: "Biện minh, chứng minh hợp lý",
		Examples:     []string{"You must justify your budget request with solid data."},
	},
	{
		Lemma:        "kingdom",
		POS:          "noun",
		CEFRLevel:    "A2",
		IPA:          "/ˈkɪŋ.dəm/",
		Definition:   "A country, state, or territory ruled by a king or queen.",
		DefinitionVI: "Vương quốc",
		Examples:     []string{"The United Kingdom is composed of four nations."},
	},
	{
		Lemma:        "knowledge",
		POS:          "noun",
		CEFRLevel:    "A2",
		IPA:          "/ˈnɒl.ɪdʒ/",
		Definition:   "Facts, information, and skills acquired through experience or education.",
		DefinitionVI: "Kiến thức",
		Examples:     []string{"Reading books expands your general knowledge."},
	},
	{
		Lemma:        "label",
		POS:          "noun",
		CEFRLevel:    "A2",
		IPA:          "/ˈleɪ.bəl/",
		Definition:   "A small piece of paper, fabric, or plastic attached to an object giving information about it.",
		DefinitionVI: "Nhãn dán",
		Examples:     []string{"Read the care label before washing the sweater."},
	},
	{
		Lemma:        "launch",
		POS:          "verb",
		CEFRLevel:    "B1",
		IPA:          "/lɔːntʃ/",
		Definition:   "Start or set in motion an activity or enterprise.",
		DefinitionVI: "Khởi động, ra mắt",
		Examples:     []string{"The startup will launch its new product next month."},
	},
	{
		Lemma:        "leading",
		POS:          "adjective",
		CEFRLevel:    "B1",
		IPA:          "/ˈliː.dɪŋ/",
		Definition:   "Most important; principal; in first place.",
		DefinitionVI: "Dẫn đầu",
		Examples:     []string{"She is a leading expert in pediatric medicine."},
	},
	{
		Lemma:        "league",
		POS:          "noun",
		CEFRLevel:    "B1",
		IPA:          "/liːɡ/",
		Definition:   "A collection of people, countries, or groups that combine for a particular purpose.",
		DefinitionVI: "Liên minh, giải đấu",
		Examples:     []string{"Our football team joined the regional premier league."},
	},
	{
		Lemma:        "legal",
		POS:          "adjective",
		CEFRLevel:    "B1",
		IPA:          "/ˈliː.ɡəl/",
		Definition:   "Relating to or permitted by law.",
		DefinitionVI: "Hợp pháp, pháp lý",
		Examples:     []string{"Always seek legal counsel when signing a major contract."},
	},
	{
		Lemma:        "leisure",
		POS:          "noun",
		CEFRLevel:    "A2",
		IPA:          "/ˈleʒ.ər/",
		Definition:   "Time when one is not working or occupied; free time.",
		DefinitionVI: "Thời gian rảnh rỗi",
		Examples:     []string{"What hobbies do you pursue in your leisure time?"},
	},
	{
		Lemma:        "maintain",
		POS:          "verb",
		CEFRLevel:    "B1",
		IPA:          "/meɪnˈteɪn/",
		Definition:   "Cause or enable a condition or state of affairs to continue.",
		DefinitionVI: "Duy trì",
		Examples:     []string{"Maintain a calm composure during public speaking."},
	},
	{
		Lemma:        "manage",
		POS:          "verb",
		CEFRLevel:    "A2",
		IPA:          "/ˈmæn.ɪdʒ/",
		Definition:   "Be in charge of a business, team, or situation.",
		DefinitionVI: "Quản lý",
		Examples:     []string{"He manages a bustling downtown café."},
	},
	{
		Lemma:        "measure",
		POS:          "verb",
		CEFRLevel:    "A2",
		IPA:          "/ˈmeʒ.ər/",
		Definition:   "Ascertain the size, amount, or degree of something by using an instrument.",
		DefinitionVI: "Đo lường",
		Examples:     []string{"Measure twice, cut once."},
	},
	{
		Lemma:        "memory",
		POS:          "noun",
		CEFRLevel:    "A2",
		IPA:          "/ˈmem.ər.i/",
		Definition:   "The faculty by which the mind stores and remembers information.",
		DefinitionVI: "Trí nhớ, kỷ niệm",
		Examples:     []string{"She has fond memories of her childhood summers."},
	},
	{
		Lemma:        "mention",
		POS:          "verb",
		CEFRLevel:    "A2",
		IPA:          "/ˈmen.ʃən/",
		Definition:   "Refer to something briefly and without going into detail.",
		DefinitionVI: "Đề cập",
		Examples:     []string{"Did he mention when he would return?"},
	},
	{
		Lemma:        "method",
		POS:          "noun",
		CEFRLevel:    "A2",
		IPA:          "/ˈmeθ.əd/",
		Definition:   "A particular procedure for accomplishing or approaching something.",
		DefinitionVI: "Phương pháp",
		Examples:     []string{"This method of teaching has proven very effective."},
	},
	{
		Lemma:        "military",
		POS:          "noun",
		CEFRLevel:    "B1",
		IPA:          "/ˈmɪl.ɪ.tri/",
		Definition:   "The armed forces of a country.",
		DefinitionVI: "Quân đội",
		Examples:     []string{"He served five years in the military."},
	},
	{
		Lemma:        "mission",
		POS:          "noun",
		CEFRLevel:    "B1",
		IPA:          "/ˈmɪʃ.ən/",
		Definition:   "An important assignment given to a person or group of people.",
		DefinitionVI: "Sứ mệnh, nhiệm vụ",
		Examples:     []string{"Their primary mission is to protect wildlife habitats."},
	},
	{
		Lemma:        "modern",
		POS:          "adjective",
		CEFRLevel:    "A2",
		IPA:          "/ˈmɒd.ən/",
		Definition:   "Relating to the present or recent times as opposed to the remote past.",
		DefinitionVI: "Hiện đại",
		Examples:     []string{"The museum is housed in a stunning modern building."},
	},
	{
		Lemma:        "modify",
		POS:          "verb",
		CEFRLevel:    "B1",
		IPA:          "/ˈmɒd.ɪ.faɪ/",
		Definition:   "Make partial or minor changes to something, typically so as to improve it.",
		DefinitionVI: "Sửa đổi",
		Examples:     []string{"We can modify the design based on your feedback."},
	},
	{
		Lemma:        "mystery",
		POS:          "noun",
		CEFRLevel:    "A2",
		IPA:          "/ˈmɪs.tər.i/",
		Definition:   "Something that is difficult or impossible to understand or explain.",
		DefinitionVI: "Bí ẩn",
		Examples:     []string{"The sudden disappearance remained a total mystery."},
	},
	{
		Lemma:        "native",
		POS:          "adjective",
		CEFRLevel:    "A2",
		IPA:          "/ˈneɪ.tɪv/",
		Definition:   "Associated with the place or circumstances of a person's birth.",
		DefinitionVI: "Bản địa",
		Examples:     []string{"She is a native speaker of Spanish."},
	},
	{
		Lemma:        "natural",
		POS:          "adjective",
		CEFRLevel:    "A2",
		IPA:          "/ˈnætʃ.ər.əl/",
		Definition:   "Existing in or caused by nature; not made or caused by humankind.",
		DefinitionVI: "Tự nhiên",
		Examples:     []string{"Enjoy the beauty of the natural landscape."},
	},
	{
		Lemma:        "negative",
		POS:          "adjective",
		CEFRLevel:    "A2",
		IPA:          "/ˈneɡ.ə.tɪv/",
		Definition:   "Consisting in or characterized by the absence rather than the presence of distinguishing features.",
		DefinitionVI: "Tiêu cực",
		Examples:     []string{"Try not to focus only on negative thoughts."},
	},
	{
		Lemma:        "network",
		POS:          "noun",
		CEFRLevel:    "B1",
		IPA:          "/ˈnet.wɜːk/",
		Definition:   "An interconnected group or system of things or people.",
		DefinitionVI: "Mạng lưới",
		Examples:     []string{"Building a strong professional network takes time."},
	},
	{
		Lemma:        "notice",
		POS:          "verb",
		CEFRLevel:    "A2",
		IPA:          "/ˈnəʊ.tɪs/",
		Definition:   "Become aware of.",
		DefinitionVI: "Nhận thấy",
		Examples:     []string{"Did you notice anything unusual about his behavior?"},
	},
	{
		Lemma:        "observe",
		POS:          "verb",
		CEFRLevel:    "B1",
		IPA:          "/əbˈzɜːv/",
		Definition:   "Notice or perceive something and register it as being significant.",
		DefinitionVI: "Quan sát",
		Examples:     []string{"Scientists observe wildlife patterns using satellite tracking."},
	},
	{
		Lemma:        "obtain",
		POS:          "verb",
		CEFRLevel:    "B1",
		IPA:          "/əbˈteɪn/",
		Definition:   "Get, acquire, or secure something.",
		DefinitionVI: "Đạt được, thu thập",
		Examples:     []string{"You must obtain a valid visa before entering the country."},
	},
	{
		Lemma:        "obvious",
		POS:          "adjective",
		CEFRLevel:    "A2",
		IPA:          "/ˈɒb.vi.əs/",
		Definition:   "Easily perceived or understood; clear, self-evident, or apparent.",
		DefinitionVI: "Rõ ràng",
		Examples:     []string{"It was obvious that she had practiced very hard."},
	},
	{
		Lemma:        "occupy",
		POS:          "verb",
		CEFRLevel:    "B1",
		IPA:          "/ˈɒk.jə.paɪ/",
		Definition:   "Reside or have one's place of business in a building.",
		DefinitionVI: "Chiếm giữ, cư ngụ",
		Examples:     []string{"The accounting department occupies the fourth floor."},
	},
	{
		Lemma:        "occur",
		POS:          "verb",
		CEFRLevel:    "B1",
		IPA:          "/əˈkɜːr/",
		Definition:   "Happen; take place.",
		DefinitionVI: "Xảy ra",
		Examples:     []string{"Minor errors can occur during peak traffic hours."},
	},
	{
		Lemma:        "official",
		POS:          "adjective",
		CEFRLevel:    "A2",
		IPA:          "/əˈfɪʃ.əl/",
		Definition:   "Relating to an authority or public body and its activities and responsibilities.",
		DefinitionVI: "Chính thức",
		Examples:     []string{"We are waiting for the official announcement."},
	},
	{
		Lemma:        "opinion",
		POS:          "noun",
		CEFRLevel:    "A2",
		IPA:          "/əˈpɪn.jən/",
		Definition:   "A view or judgment formed about something, not necessarily based on fact.",
		DefinitionVI: "Ý kiến",
		Examples:     []string{"Everyone is entitled to their own opinion."},
	},
	{
		Lemma:        "option",
		POS:          "noun",
		CEFRLevel:    "A2",
		IPA:          "/ˈɒp.ʃən/",
		Definition:   "A thing that is or may be chosen.",
		DefinitionVI: "Lựa chọn",
		Examples:     []string{"We have several good options for dinner tonight."},
	},
	{
		Lemma:        "organize",
		POS:          "verb",
		CEFRLevel:    "A2",
		IPA:          "/ˈɔː.ɡən.aɪz/",
		Definition:   "Arrange into a structured whole; order.",
		DefinitionVI: "Tổ chức, sắp xếp",
		Examples:     []string{"She helped organize the annual community festival."},
	},
}
