// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// SystemHealth Check process liveness.
	//
	// Returns success when the API process is able to serve requests.
	//
	// Corresponds with GET /health (the `SystemHealth` operationId).
	SystemHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SystemPing Check API dependency connectivity.
	//
	// Performs lightweight PostgreSQL and Redis checks for the trace proof.
	//
	// Corresponds with GET /ping (the `SystemPing` operationId).
	SystemPing(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SystemReady Check dependency readiness.
	//
	// Returns success only when every hard dependency is usable.
	//
	// Corresponds with GET /ready (the `SystemReady` operationId).
	SystemReady(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SystemVersion Read the deployed API version.
	//
	// Returns the version associated with the running API build.
	//
	// Corresponds with GET /version (the `SystemVersion` operationId).
	SystemVersion(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// SystemHealth Check process liveness.
//
// Returns success when the API process is able to serve requests.
//
// Corresponds with GET /health (the `SystemHealth` operationId).
func (c *Client) SystemHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSystemHealthRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// SystemPing Check API dependency connectivity.
//
// Performs lightweight PostgreSQL and Redis checks for the trace proof.
//
// Corresponds with GET /ping (the `SystemPing` operationId).
func (c *Client) SystemPing(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSystemPingRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// SystemReady Check dependency readiness.
//
// Returns success only when every hard dependency is usable.
//
// Corresponds with GET /ready (the `SystemReady` operationId).
func (c *Client) SystemReady(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSystemReadyRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// SystemVersion Read the deployed API version.
//
// Returns the version associated with the running API build.
//
// Corresponds with GET /version (the `SystemVersion` operationId).
func (c *Client) SystemVersion(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSystemVersionRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewSystemHealthRequest constructs an http.Request for the SystemHealth method
func NewSystemHealthRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewSystemPingRequest constructs an http.Request for the SystemPing method
func NewSystemPingRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/ping")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewSystemReadyRequest constructs an http.Request for the SystemReady method
func NewSystemReadyRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/ready")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewSystemVersionRequest constructs an http.Request for the SystemVersion method
func NewSystemVersionRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/version")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// SystemHealthWithResponse Check process liveness.
	//
	// Returns success when the API process is able to serve requests.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /health (the `SystemHealth` operationId).
	SystemHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*SystemHealthResponse, error)

	// SystemPingWithResponse Check API dependency connectivity.
	//
	// Performs lightweight PostgreSQL and Redis checks for the trace proof.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /ping (the `SystemPing` operationId).
	SystemPingWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*SystemPingResponse, error)

	// SystemReadyWithResponse Check dependency readiness.
	//
	// Returns success only when every hard dependency is usable.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /ready (the `SystemReady` operationId).
	SystemReadyWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*SystemReadyResponse, error)

	// SystemVersionWithResponse Read the deployed API version.
	//
	// Returns the version associated with the running API build.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /version (the `SystemVersion` operationId).
	SystemVersionWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*SystemVersionResponse, error)
}

// SystemHealthResponse200Headers the declared response headers of an HTTP 200 response for SystemHealth
type SystemHealthResponse200Headers struct {
	XRequestId *string
}

type SystemHealthResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Health
	// Headers200 the parsed response headers for an HTTP 200 response
	Headers200 *SystemHealthResponse200Headers
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r SystemHealthResponse) GetJSON200() *Health {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r SystemHealthResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r SystemHealthResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SystemHealthResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r SystemHealthResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// SystemPingResponse200Headers the declared response headers of an HTTP 200 response for SystemPing
type SystemPingResponse200Headers struct {
	XRequestId *string
}

type SystemPingResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Ping
	// Headers200 the parsed response headers for an HTTP 200 response
	Headers200 *SystemPingResponse200Headers
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r SystemPingResponse) GetJSON200() *Ping {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r SystemPingResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r SystemPingResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SystemPingResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r SystemPingResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// SystemReadyResponse200Headers the declared response headers of an HTTP 200 response for SystemReady
type SystemReadyResponse200Headers struct {
	XRequestId *string
}

// SystemReadyResponse503Headers the declared response headers of an HTTP 503 response for SystemReady
type SystemReadyResponse503Headers struct {
	RetryAfter *int
}

type SystemReadyResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Ready
	// ApplicationproblemJSON503 the response for an HTTP 503 `application/problem+json` response
	ApplicationproblemJSON503 *ServiceUnavailable
	// Headers200 the parsed response headers for an HTTP 200 response
	Headers200 *SystemReadyResponse200Headers
	// Headers503 the parsed response headers for an HTTP 503 response
	Headers503 *SystemReadyResponse503Headers
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r SystemReadyResponse) GetJSON200() *Ready {
	return r.JSON200
}

// GetApplicationproblemJSON503 returns the response for an HTTP 503 `application/problem+json` response
func (r SystemReadyResponse) GetApplicationproblemJSON503() *ServiceUnavailable {
	return r.ApplicationproblemJSON503
}

// GetBody returns the raw response body bytes
func (r SystemReadyResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r SystemReadyResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SystemReadyResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r SystemReadyResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// SystemVersionResponse200Headers the declared response headers of an HTTP 200 response for SystemVersion
type SystemVersionResponse200Headers struct {
	XRequestId *string
}

type SystemVersionResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Version
	// Headers200 the parsed response headers for an HTTP 200 response
	Headers200 *SystemVersionResponse200Headers
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r SystemVersionResponse) GetJSON200() *Version {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r SystemVersionResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r SystemVersionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SystemVersionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r SystemVersionResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// SystemHealthWithResponse Check process liveness.
//
// Returns success when the API process is able to serve requests.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /health (the `SystemHealth` operationId).
func (c *ClientWithResponses) SystemHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*SystemHealthResponse, error) {
	rsp, err := c.SystemHealth(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSystemHealthResponse(rsp)
}

// SystemPingWithResponse Check API dependency connectivity.
//
// Performs lightweight PostgreSQL and Redis checks for the trace proof.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /ping (the `SystemPing` operationId).
func (c *ClientWithResponses) SystemPingWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*SystemPingResponse, error) {
	rsp, err := c.SystemPing(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSystemPingResponse(rsp)
}

// SystemReadyWithResponse Check dependency readiness.
//
// Returns success only when every hard dependency is usable.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /ready (the `SystemReady` operationId).
func (c *ClientWithResponses) SystemReadyWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*SystemReadyResponse, error) {
	rsp, err := c.SystemReady(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSystemReadyResponse(rsp)
}

// SystemVersionWithResponse Read the deployed API version.
//
// Returns the version associated with the running API build.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /version (the `SystemVersion` operationId).
func (c *ClientWithResponses) SystemVersionWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*SystemVersionResponse, error) {
	rsp, err := c.SystemVersion(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSystemVersionResponse(rsp)
}

// ParseSystemHealthResponse parses an HTTP response from a SystemHealthWithResponse call
func ParseSystemHealthResponse(rsp *http.Response) (*SystemHealthResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SystemHealthResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Health
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	switch {
	case rsp.StatusCode == 200:
		var headers SystemHealthResponse200Headers
		if values := rsp.Header.Values("X-Request-Id"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "X-Request-Id", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.XRequestId = &value
		}
		response.Headers200 = &headers
	}

	return response, nil
}

// ParseSystemPingResponse parses an HTTP response from a SystemPingWithResponse call
func ParseSystemPingResponse(rsp *http.Response) (*SystemPingResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SystemPingResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Ping
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	switch {
	case rsp.StatusCode == 200:
		var headers SystemPingResponse200Headers
		if values := rsp.Header.Values("X-Request-Id"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "X-Request-Id", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.XRequestId = &value
		}
		response.Headers200 = &headers
	}

	return response, nil
}

// ParseSystemReadyResponse parses an HTTP response from a SystemReadyWithResponse call
func ParseSystemReadyResponse(rsp *http.Response) (*SystemReadyResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SystemReadyResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Ready
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest ServiceUnavailable
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON503 = &dest

	}

	switch {
	case rsp.StatusCode == 200:
		var headers SystemReadyResponse200Headers
		if values := rsp.Header.Values("X-Request-Id"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "X-Request-Id", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.XRequestId = &value
		}
		response.Headers200 = &headers
	case rsp.StatusCode == 503:
		var headers SystemReadyResponse503Headers
		if values := rsp.Header.Values("Retry-After"); len(values) > 0 {
			var value int
			if err := runtime.BindStyledParameterWithOptions("simple", "Retry-After", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "integer", Format: ""}); err != nil {
				return nil, err
			}
			headers.RetryAfter = &value
		}
		response.Headers503 = &headers
	}

	return response, nil
}

// ParseSystemVersionResponse parses an HTTP response from a SystemVersionWithResponse call
func ParseSystemVersionResponse(rsp *http.Response) (*SystemVersionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SystemVersionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Version
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	switch {
	case rsp.StatusCode == 200:
		var headers SystemVersionResponse200Headers
		if values := rsp.Header.Values("X-Request-Id"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "X-Request-Id", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.XRequestId = &value
		}
		response.Headers200 = &headers
	}

	return response, nil
}
