// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for HealthStatus.
const (
	HealthStatusOk HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case HealthStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for PingStatus.
const (
	PingStatusOk PingStatus = "ok"
)

// Valid indicates whether the value is a known member of the PingStatus enum.
func (e PingStatus) Valid() bool {
	switch e {
	case PingStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for PreferencesNotificationChannels.
const (
	PreferencesNotificationChannelsEmail PreferencesNotificationChannels = "email"
	PreferencesNotificationChannelsInApp PreferencesNotificationChannels = "in_app"
	PreferencesNotificationChannelsPush  PreferencesNotificationChannels = "push"
)

// Valid indicates whether the value is a known member of the PreferencesNotificationChannels enum.
func (e PreferencesNotificationChannels) Valid() bool {
	switch e {
	case PreferencesNotificationChannelsEmail:
		return true
	case PreferencesNotificationChannelsInApp:
		return true
	case PreferencesNotificationChannelsPush:
		return true
	default:
		return false
	}
}

// Defines values for PreferencesTheme.
const (
	PreferencesThemeDark   PreferencesTheme = "dark"
	PreferencesThemeLight  PreferencesTheme = "light"
	PreferencesThemeSystem PreferencesTheme = "system"
)

// Valid indicates whether the value is a known member of the PreferencesTheme enum.
func (e PreferencesTheme) Valid() bool {
	switch e {
	case PreferencesThemeDark:
		return true
	case PreferencesThemeLight:
		return true
	case PreferencesThemeSystem:
		return true
	default:
		return false
	}
}

// Defines values for ReadyStatus.
const (
	ReadyStatusReady ReadyStatus = "ready"
)

// Valid indicates whether the value is a known member of the ReadyStatus enum.
func (e ReadyStatus) Valid() bool {
	switch e {
	case ReadyStatusReady:
		return true
	default:
		return false
	}
}

// Defines values for ReplacePreferencesRequestNotificationChannels.
const (
	ReplacePreferencesRequestNotificationChannelsEmail ReplacePreferencesRequestNotificationChannels = "email"
	ReplacePreferencesRequestNotificationChannelsInApp ReplacePreferencesRequestNotificationChannels = "in_app"
	ReplacePreferencesRequestNotificationChannelsPush  ReplacePreferencesRequestNotificationChannels = "push"
)

// Valid indicates whether the value is a known member of the ReplacePreferencesRequestNotificationChannels enum.
func (e ReplacePreferencesRequestNotificationChannels) Valid() bool {
	switch e {
	case ReplacePreferencesRequestNotificationChannelsEmail:
		return true
	case ReplacePreferencesRequestNotificationChannelsInApp:
		return true
	case ReplacePreferencesRequestNotificationChannelsPush:
		return true
	default:
		return false
	}
}

// Defines values for ReplacePreferencesRequestTheme.
const (
	ReplacePreferencesRequestThemeDark   ReplacePreferencesRequestTheme = "dark"
	ReplacePreferencesRequestThemeLight  ReplacePreferencesRequestTheme = "light"
	ReplacePreferencesRequestThemeSystem ReplacePreferencesRequestTheme = "system"
)

// Valid indicates whether the value is a known member of the ReplacePreferencesRequestTheme enum.
func (e ReplacePreferencesRequestTheme) Valid() bool {
	switch e {
	case ReplacePreferencesRequestThemeDark:
		return true
	case ReplacePreferencesRequestThemeLight:
		return true
	case ReplacePreferencesRequestThemeSystem:
		return true
	default:
		return false
	}
}

// Defines values for RoleName.
const (
	Admin RoleName = "admin"
	User  RoleName = "user"
)

// Valid indicates whether the value is a known member of the RoleName enum.
func (e RoleName) Valid() bool {
	switch e {
	case Admin:
		return true
	case User:
		return true
	default:
		return false
	}
}

// Defines values for UserStatus.
const (
	Active          UserStatus = "active"
	Deleted         UserStatus = "deleted"
	PendingDeletion UserStatus = "pending_deletion"
	Suspended       UserStatus = "suspended"
)

// Valid indicates whether the value is a known member of the UserStatus enum.
func (e UserStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Deleted:
		return true
	case PendingDeletion:
		return true
	case Suspended:
		return true
	default:
		return false
	}
}

// AssignRoleRequest Grant a role to a user.
type AssignRoleRequest struct {
	// Role Exactly two roles exist (BR-RBAC-02). A third is an ADR, not a row: it changes the shape of the product rather than its data.
	Role RoleName `json:"role"`
}

// Cursor Opaque, URL-safe cursor encoding a stable sort value and ID.
type Cursor = string

// Health Successful process liveness result.
type Health struct {
	// Status Confirms that the process is serving requests.
	Status HealthStatus `json:"status"`
}

// HealthStatus Confirms that the process is serving requests.
type HealthStatus string

// Me The authenticated caller's own account. There is no operation that returns this shape for anybody else: the server reads the actor from the access token and the path carries no user id.
type Me struct {
	CreatedAt time.Time `json:"created_at"`

	// Email Returned only here. No other operation exposes a user's email address.
	Email openapi_types.Email `json:"email"`

	// EmailVerifiedAt When the address was verified, or null while it is unverified.
	EmailVerifiedAt *time.Time `json:"email_verified_at,omitempty"`

	// Id Stable identifier every other resource references.
	Id openapi_types.UUID `json:"id"`

	// Profile Descriptive data about the caller. Nothing here is used to authenticate.
	Profile MeProfile `json:"profile"`

	// Status Account lifecycle state. `pending_deletion` is the 30-day grace period, in which the account is unusable but still recoverable by the owner.
	Status    UserStatus `json:"status"`
	UpdatedAt time.Time  `json:"updated_at"`
}

// MeProfile Descriptive data about the caller. Nothing here is used to authenticate.
type MeProfile struct {
	// AvatarUrl Public avatar URL, or null when none has been uploaded.
	AvatarUrl *string `json:"avatar_url,omitempty"`

	// Country ISO 3166-1 alpha-2 country code, or null.
	Country *string `json:"country,omitempty"`

	// DateOfBirth Used only for the age gate. It is never shown to other learners and never leaves this operation.
	DateOfBirth *openapi_types.Date `json:"date_of_birth,omitempty"`

	// DisplayName Shown to other learners. Names that impersonate Fluentra staff are rejected.
	DisplayName string `json:"display_name"`

	// Timezone IANA timezone name. Every timestamp in the API stays UTC; this is used to place reminders and streak boundaries in the learner's day.
	Timezone string `json:"timezone"`
}

// MyPermissions What the caller is allowed to do, as the server currently sees it.
// This is advisory (BR-RBAC-08). It exists so the interface can hide actions that would fail, not so the client can decide anything: every server call re-checks, and a client that has this list is no closer to using a permission it was not granted.
type MyPermissions struct {
	// Permissions Every named permission the caller's roles grant, resolved and flattened. A learner holds none of these — access to their own data is not a named permission, it is what `/me` means.
	Permissions []string `json:"permissions"`

	// Roles The roles assigned to the caller. There are exactly two in this product.
	Roles []RoleName `json:"roles"`
}

// Page Cursor pagination metadata returned with every user-facing list.
type Page struct {
	// HasMore Whether another page can be requested using next_cursor.
	HasMore bool `json:"has_more"`

	// Limit Number of items requested for this page.
	Limit int `json:"limit"`

	// NextCursor Opaque cursor for the next page, omitted when there is no next page.
	NextCursor *Cursor `json:"next_cursor,omitempty"`
}

// Ping Successful API dependency connectivity result.
type Ping struct {
	// Status Confirms that PostgreSQL and Redis responded.
	Status PingStatus `json:"status"`
}

// PingStatus Confirms that PostgreSQL and Redis responded.
type PingStatus string

// Preferences The caller's settings. Replaced as a whole, never patched.
type Preferences struct {
	// AiProcessingOptOut Disables AI grading only. Deterministic exercises keep working, so opting out never costs the learner access to the product.
	AiProcessingOptOut bool `json:"ai_processing_opt_out"`

	// DailyGoalMinutes Minutes of study the learner is aiming for each day.
	DailyGoalMinutes int `json:"daily_goal_minutes"`

	// Locale BCP 47 language tag, optionally with a region.
	Locale string `json:"locale"`

	// NotificationChannels Channels the learner accepts notifications on.
	NotificationChannels []PreferencesNotificationChannels `json:"notification_channels"`

	// QuietHours A window in which no notification is delivered, or null for none. It is one object rather than two fields so that half a window cannot be expressed.
	QuietHours *QuietHours      `json:"quiet_hours,omitempty"`
	Theme      PreferencesTheme `json:"theme"`
	UpdatedAt  time.Time        `json:"updated_at"`
}

// PreferencesNotificationChannels defines model for Preferences.NotificationChannels.
type PreferencesNotificationChannels string

// PreferencesTheme defines model for Preferences.Theme.
type PreferencesTheme string

// Problem RFC 9457 Problem Details response.
type Problem struct {
	// Code Stable machine-readable error code.
	Code string `json:"code"`

	// Detail A safe explanation of this occurrence.
	Detail *string `json:"detail,omitempty"`

	// Instance Request path that produced the problem.
	Instance *string `json:"instance,omitempty"`

	// Meta Safe, problem-specific metadata.
	Meta *map[string]interface{} `json:"meta,omitempty"`

	// RequestId Correlation identifier for support and observability.
	RequestId string `json:"request_id"`

	// Status HTTP status code for this occurrence.
	Status int `json:"status"`

	// Title A short, safe, human-readable summary.
	Title string `json:"title"`

	// Type Stable URI identifying the problem type.
	Type string `json:"type"`
}

// QuietHours Local wall-clock times in the learner's timezone. A window may wrap past midnight, which is the normal case for sleeping hours.
type QuietHours struct {
	End   string `json:"end"`
	Start string `json:"start"`
}

// Ready Successful hard dependency readiness result.
type Ready struct {
	// Status Confirms that every hard dependency is usable.
	Status ReadyStatus `json:"status"`
}

// ReadyStatus Confirms that every hard dependency is usable.
type ReadyStatus string

// ReplacePreferencesRequest The complete preference set. This is a PUT: every field is required, and what the caller sends is exactly what is stored.
type ReplacePreferencesRequest struct {
	AiProcessingOptOut   bool                                            `json:"ai_processing_opt_out"`
	DailyGoalMinutes     int                                             `json:"daily_goal_minutes"`
	Locale               string                                          `json:"locale"`
	NotificationChannels []ReplacePreferencesRequestNotificationChannels `json:"notification_channels"`
	QuietHours           *QuietHours                                     `json:"quiet_hours,omitempty"`
	Theme                ReplacePreferencesRequestTheme                  `json:"theme"`
}

// ReplacePreferencesRequestNotificationChannels defines model for ReplacePreferencesRequest.NotificationChannels.
type ReplacePreferencesRequestNotificationChannels string

// ReplacePreferencesRequestTheme defines model for ReplacePreferencesRequest.Theme.
type ReplacePreferencesRequestTheme string

// Role A role and the permissions it grants.
type Role struct {
	Description string `json:"description"`

	// Name Exactly two roles exist (BR-RBAC-02). A third is an ADR, not a row: it changes the shape of the product rather than its data.
	Name        RoleName `json:"name"`
	Permissions []string `json:"permissions"`
}

// RoleList The role catalogue. It is small and fixed, so it is not paginated.
type RoleList struct {
	Items []Role `json:"items"`
}

// RoleName Exactly two roles exist (BR-RBAC-02). A third is an ADR, not a row: it changes the shape of the product rather than its data.
type RoleName string

// UpdateMeRequest A partial update. Omit a field to leave it unchanged; an unknown field is a validation failure rather than something quietly ignored, because a misspelled field name that returns 200 is indistinguishable from success.
type UpdateMeRequest struct {
	Country     *string             `json:"country,omitempty"`
	DateOfBirth *openapi_types.Date `json:"date_of_birth,omitempty"`
	DisplayName *string             `json:"display_name,omitempty"`
	Timezone    *string             `json:"timezone,omitempty"`
}

// UserRoles The roles held by one user, after the change.
type UserRoles struct {
	Roles  []RoleName         `json:"roles"`
	UserId openapi_types.UUID `json:"user_id"`
}

// UserStatus Account lifecycle state. `pending_deletion` is the 30-day grace period, in which the account is unusable but still recoverable by the owner.
type UserStatus string

// ValidationError One invalid request field.
type ValidationError struct {
	// Code Stable validation error code.
	Code string `json:"code"`

	// Field JSON field path that failed validation.
	Field string `json:"field"`

	// Message Localised, safe explanation of the validation failure.
	Message string `json:"message"`
}

// ValidationProblem defines model for ValidationProblem.
type ValidationProblem struct {
	// Code Stable machine-readable error code.
	Code string `json:"code"`

	// Detail A safe explanation of this occurrence.
	Detail *string `json:"detail,omitempty"`

	// Errors Field-level validation failures.
	Errors []ValidationError `json:"errors"`

	// Instance Request path that produced the problem.
	Instance *string `json:"instance,omitempty"`

	// Meta Safe, problem-specific metadata.
	Meta *map[string]interface{} `json:"meta,omitempty"`

	// RequestId Correlation identifier for support and observability.
	RequestId string `json:"request_id"`

	// Status HTTP status code for this occurrence.
	Status int `json:"status"`

	// Title A short, safe, human-readable summary.
	Title string `json:"title"`

	// Type Stable URI identifying the problem type.
	Type string `json:"type"`
}

// Version Deployed API build version.
type Version struct {
	// Version Version associated with the running API build.
	Version string `json:"version"`
}

// BadRequest RFC 9457 Problem Details response.
type BadRequest = Problem

// Conflict RFC 9457 Problem Details response.
type Conflict = Problem

// Forbidden RFC 9457 Problem Details response.
type Forbidden = Problem

// InternalServerError RFC 9457 Problem Details response.
type InternalServerError = Problem

// NotFound RFC 9457 Problem Details response.
type NotFound = Problem

// ServiceUnavailable RFC 9457 Problem Details response.
type ServiceUnavailable = Problem

// TooManyRequests RFC 9457 Problem Details response.
type TooManyRequests = Problem

// Unauthorized RFC 9457 Problem Details response.
type Unauthorized = Problem

// ValidationFailed defines model for ValidationFailed.
type ValidationFailed = ValidationProblem

// RbacAssignRoleJSONRequestBody defines body for RbacAssignRole for application/json ContentType.
type RbacAssignRoleJSONRequestBody = AssignRoleRequest

// UserUpdateMeJSONRequestBody defines body for UserUpdateMe for application/json ContentType.
type UserUpdateMeJSONRequestBody = UpdateMeRequest

// UserReplaceMyPreferencesJSONRequestBody defines body for UserReplaceMyPreferences for application/json ContentType.
type UserReplaceMyPreferencesJSONRequestBody = ReplacePreferencesRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// RbacListRoles List roles and the permissions they grant.
	// (GET /admin/roles)
	RbacListRoles(w http.ResponseWriter, r *http.Request)
	// RbacAssignRole Grant a role to a user.
	// (POST /admin/users/{id}/roles)
	RbacAssignRole(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// RbacRevokeRole Revoke a role from a user.
	// (DELETE /admin/users/{id}/roles/{role})
	RbacRevokeRole(w http.ResponseWriter, r *http.Request, id openapi_types.UUID, role RoleName)
	// SystemHealth Check process liveness.
	// (GET /health)
	SystemHealth(w http.ResponseWriter, r *http.Request)
	// UserGetMe Read the caller's own account.
	// (GET /me)
	UserGetMe(w http.ResponseWriter, r *http.Request)
	// UserUpdateMe Update the caller's own profile.
	// (PATCH /me)
	UserUpdateMe(w http.ResponseWriter, r *http.Request)
	// RbacGetMyPermissions Read the caller's own effective permissions.
	// (GET /me/permissions)
	RbacGetMyPermissions(w http.ResponseWriter, r *http.Request)
	// UserGetMyPreferences Read the caller's preferences.
	// (GET /me/preferences)
	UserGetMyPreferences(w http.ResponseWriter, r *http.Request)
	// UserReplaceMyPreferences Replace the caller's preferences.
	// (PUT /me/preferences)
	UserReplaceMyPreferences(w http.ResponseWriter, r *http.Request)
	// SystemPing Check API dependency connectivity.
	// (GET /ping)
	SystemPing(w http.ResponseWriter, r *http.Request)
	// SystemReady Check dependency readiness.
	// (GET /ready)
	SystemReady(w http.ResponseWriter, r *http.Request)
	// SystemVersion Read the deployed API version.
	// (GET /version)
	SystemVersion(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// RbacListRoles List roles and the permissions they grant.
// (GET /admin/roles)
func (_ Unimplemented) RbacListRoles(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// RbacAssignRole Grant a role to a user.
// (POST /admin/users/{id}/roles)
func (_ Unimplemented) RbacAssignRole(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// RbacRevokeRole Revoke a role from a user.
// (DELETE /admin/users/{id}/roles/{role})
func (_ Unimplemented) RbacRevokeRole(w http.ResponseWriter, r *http.Request, id openapi_types.UUID, role RoleName) {
	w.WriteHeader(http.StatusNotImplemented)
}

// SystemHealth Check process liveness.
// (GET /health)
func (_ Unimplemented) SystemHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UserGetMe Read the caller's own account.
// (GET /me)
func (_ Unimplemented) UserGetMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UserUpdateMe Update the caller's own profile.
// (PATCH /me)
func (_ Unimplemented) UserUpdateMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// RbacGetMyPermissions Read the caller's own effective permissions.
// (GET /me/permissions)
func (_ Unimplemented) RbacGetMyPermissions(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UserGetMyPreferences Read the caller's preferences.
// (GET /me/preferences)
func (_ Unimplemented) UserGetMyPreferences(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UserReplaceMyPreferences Replace the caller's preferences.
// (PUT /me/preferences)
func (_ Unimplemented) UserReplaceMyPreferences(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// SystemPing Check API dependency connectivity.
// (GET /ping)
func (_ Unimplemented) SystemPing(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// SystemReady Check dependency readiness.
// (GET /ready)
func (_ Unimplemented) SystemReady(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// SystemVersion Read the deployed API version.
// (GET /version)
func (_ Unimplemented) SystemVersion(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// RbacListRoles operation middleware
func (siw *ServerInterfaceWrapper) RbacListRoles(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RbacListRoles(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RbacAssignRole operation middleware
func (siw *ServerInterfaceWrapper) RbacAssignRole(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RbacAssignRole(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RbacRevokeRole operation middleware
func (siw *ServerInterfaceWrapper) RbacRevokeRole(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "role" -------------
	var role RoleName

	err = runtime.BindStyledParameterWithOptions("simple", "role", chi.URLParam(r, "role"), &role, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "role", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RbacRevokeRole(w, r, id, role)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SystemHealth operation middleware
func (siw *ServerInterfaceWrapper) SystemHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SystemHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UserGetMe operation middleware
func (siw *ServerInterfaceWrapper) UserGetMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UserGetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UserUpdateMe operation middleware
func (siw *ServerInterfaceWrapper) UserUpdateMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UserUpdateMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RbacGetMyPermissions operation middleware
func (siw *ServerInterfaceWrapper) RbacGetMyPermissions(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RbacGetMyPermissions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UserGetMyPreferences operation middleware
func (siw *ServerInterfaceWrapper) UserGetMyPreferences(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UserGetMyPreferences(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UserReplaceMyPreferences operation middleware
func (siw *ServerInterfaceWrapper) UserReplaceMyPreferences(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UserReplaceMyPreferences(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SystemPing operation middleware
func (siw *ServerInterfaceWrapper) SystemPing(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SystemPing(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SystemReady operation middleware
func (siw *ServerInterfaceWrapper) SystemReady(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SystemReady(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SystemVersion operation middleware
func (siw *ServerInterfaceWrapper) SystemVersion(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SystemVersion(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/ping", wrapper.SystemPing)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.SystemHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/ready", wrapper.SystemReady)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/version", wrapper.SystemVersion)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/me", wrapper.UserGetMe)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/me", wrapper.UserUpdateMe)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/me/permissions", wrapper.RbacGetMyPermissions)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/me/preferences", wrapper.UserGetMyPreferences)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/me/preferences", wrapper.UserReplaceMyPreferences)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/roles", wrapper.RbacListRoles)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/admin/users/{id}/roles", wrapper.RbacAssignRole)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/admin/users/{id}/roles/{role}", wrapper.RbacRevokeRole)
	})

	return r
}

type BadRequestApplicationProblemPlusJSONResponse Problem

type ConflictApplicationProblemPlusJSONResponse Problem

type ForbiddenApplicationProblemPlusJSONResponse Problem

type InternalServerErrorApplicationProblemPlusJSONResponse Problem

type NotFoundApplicationProblemPlusJSONResponse Problem

type ServiceUnavailableResponseHeaders struct {
	RetryAfter *int
}
type ServiceUnavailableApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers ServiceUnavailableResponseHeaders
}

type TooManyRequestsResponseHeaders struct {
	RetryAfter *int
}
type TooManyRequestsApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers TooManyRequestsResponseHeaders
}

type UnauthorizedApplicationProblemPlusJSONResponse Problem

type ValidationFailedApplicationProblemPlusJSONResponse ValidationProblem

type RbacListRolesRequestObject struct {
}

type RbacListRolesResponseObject interface {
	VisitRbacListRolesResponse(w http.ResponseWriter) error
}

type RbacListRoles200ResponseHeaders struct {
	XRequestId *string
}

type RbacListRoles200JSONResponse struct {
	Body    RoleList
	Headers RbacListRoles200ResponseHeaders
}

func (response RbacListRoles200JSONResponse) VisitRbacListRolesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.XRequestId != nil {
		w.Header().Set("X-Request-Id", fmt.Sprint(*response.Headers.XRequestId))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RbacListRoles401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response RbacListRoles401ApplicationProblemPlusJSONResponse) VisitRbacListRolesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RbacListRoles403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response RbacListRoles403ApplicationProblemPlusJSONResponse) VisitRbacListRolesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type RbacAssignRoleRequestObject struct {
	Id   openapi_types.UUID `json:"id"`
	Body *RbacAssignRoleJSONRequestBody
}

type RbacAssignRoleResponseObject interface {
	VisitRbacAssignRoleResponse(w http.ResponseWriter) error
}

type RbacAssignRole200ResponseHeaders struct {
	XRequestId *string
}

type RbacAssignRole200JSONResponse struct {
	Body    UserRoles
	Headers RbacAssignRole200ResponseHeaders
}

func (response RbacAssignRole200JSONResponse) VisitRbacAssignRoleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.XRequestId != nil {
		w.Header().Set("X-Request-Id", fmt.Sprint(*response.Headers.XRequestId))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RbacAssignRole400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response RbacAssignRole400ApplicationProblemPlusJSONResponse) VisitRbacAssignRoleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type RbacAssignRole401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response RbacAssignRole401ApplicationProblemPlusJSONResponse) VisitRbacAssignRoleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RbacAssignRole403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response RbacAssignRole403ApplicationProblemPlusJSONResponse) VisitRbacAssignRoleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type RbacAssignRole404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response RbacAssignRole404ApplicationProblemPlusJSONResponse) VisitRbacAssignRoleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type RbacAssignRole422ApplicationProblemPlusJSONResponse struct {
	ValidationFailedApplicationProblemPlusJSONResponse
}

func (response RbacAssignRole422ApplicationProblemPlusJSONResponse) VisitRbacAssignRoleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type RbacRevokeRoleRequestObject struct {
	Id   openapi_types.UUID `json:"id"`
	Role RoleName           `json:"role"`
}

type RbacRevokeRoleResponseObject interface {
	VisitRbacRevokeRoleResponse(w http.ResponseWriter) error
}

type RbacRevokeRole200ResponseHeaders struct {
	XRequestId *string
}

type RbacRevokeRole200JSONResponse struct {
	Body    UserRoles
	Headers RbacRevokeRole200ResponseHeaders
}

func (response RbacRevokeRole200JSONResponse) VisitRbacRevokeRoleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.XRequestId != nil {
		w.Header().Set("X-Request-Id", fmt.Sprint(*response.Headers.XRequestId))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RbacRevokeRole401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response RbacRevokeRole401ApplicationProblemPlusJSONResponse) VisitRbacRevokeRoleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RbacRevokeRole403ApplicationProblemPlusJSONResponse struct {
	ForbiddenApplicationProblemPlusJSONResponse
}

func (response RbacRevokeRole403ApplicationProblemPlusJSONResponse) VisitRbacRevokeRoleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type RbacRevokeRole404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response RbacRevokeRole404ApplicationProblemPlusJSONResponse) VisitRbacRevokeRoleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type RbacRevokeRole409ApplicationProblemPlusJSONResponse struct {
	ConflictApplicationProblemPlusJSONResponse
}

func (response RbacRevokeRole409ApplicationProblemPlusJSONResponse) VisitRbacRevokeRoleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type SystemHealthRequestObject struct {
}

type SystemHealthResponseObject interface {
	VisitSystemHealthResponse(w http.ResponseWriter) error
}

type SystemHealth200ResponseHeaders struct {
	XRequestId *string
}

type SystemHealth200JSONResponse struct {
	Body    Health
	Headers SystemHealth200ResponseHeaders
}

func (response SystemHealth200JSONResponse) VisitSystemHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.XRequestId != nil {
		w.Header().Set("X-Request-Id", fmt.Sprint(*response.Headers.XRequestId))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UserGetMeRequestObject struct {
}

type UserGetMeResponseObject interface {
	VisitUserGetMeResponse(w http.ResponseWriter) error
}

type UserGetMe200ResponseHeaders struct {
	XRequestId *string
}

type UserGetMe200JSONResponse struct {
	Body    Me
	Headers UserGetMe200ResponseHeaders
}

func (response UserGetMe200JSONResponse) VisitUserGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.XRequestId != nil {
		w.Header().Set("X-Request-Id", fmt.Sprint(*response.Headers.XRequestId))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UserGetMe401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response UserGetMe401ApplicationProblemPlusJSONResponse) VisitUserGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UserGetMe404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response UserGetMe404ApplicationProblemPlusJSONResponse) VisitUserGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UserUpdateMeRequestObject struct {
	Body *UserUpdateMeJSONRequestBody
}

type UserUpdateMeResponseObject interface {
	VisitUserUpdateMeResponse(w http.ResponseWriter) error
}

type UserUpdateMe200ResponseHeaders struct {
	XRequestId *string
}

type UserUpdateMe200JSONResponse struct {
	Body    Me
	Headers UserUpdateMe200ResponseHeaders
}

func (response UserUpdateMe200JSONResponse) VisitUserUpdateMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.XRequestId != nil {
		w.Header().Set("X-Request-Id", fmt.Sprint(*response.Headers.XRequestId))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UserUpdateMe400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response UserUpdateMe400ApplicationProblemPlusJSONResponse) VisitUserUpdateMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UserUpdateMe401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response UserUpdateMe401ApplicationProblemPlusJSONResponse) VisitUserUpdateMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UserUpdateMe404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response UserUpdateMe404ApplicationProblemPlusJSONResponse) VisitUserUpdateMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UserUpdateMe422ApplicationProblemPlusJSONResponse struct {
	ValidationFailedApplicationProblemPlusJSONResponse
}

func (response UserUpdateMe422ApplicationProblemPlusJSONResponse) VisitUserUpdateMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type RbacGetMyPermissionsRequestObject struct {
}

type RbacGetMyPermissionsResponseObject interface {
	VisitRbacGetMyPermissionsResponse(w http.ResponseWriter) error
}

type RbacGetMyPermissions200ResponseHeaders struct {
	XRequestId *string
}

type RbacGetMyPermissions200JSONResponse struct {
	Body    MyPermissions
	Headers RbacGetMyPermissions200ResponseHeaders
}

func (response RbacGetMyPermissions200JSONResponse) VisitRbacGetMyPermissionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.XRequestId != nil {
		w.Header().Set("X-Request-Id", fmt.Sprint(*response.Headers.XRequestId))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RbacGetMyPermissions401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response RbacGetMyPermissions401ApplicationProblemPlusJSONResponse) VisitRbacGetMyPermissionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UserGetMyPreferencesRequestObject struct {
}

type UserGetMyPreferencesResponseObject interface {
	VisitUserGetMyPreferencesResponse(w http.ResponseWriter) error
}

type UserGetMyPreferences200ResponseHeaders struct {
	XRequestId *string
}

type UserGetMyPreferences200JSONResponse struct {
	Body    Preferences
	Headers UserGetMyPreferences200ResponseHeaders
}

func (response UserGetMyPreferences200JSONResponse) VisitUserGetMyPreferencesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.XRequestId != nil {
		w.Header().Set("X-Request-Id", fmt.Sprint(*response.Headers.XRequestId))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UserGetMyPreferences401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response UserGetMyPreferences401ApplicationProblemPlusJSONResponse) VisitUserGetMyPreferencesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UserGetMyPreferences404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response UserGetMyPreferences404ApplicationProblemPlusJSONResponse) VisitUserGetMyPreferencesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UserReplaceMyPreferencesRequestObject struct {
	Body *UserReplaceMyPreferencesJSONRequestBody
}

type UserReplaceMyPreferencesResponseObject interface {
	VisitUserReplaceMyPreferencesResponse(w http.ResponseWriter) error
}

type UserReplaceMyPreferences200ResponseHeaders struct {
	XRequestId *string
}

type UserReplaceMyPreferences200JSONResponse struct {
	Body    Preferences
	Headers UserReplaceMyPreferences200ResponseHeaders
}

func (response UserReplaceMyPreferences200JSONResponse) VisitUserReplaceMyPreferencesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.XRequestId != nil {
		w.Header().Set("X-Request-Id", fmt.Sprint(*response.Headers.XRequestId))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UserReplaceMyPreferences400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response UserReplaceMyPreferences400ApplicationProblemPlusJSONResponse) VisitUserReplaceMyPreferencesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UserReplaceMyPreferences401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response UserReplaceMyPreferences401ApplicationProblemPlusJSONResponse) VisitUserReplaceMyPreferencesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UserReplaceMyPreferences404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response UserReplaceMyPreferences404ApplicationProblemPlusJSONResponse) VisitUserReplaceMyPreferencesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UserReplaceMyPreferences422ApplicationProblemPlusJSONResponse struct {
	ValidationFailedApplicationProblemPlusJSONResponse
}

func (response UserReplaceMyPreferences422ApplicationProblemPlusJSONResponse) VisitUserReplaceMyPreferencesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type SystemPingRequestObject struct {
}

type SystemPingResponseObject interface {
	VisitSystemPingResponse(w http.ResponseWriter) error
}

type SystemPing200ResponseHeaders struct {
	XRequestId *string
}

type SystemPing200JSONResponse struct {
	Body    Ping
	Headers SystemPing200ResponseHeaders
}

func (response SystemPing200JSONResponse) VisitSystemPingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.XRequestId != nil {
		w.Header().Set("X-Request-Id", fmt.Sprint(*response.Headers.XRequestId))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SystemReadyRequestObject struct {
}

type SystemReadyResponseObject interface {
	VisitSystemReadyResponse(w http.ResponseWriter) error
}

type SystemReady200ResponseHeaders struct {
	XRequestId *string
}

type SystemReady200JSONResponse struct {
	Body    Ready
	Headers SystemReady200ResponseHeaders
}

func (response SystemReady200JSONResponse) VisitSystemReadyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.XRequestId != nil {
		w.Header().Set("X-Request-Id", fmt.Sprint(*response.Headers.XRequestId))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SystemReady503ApplicationProblemPlusJSONResponse struct {
	ServiceUnavailableApplicationProblemPlusJSONResponse
}

func (response SystemReady503ApplicationProblemPlusJSONResponse) VisitSystemReadyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type SystemVersionRequestObject struct {
}

type SystemVersionResponseObject interface {
	VisitSystemVersionResponse(w http.ResponseWriter) error
}

type SystemVersion200ResponseHeaders struct {
	XRequestId *string
}

type SystemVersion200JSONResponse struct {
	Body    Version
	Headers SystemVersion200ResponseHeaders
}

func (response SystemVersion200JSONResponse) VisitSystemVersionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.XRequestId != nil {
		w.Header().Set("X-Request-Id", fmt.Sprint(*response.Headers.XRequestId))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// RbacListRoles List roles and the permissions they grant.
	// (GET /admin/roles)
	RbacListRoles(ctx context.Context, request RbacListRolesRequestObject) (RbacListRolesResponseObject, error)
	// RbacAssignRole Grant a role to a user.
	// (POST /admin/users/{id}/roles)
	RbacAssignRole(ctx context.Context, request RbacAssignRoleRequestObject) (RbacAssignRoleResponseObject, error)
	// RbacRevokeRole Revoke a role from a user.
	// (DELETE /admin/users/{id}/roles/{role})
	RbacRevokeRole(ctx context.Context, request RbacRevokeRoleRequestObject) (RbacRevokeRoleResponseObject, error)
	// SystemHealth Check process liveness.
	// (GET /health)
	SystemHealth(ctx context.Context, request SystemHealthRequestObject) (SystemHealthResponseObject, error)
	// UserGetMe Read the caller's own account.
	// (GET /me)
	UserGetMe(ctx context.Context, request UserGetMeRequestObject) (UserGetMeResponseObject, error)
	// UserUpdateMe Update the caller's own profile.
	// (PATCH /me)
	UserUpdateMe(ctx context.Context, request UserUpdateMeRequestObject) (UserUpdateMeResponseObject, error)
	// RbacGetMyPermissions Read the caller's own effective permissions.
	// (GET /me/permissions)
	RbacGetMyPermissions(ctx context.Context, request RbacGetMyPermissionsRequestObject) (RbacGetMyPermissionsResponseObject, error)
	// UserGetMyPreferences Read the caller's preferences.
	// (GET /me/preferences)
	UserGetMyPreferences(ctx context.Context, request UserGetMyPreferencesRequestObject) (UserGetMyPreferencesResponseObject, error)
	// UserReplaceMyPreferences Replace the caller's preferences.
	// (PUT /me/preferences)
	UserReplaceMyPreferences(ctx context.Context, request UserReplaceMyPreferencesRequestObject) (UserReplaceMyPreferencesResponseObject, error)
	// SystemPing Check API dependency connectivity.
	// (GET /ping)
	SystemPing(ctx context.Context, request SystemPingRequestObject) (SystemPingResponseObject, error)
	// SystemReady Check dependency readiness.
	// (GET /ready)
	SystemReady(ctx context.Context, request SystemReadyRequestObject) (SystemReadyResponseObject, error)
	// SystemVersion Read the deployed API version.
	// (GET /version)
	SystemVersion(ctx context.Context, request SystemVersionRequestObject) (SystemVersionResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// RbacListRoles operation middleware
func (sh *strictHandler) RbacListRoles(w http.ResponseWriter, r *http.Request) {
	var request RbacListRolesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RbacListRoles(ctx, request.(RbacListRolesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RbacListRoles")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RbacListRolesResponseObject); ok {
		if err := validResponse.VisitRbacListRolesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RbacAssignRole operation middleware
func (sh *strictHandler) RbacAssignRole(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request RbacAssignRoleRequestObject

	request.Id = id

	var body RbacAssignRoleJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RbacAssignRole(ctx, request.(RbacAssignRoleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RbacAssignRole")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RbacAssignRoleResponseObject); ok {
		if err := validResponse.VisitRbacAssignRoleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RbacRevokeRole operation middleware
func (sh *strictHandler) RbacRevokeRole(w http.ResponseWriter, r *http.Request, id openapi_types.UUID, role RoleName) {
	var request RbacRevokeRoleRequestObject

	request.Id = id
	request.Role = role

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RbacRevokeRole(ctx, request.(RbacRevokeRoleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RbacRevokeRole")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RbacRevokeRoleResponseObject); ok {
		if err := validResponse.VisitRbacRevokeRoleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SystemHealth operation middleware
func (sh *strictHandler) SystemHealth(w http.ResponseWriter, r *http.Request) {
	var request SystemHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SystemHealth(ctx, request.(SystemHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SystemHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SystemHealthResponseObject); ok {
		if err := validResponse.VisitSystemHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UserGetMe operation middleware
func (sh *strictHandler) UserGetMe(w http.ResponseWriter, r *http.Request) {
	var request UserGetMeRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UserGetMe(ctx, request.(UserGetMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UserGetMe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UserGetMeResponseObject); ok {
		if err := validResponse.VisitUserGetMeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UserUpdateMe operation middleware
func (sh *strictHandler) UserUpdateMe(w http.ResponseWriter, r *http.Request) {
	var request UserUpdateMeRequestObject

	var body UserUpdateMeJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UserUpdateMe(ctx, request.(UserUpdateMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UserUpdateMe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UserUpdateMeResponseObject); ok {
		if err := validResponse.VisitUserUpdateMeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RbacGetMyPermissions operation middleware
func (sh *strictHandler) RbacGetMyPermissions(w http.ResponseWriter, r *http.Request) {
	var request RbacGetMyPermissionsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RbacGetMyPermissions(ctx, request.(RbacGetMyPermissionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RbacGetMyPermissions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RbacGetMyPermissionsResponseObject); ok {
		if err := validResponse.VisitRbacGetMyPermissionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UserGetMyPreferences operation middleware
func (sh *strictHandler) UserGetMyPreferences(w http.ResponseWriter, r *http.Request) {
	var request UserGetMyPreferencesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UserGetMyPreferences(ctx, request.(UserGetMyPreferencesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UserGetMyPreferences")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UserGetMyPreferencesResponseObject); ok {
		if err := validResponse.VisitUserGetMyPreferencesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UserReplaceMyPreferences operation middleware
func (sh *strictHandler) UserReplaceMyPreferences(w http.ResponseWriter, r *http.Request) {
	var request UserReplaceMyPreferencesRequestObject

	var body UserReplaceMyPreferencesJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UserReplaceMyPreferences(ctx, request.(UserReplaceMyPreferencesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UserReplaceMyPreferences")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UserReplaceMyPreferencesResponseObject); ok {
		if err := validResponse.VisitUserReplaceMyPreferencesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SystemPing operation middleware
func (sh *strictHandler) SystemPing(w http.ResponseWriter, r *http.Request) {
	var request SystemPingRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SystemPing(ctx, request.(SystemPingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SystemPing")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SystemPingResponseObject); ok {
		if err := validResponse.VisitSystemPingResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SystemReady operation middleware
func (sh *strictHandler) SystemReady(w http.ResponseWriter, r *http.Request) {
	var request SystemReadyRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SystemReady(ctx, request.(SystemReadyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SystemReady")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SystemReadyResponseObject); ok {
		if err := validResponse.VisitSystemReadyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SystemVersion operation middleware
func (sh *strictHandler) SystemVersion(w http.ResponseWriter, r *http.Request) {
	var request SystemVersionRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SystemVersion(ctx, request.(SystemVersionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SystemVersion")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SystemVersionResponseObject); ok {
		if err := validResponse.VisitSystemVersionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7H3rchs3lvCroPpLVZLvIylKsmOL+fEtLckTZiRZ1iVzsbUy2H3IRoQGOgCaEserqn2IfcJ9kq0DoO9N",
	"kZaUTGZ2foxHJBvAOTj3W+dzEMoklQKE0cHocxADjUDZP/dpGEN/XwqjJMcvItChYqlhUgQj9zOJmILQ",
	"sAV8T2hmYhCGhdRARBToVAoNmkQwoxk3xEgiZF8bqWAQ9AK4o0nKIRgF+bdBL9BhDAnFw8wyxd+0UUzM",
	"g/v7XnB4QedtMA6FYWZJDJ2TmVSEkhDholMORCqSZMb+qUDLTIWNgz8Gi+3+cPvH139+/+qve3/cPX5x",
	"8vL0u/evzl6f710Mf/oYrIHojBo4YgkzfftvG7hjeseSLCEKfslAG01SUAkzeD9MEBMDCTOlQBiiqIE+",
	"x13ILRORvK1B+t2wAxAmDMxBNSA5g4QygRC2oDnLoVD5M18Gxcu9L4BCQ8d9XAp2RwxLQBuapOQ2hjXn",
	"I+HA6BoY269efzfc3d1Zfylg1LI/nhlQbVBOsmQKisgZ0RBKEWkyhZlUYOHx9CIJXZIpfjSKQVSDYrd2",
	"esIEEjoYDXtdkPy57+++P4k6JEkqBZziJzI5IDpLU84gItOluxzO8G6kInMQoKx0+Z/Gp5M6R69m5gdZ",
	"+b4XFPKKv7+hkQcYP4VSGBD2T4qghRbUrVTJKYfk//2sEYvPJRS4IsL934wPrs8O318enl8EvSACQxkP",
	"RsFF5YanMlqSUGY8IkIavOwIcLW9bP/QNYvWomaoyXQwejFEAjBjL+MNjfJzgoIssTGpHm1tzXgGwig6",
	"iGCxBUpJpbemNOrnC+6r9/WVglkwCv7PVqkst9yveuvUXYO7xTphq4gyTRLKZ1IlECEtY6oJFYSJBeUs",
	"QgnQUg3w2H0pZpyFT7v6/Xcnb48m+617lylyEHJa6I/R5JaZuC6GXlsSvFZ4LCX2SkoUKG1Ehhyy56YB",
	"Xvxj0L/vBW+lmrIoAvEkopwenh1Pzs8n706uDw5PJocHVer8RWYkklYKYroAZyq0RliNxE/IO8TETBMa",
	"4oGPpctuSZfT8owIBINoMwKVoPX9sueiVN2HoKGRinAa3ujqdaCdt/dQUNPSaCIMKEH5OagFqEME9UnU",
	"mpxcHJ6djI+qRBoLkgm4SyFE+Ox1EBlaxnmkxnpZ1Vg5CkRbHNwBm9GE+aXPQoo6mlVgCmyt2MjMELhL",
	"pXa+hINAW2qcSPNWZiJ6EglO3l1cv313eXKwwnw4P9MJ6y3VVnhmeOpjZeNFSYuTfK/N7l9I03ePP5/W",
	"8phFEhxqcMe0dQSY+7xgmqF3a2ShF7wNQRlgIVwKuqCMowv8JDocHJ4enhwcnuz/5fryZPzTeHI0fnN0",
	"WBMMSxKmPLuwEBBIA0kqFVWML0lWwvJYSaloLo9gddfN6BRBCiICES771bXPIjUkpioi5Qk5nWqIVyKs",
	"hoPadax/eqv6qD36QspjKpa5T/8k8p6NLw6vjybHk4u6SbKHEoqHWgPJROQ1s5X1BeWPlLOdim9wISVJ",
	"qFgWQdJmdCxDhec0P+7abMRIDRAXiqCrNgUQBO5CAO+bPhMZLwWaPKnY3+BpqvLyZHx58cPhycVkf9wg",
	"46mSCxYBocT5mjQMQWti5A082onYLgk4Lm02WudcD2xGxkzUTP7zyGEdoFBBhB8p14QqINaNEPNe7nv3",
	"UKPCXcqsDb/vBT/ht3btW8r4E+ny0/hocjC+QJ/v7XhyVKfMO+GyFBh35oHCjAGPHKQeQBvi2esKRh+K",
	"jQ+PxxP0TezzwSjAmJ4HvSABrekcXGoEVEF1+zuhUaRAo4m+epzk7pSEL++JzNxFbUTyRbGs75dtTPTy",
	"xAfI/8CluvNICcHAhud+ezx9rDWbizPJoRIA0yhi+DTlpwp9TsMwTJ5RrqF5+B8UFYZQoqSzy5RkGhRS",
	"MK0s/Rzg7+uwRShOaAKBi8+9WI0+uMVXxWXL6c/goqV9G0W2MwzvUvpLBj1yeXbU13QGPtwkIEIZoe9G",
	"MdZBtaelMng/GRAqIjI5qOcXYPnjz5OfJTv+ebw8YcPbd/vD2xP+/u74QN7a/72V7Gj/x9Q+c3D48njn",
	"cHcihsiWTByBmJs4GG33mgmIXvADUI6/NSE/z6yymmWcpEpavcXZAgT+oUBn3LTvNmfWdp5FzJhKNDEx",
	"Ndag5Vsy7bwWMS+skMVbZAnet7yp3HYl/1eliT+0iyrH0IalHeyElHNQX2sibwWqaJkJMyAXMShwfkQl",
	"eLUIKDCZEtq5fjqmKbgMqFjapApwDSOLpfffFdBI2y9cXDVTMvEfS3tgqW6vhpqYhFQpZp1Py8bE6aL6",
	"bYcKEP5rakUFg1T8K4jQPhuWVNyyktpOV3UkKBEjDNMFXxLEfEBOJJEmBlXB3kYcoL1sfa2bqq3KsByo",
	"EqD+zX8zCGWCOjOHMlea3RBeL0CxGSuQq0P7pzx76Q+2EUi+whoVkXFObmPGgTCbAcpE/vugCkX7rj7k",
	"oPQC3CS4uu8FrCN1eO6kllkDN2MYpS1ALf2VFRGEghkoECHo2rlZxqIu5FMlZ2y9fjqGU//gfa8idA8t",
	"udSgzt2T970gS6MvZJ2G0Fnwcxp6CHpVjqydUSLWLaWnJdr1Wz7IPy2ARNRQQqcY+dqckZVaZFMTo/rI",
	"xTXTEFn9X5HxtuzQBTVUXWeqQxhOsylnIXGPoOaushQIIqSA0jXNUi5p1OCrTLEHOcrqGLVsnz05f0d2",
	"t7/7rr9NKE9j2t8h/lmC3kcBSV3WfjpBBKkxoHCTf/8w7v/16vPO/VcPAoHkuZaz6ylTXQbgUuf6wKV9",
	"gNA5kDleJ5lYoRLI8kTHqDdNri283Gurz9wTHOgCdCtz1JDDh2FlOuV0eS3QKreFsRuEAUEj7q0OS1JQ",
	"WgqMLt565wht72xmPT4FP9ucS/1iT+YxEjKhd7kJfTlca1FRgP4mRQeck/HJmOQ/E8RlQA6t2ihLM74w",
	"ND6dIHRLTS4v9r93d1fh7pRTq10SJqL8srVRQG/IVGYiotZ6+L38fXytSUSXdQTHmtGtH+T1fsyuj5mI",
	"1wp+jRAVXDsFe1mmOXWXGqdVUUb0KOfy1mEYyR6humpGfZaYL4kGRM4MPooLfy80WjAt1ZJ88+asf/Zm",
	"vN8fvv7W8qlN3WiipQ+kDagZ3l1IBYltcGZzup5Lbm1BBL3Vnk0g+GW+EoRrIgjtKrG0emfk9X4OI+Wc",
	"KOiHMYQ3umfpQvPl9oSYekngzBUnhCQhl2jkDRp75xRWkq7MFBm2Ofq40OEKpA/ds+MwJFhUy20XN/+1",
	"tl6zdvv3rPXiC4gs9DOOekVANCDjnJNILNGpt4pQznAnDeS///O/SocGv2PKelRWb+f5mBYYPW+gb/Fu",
	"Pm0l8IkkQEXdmfhw1QuYgcThWtFztP+3K/xn2N+7vvq/Hz8OGt980/7q2///VZfl9V9QpegSjZdgv2Qw",
	"cWcalQGKAd5Rt0Ppro/aEMaxb9VEOVcStQzc0RAZ2NxKJ5xMoyscZaGpIxyggxVU0d4sXtkAkY6QBm13",
	"lYW6hPnUhrYtz96FMymdM+F8xAQMtSRXuU9pyzxOShCr/oyGyOTI/21Ojqm+xgCy0+uz2p0Kp+VTNEco",
	"kdNqVtoJkIA7c51X9ir3ihdQ4DaVkgMViBzv7iIoS9WWDJVjikoIQlE7Ymdo7YUrSm8Pnbnwn9ol6l5Q",
	"AXUdmX2Q2aRgcWU5Hp3k62xMqAR5aHAqCdRQCmH7S5hZPjHeO5XazBWcvz+yCuUMIqZ9l4r3m54p3Dst",
	"ve1uMS3UnQZjmJjrATkDa0ojtDWU3MaSQ8+7LSk1YdylbSm79vErE/NrmZprmXVwzwHTGCNoMp6gZrXh",
	"PvpTA3IABqVNMG1YSOAOVMgwrroBSMmtVDc2S6Yx8DR2VWY8TKFEY1Yx6nWVW1UmbS6PKOPL67mk/Dph",
	"IjNd13TsfrDtGSaLlrWz0NCyBCFC/gcaxi2PYvtlhf1fvK6y/8su9ucypF2e/5v9U/LiFeFUzDMUdEPn",
	"PXsdUlDOl06poJKZe1+y9GkWrOENowH4vHP/TT/3i1fYACExlHMJxuswpkIA7+Ju/0uLDKmxVq7YQ5MG",
	"aB8CJq5pmhaxU1XB50LQeKQXpJmOO+RiI5v1S8bAXMcyUx2IjPNeHyYwWA5j9EWqCCDBI+BsAaoaWCPx",
	"0fbncYB1A6wUEkWtbjYxFdbI+fSfdaOs88NnKGbu2JAK33oCdykG8k7YpIB3M5twfUgZvkfMfrCI3feK",
	"xhobMNxjxGBicKFCfq+czWMMRSOqbjBoXWoDSee9Pjk69kydA9EpeavYrbdCvdTA6tZ+LjHbTu683Sd7",
	"L16+Iv4JVD+UcV10Cnaklmyme0XOI6FhzAT0FdDIfuHq07imEZZ2ZOCbUSr+4xyzTpHME/Zt1rXZVLhL",
	"OfWOh3VEkRtdnVw0ew43T/m3oGBCGypCWNnZ55J2lsWdBoYoV8d443VAtmjKthbbWzQz8RYqMG1AdR2L",
	"rtTqLLjzZRoUojPo5af2dQohcljhk1WQK/mmWot4qEGukupCBaCzNJXKWJMupxj+0CnjzCy/oC+uhfEq",
	"h+KHi4tT4n60fFbpROmmtiuXtKyNL6B0cFMslelZpuqROEuoKNlbZ0lCVQOvB0owTQW9Qowuzyb5nS7R",
	"pFb4heDC+nlfVtepp6L6hV+0VnPZX/N7qmb2UCHUeKVLBVV0cgvrI9SJ5JZy3g+5DG9cyqOdosgzChhu",
	"ejuR0CW5VTQlKdWGJCwSqMp73mYxZ4gFIsxJSLXjDs0BUpsYRHjaKg5ch0yFU1+NhsO6hvrmw3D76sOw",
	"v3f1Hzsfhv3dq29HH4b9l+6rr1YwsDL1fXd2nrxv2wVWxrrN3WQ4AxotH3T2m+0SyOvsGUo7LsrraMbI",
	"dN6FkZtjZYF8irvvXfeK1/+4yqGNDCRSy6AE5rthkICxu08wkdPLizzZY80GYbooubtEz20joaVBRHZx",
	"HvbbB5gmtun+SwKLgps8Apv69rWm6ce55b+mX93lGOfe7m/qF/+dXc7fwH3sFCDZbQxtCb0oR5Z5IcJ8",
	"CrJDndb2qHLNW4wYaOSiXUVtKcfFrJ2uVp7g3zTd1ch8VjhKTWk4cCk5tFz4CXUOMoQGNeBMmxqffTkb",
	"NcjmU+LVm1ifVkNcjpg2q/OKJKSGcjnPinhLJxTvVERkxu5Q+Wjps6gYTvlcXJd+KXDdOKvYuodWIdDu",
	"tAqzk85yzWElC+oyp66/sszd73yL5t/ETFk1SwUZH5z1fApZydsR4os8PwdfIrBVeJeLzpMgtWCUGU1y",
	"FzgXT8uVnh86FcmljbiOH9mRMiYpVYZRTlzkNiDvEoYIOPNhpCuMISqZcMhE3yOumbgR8laUZoZWGmes",
	"u5kpqGGnZQKuDGoVG18SNhfSGqYphDTTQKhtv0qBc4j8zsiw9Y6GneEQz2MiYtowMc+Yjq2zalsWdFbI",
	"bcJEFf/tdgBZFDi/pExZjfya1clyn+29vdf94W5/+GJlDbG6UaN0WK/ukZN5tgTxpCLfF5bTWpJyqUGd",
	"rSsuxEix6dImW5Bhe5X2UMc83b1OTbXYZPrnLzC4vX08uabloaFN8oV5seVqxW2dr/BGx657h3A2g3AZ",
	"8nyShHxCZxTtYQQc8OFPedywO+xHdIl2LbTGjsmoVybEfJeO3dS2kThHlkwzQ7RhttgXygUo961Ll8pb",
	"4TrPCkVjBzXRA8i09YojaxnqEFnTgT5o1KmLyoCzGLBod9/lQ021/MYXpncqqmZVYufs8P3l5Mzmc1pw",
	"+q7I5uY/nr878WqnzJV0dAXWet5W9QgVnZadQSbT1iZ25oegQ5PWDz20LU0V336wlmsdykWQnEPXxbzt",
	"Pkq0KZxv4H0WjZe9tsdWQSpPIdgEeQqq7y7d49oVCPsG1+aub3Fdn8MCeMel2Y020h1Nxl3nUXh42reH",
	"LvZPoLR3MZudQimXS4hsHWuaMR6RhXu2jfFi1SZ+d0K1liGzzYHFjJrKhB3cLfZv5LkG24PhWk7JT24j",
	"d98LNISZYmZ5jhfnx0GBKlDjzFnAqf30NteoP/7pIuh1Z7L6nC0gKvtcmo3nljY2grRb1tuHXWw9U6Dj",
	"fSlv2IoYwVDj2jbtk76JsRihtY1DviiVP1Lr/WG4T+j2z93+wD95bTcroaIp+yMsXcsxEzOZ94VTN6vp",
	"FxfYTml4Axi+AE3QQileSaDNmYmz6SCUSZFLK/4IOmcTPNEgIjYNiQcrGhqbZcrPHBDfNVbgqK3yYSFz",
	"DSuGfMrpOyIfrj59X+sXLFssk0wbEkHIbU7alGqoEogNgrIVvEB6fDoJeiVre4a87wUyBUFTFoyCXc+j",
	"qIAte21ZZ2CrcBPmYFYVTn0I8nD4UZb8Y8nrHmotKinQnURoTaY0xBDozHci1Aaid4bDB6YAOrr/vU76",
	"0FJnD8ahnoVy56gWVW4YSnbpZZ/WHJAffMNMq/+lerp1yZqHX1m9t1mXfhFMdjTnuy4gZevbVqkxo5tw",
	"VEZrmoPzD83W1J61R78Ybq9aVFB3qzaBYxftrl9UzgNblelS82j5MYD0bTgdmQsTw9LlLqzw0HlBV9TF",
	"d/3yWdRCBYHxDC8kSBy99ZlF96W8pFTRBAyoLoZDubG927ex1EWLkAIyBdSbPuArVCEKZckKzgcuLIer",
	"9ZRMsM6rvuoFqexKKtgpCTszqgmLIEklitWomJvIYabc5md9o1feveU9wgEZC9/K7ku49mZxdaKBL2yH",
	"eL7fMp+trm7ZrQTKEZCy1PBGulT25grADXh4Ud5YdNrjJ/d14503gT1JOXnOaUdhRcQUDLf39uh2uNPf",
	"jV5A/9Xs9bC/R6dhP4LZcHtn98XL71693hytMrRcMXjnG/k9dxYRZSEqz6gShuulu/L6i99Ki+CKF+tX",
	"FFPVuGBnZ/2C1ixbXV+tHlfaRDl5W/SAetr6jP937zQARpVdteuFvGnpggG5uJVEwULmTSyuPXqWaYhG",
	"qAOc5CtI5MLXLX2n5ycLyidvZGzrq50uzbeqtti61JdN3dmsuLNJQlZNtGvea+sJCzgUeuJ/hUCWt/iP",
	"Z6gfI2LDvfULipeb1EXLsUcuWzZz+Tjp6v1+DXxvZbXAOOG9gRUHq9K8dh+94WAkeqXIWH54sDN0OPNp",
	"ZZ84Ll87hUF0ZQSQ+ncp2Cb62iBgXfjPrarwE4tPFf28oh3Im83F15+9QnYbaGEQ/ozSWkkRuJb4kuX3",
	"YwhvWnOaVX7Pa4/WZLhE+IMkqyY+p8ClmFtdL1tzi5VJyQg4m9r3ZPElqvJPFav0yc0xgUqpMkXvuw9X",
	"R5XhyFAmoMsRSXuG64X1ie/c50RvsmgGny6dvPnpCWpiomGegHNi6lyEKvgPYI6fbj2qE5jBznDnu/7w",
	"dX+4fTHcG22/HA2Hfy2q1avmITumHcuN9i6GL0Y726PhK9xoc2NUmyOsTrqJjPPK8JkryDQKLfXqSr14",
	"ks9DlcWPdsWj0sVV5r2rHZXd+G0sgcewSvqK7u58hvd3YCi/yOw1rBiN6jM61fHkimTnHkvDkmngM2fC",
	"TNgx3XfqSpN86YuTOq+cIt+4SqXJC4XOqnGYYRAnBXxfVCjtjJ9tCS6fyyfpnEf3YmenWwLz2upTQr0O",
	"7izreeuYdDN3rVEB/jWCwn9pkd+TFvGH/EpK5LeKgf8OEa0TlbbKynXKpirLOShbjcaeFc6KHVTUXbOM",
	"3lWZcWps+l3O2rnXalqQjPMRUin40jaYPH50FPXiA3OhRMGcqoijEyVnlb5BNyc6Bc5gAbo7+kXXpTZY",
	"+1T908g398qg2NFpc6GqgbXOSpfJ2t9RFnoDEwyzmXvxchPuNaFlnbvro2prXfEZGtlmb6pL6edeekzd",
	"JI51nd1Yga8pSXFLVaR7jpOLwf286YcKAklqlvaVsKvd5WV1vO6pPLei0zXvo+poZt0dll2prhV1RVtp",
	"Ry9po9vTtn4X/d6+Zdv3aZdtnHnX5jNaneoNrhOPtP7qkH8mR7aB2qaObNYpI7YH3AmJqzo2pWTs206s",
	"/yqzok/yY1B03X0M8jH0zk67fr8cNbC6OqE3+fssKonTTsnxALal55Eu7z+M4GxetFzZxv9rONv/Ujwr",
	"FI+bSfgV1c4/sevrWfjpWg69g9RP6nf6BKfubdSa2NGCW8B/uwfsvaeZv7vHuP5GJeVsVV711L1z5++Q",
	"VT0tXobfnVNFrJjRhCUJRAyjjGK6iEHjXQK/VbL1gfclrMy7qnwwa6NsuW2hsinzDcaqugjq5sCejaIO",
	"+i/Q6/bxjreE8uYAGoM8dUSdB/psauflJqWqjnc2r6d/1/TcSsJXOg7XuvqLL21C7CJ93if5VOJ39JNt",
	"+MJQv3CFVEfVds1Ko+avL72FO7oKhDYB67vVuzI/XN3j9jbK7yoS5i2l275BzzUj+hFw+y5Yf15L03Nq",
	"7H94wNXYrA6MGJ0LqQ0Lq21jHtDummBX9niU52Rc9F2xUz6kLNsR3ZuLQoPaqFKkYaJVB8rfmoKcm7+z",
	"Mn8upSZu9rm1wT3rTAiQ5mvCErp0LwfzbV6Nnr5KA6ZNyzgXnzBTAcBG6PdX9/8TAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
