// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
)

// Defines values for HealthStatus.
const (
	HealthStatusOk HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case HealthStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for PingStatus.
const (
	PingStatusOk PingStatus = "ok"
)

// Valid indicates whether the value is a known member of the PingStatus enum.
func (e PingStatus) Valid() bool {
	switch e {
	case PingStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for ReadyStatus.
const (
	ReadyStatusReady ReadyStatus = "ready"
)

// Valid indicates whether the value is a known member of the ReadyStatus enum.
func (e ReadyStatus) Valid() bool {
	switch e {
	case ReadyStatusReady:
		return true
	default:
		return false
	}
}

// Cursor Opaque, URL-safe cursor encoding a stable sort value and ID.
type Cursor = string

// Health Successful process liveness result.
type Health struct {
	// Status Confirms that the process is serving requests.
	Status HealthStatus `json:"status"`
}

// HealthStatus Confirms that the process is serving requests.
type HealthStatus string

// Page Cursor pagination metadata returned with every user-facing list.
type Page struct {
	// HasMore Whether another page can be requested using next_cursor.
	HasMore bool `json:"has_more"`

	// Limit Number of items requested for this page.
	Limit int `json:"limit"`

	// NextCursor Opaque cursor for the next page, omitted when there is no next page.
	NextCursor *Cursor `json:"next_cursor,omitempty"`
}

// Ping Successful API dependency connectivity result.
type Ping struct {
	// Status Confirms that PostgreSQL and Redis responded.
	Status PingStatus `json:"status"`
}

// PingStatus Confirms that PostgreSQL and Redis responded.
type PingStatus string

// Problem RFC 9457 Problem Details response.
type Problem struct {
	// Code Stable machine-readable error code.
	Code string `json:"code"`

	// Detail A safe explanation of this occurrence.
	Detail *string `json:"detail,omitempty"`

	// Instance Request path that produced the problem.
	Instance *string `json:"instance,omitempty"`

	// Meta Safe, problem-specific metadata.
	Meta *map[string]interface{} `json:"meta,omitempty"`

	// RequestId Correlation identifier for support and observability.
	RequestId string `json:"request_id"`

	// Status HTTP status code for this occurrence.
	Status int `json:"status"`

	// Title A short, safe, human-readable summary.
	Title string `json:"title"`

	// Type Stable URI identifying the problem type.
	Type string `json:"type"`
}

// Ready Successful hard dependency readiness result.
type Ready struct {
	// Status Confirms that every hard dependency is usable.
	Status ReadyStatus `json:"status"`
}

// ReadyStatus Confirms that every hard dependency is usable.
type ReadyStatus string

// ValidationError One invalid request field.
type ValidationError struct {
	// Code Stable validation error code.
	Code string `json:"code"`

	// Field JSON field path that failed validation.
	Field string `json:"field"`

	// Message Localised, safe explanation of the validation failure.
	Message string `json:"message"`
}

// ValidationProblem defines model for ValidationProblem.
type ValidationProblem struct {
	// Code Stable machine-readable error code.
	Code string `json:"code"`

	// Detail A safe explanation of this occurrence.
	Detail *string `json:"detail,omitempty"`

	// Errors Field-level validation failures.
	Errors []ValidationError `json:"errors"`

	// Instance Request path that produced the problem.
	Instance *string `json:"instance,omitempty"`

	// Meta Safe, problem-specific metadata.
	Meta *map[string]interface{} `json:"meta,omitempty"`

	// RequestId Correlation identifier for support and observability.
	RequestId string `json:"request_id"`

	// Status HTTP status code for this occurrence.
	Status int `json:"status"`

	// Title A short, safe, human-readable summary.
	Title string `json:"title"`

	// Type Stable URI identifying the problem type.
	Type string `json:"type"`
}

// Version Deployed API build version.
type Version struct {
	// Version Version associated with the running API build.
	Version string `json:"version"`
}

// BadRequest RFC 9457 Problem Details response.
type BadRequest = Problem

// Conflict RFC 9457 Problem Details response.
type Conflict = Problem

// Forbidden RFC 9457 Problem Details response.
type Forbidden = Problem

// InternalServerError RFC 9457 Problem Details response.
type InternalServerError = Problem

// NotFound RFC 9457 Problem Details response.
type NotFound = Problem

// ServiceUnavailable RFC 9457 Problem Details response.
type ServiceUnavailable = Problem

// TooManyRequests RFC 9457 Problem Details response.
type TooManyRequests = Problem

// Unauthorized RFC 9457 Problem Details response.
type Unauthorized = Problem

// ValidationFailed defines model for ValidationFailed.
type ValidationFailed = ValidationProblem

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// SystemHealth Check process liveness.
	// (GET /health)
	SystemHealth(w http.ResponseWriter, r *http.Request)
	// SystemPing Check API dependency connectivity.
	// (GET /ping)
	SystemPing(w http.ResponseWriter, r *http.Request)
	// SystemReady Check dependency readiness.
	// (GET /ready)
	SystemReady(w http.ResponseWriter, r *http.Request)
	// SystemVersion Read the deployed API version.
	// (GET /version)
	SystemVersion(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// SystemHealth Check process liveness.
// (GET /health)
func (_ Unimplemented) SystemHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// SystemPing Check API dependency connectivity.
// (GET /ping)
func (_ Unimplemented) SystemPing(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// SystemReady Check dependency readiness.
// (GET /ready)
func (_ Unimplemented) SystemReady(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// SystemVersion Read the deployed API version.
// (GET /version)
func (_ Unimplemented) SystemVersion(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// SystemHealth operation middleware
func (siw *ServerInterfaceWrapper) SystemHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SystemHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SystemPing operation middleware
func (siw *ServerInterfaceWrapper) SystemPing(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SystemPing(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SystemReady operation middleware
func (siw *ServerInterfaceWrapper) SystemReady(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SystemReady(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SystemVersion operation middleware
func (siw *ServerInterfaceWrapper) SystemVersion(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SystemVersion(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/ping", wrapper.SystemPing)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.SystemHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/ready", wrapper.SystemReady)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/version", wrapper.SystemVersion)
	})

	return r
}

type BadRequestApplicationProblemPlusJSONResponse Problem

type ConflictApplicationProblemPlusJSONResponse Problem

type ForbiddenApplicationProblemPlusJSONResponse Problem

type InternalServerErrorApplicationProblemPlusJSONResponse Problem

type NotFoundApplicationProblemPlusJSONResponse Problem

type ServiceUnavailableResponseHeaders struct {
	RetryAfter *int
}
type ServiceUnavailableApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers ServiceUnavailableResponseHeaders
}

type TooManyRequestsResponseHeaders struct {
	RetryAfter *int
}
type TooManyRequestsApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers TooManyRequestsResponseHeaders
}

type UnauthorizedApplicationProblemPlusJSONResponse Problem

type ValidationFailedApplicationProblemPlusJSONResponse ValidationProblem

type SystemHealthRequestObject struct {
}

type SystemHealthResponseObject interface {
	VisitSystemHealthResponse(w http.ResponseWriter) error
}

type SystemHealth200ResponseHeaders struct {
	XRequestId *string
}

type SystemHealth200JSONResponse struct {
	Body    Health
	Headers SystemHealth200ResponseHeaders
}

func (response SystemHealth200JSONResponse) VisitSystemHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.XRequestId != nil {
		w.Header().Set("X-Request-Id", fmt.Sprint(*response.Headers.XRequestId))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SystemPingRequestObject struct {
}

type SystemPingResponseObject interface {
	VisitSystemPingResponse(w http.ResponseWriter) error
}

type SystemPing200ResponseHeaders struct {
	XRequestId *string
}

type SystemPing200JSONResponse struct {
	Body    Ping
	Headers SystemPing200ResponseHeaders
}

func (response SystemPing200JSONResponse) VisitSystemPingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.XRequestId != nil {
		w.Header().Set("X-Request-Id", fmt.Sprint(*response.Headers.XRequestId))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SystemReadyRequestObject struct {
}

type SystemReadyResponseObject interface {
	VisitSystemReadyResponse(w http.ResponseWriter) error
}

type SystemReady200ResponseHeaders struct {
	XRequestId *string
}

type SystemReady200JSONResponse struct {
	Body    Ready
	Headers SystemReady200ResponseHeaders
}

func (response SystemReady200JSONResponse) VisitSystemReadyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.XRequestId != nil {
		w.Header().Set("X-Request-Id", fmt.Sprint(*response.Headers.XRequestId))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SystemReady503ApplicationProblemPlusJSONResponse struct {
	ServiceUnavailableApplicationProblemPlusJSONResponse
}

func (response SystemReady503ApplicationProblemPlusJSONResponse) VisitSystemReadyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type SystemVersionRequestObject struct {
}

type SystemVersionResponseObject interface {
	VisitSystemVersionResponse(w http.ResponseWriter) error
}

type SystemVersion200ResponseHeaders struct {
	XRequestId *string
}

type SystemVersion200JSONResponse struct {
	Body    Version
	Headers SystemVersion200ResponseHeaders
}

func (response SystemVersion200JSONResponse) VisitSystemVersionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.XRequestId != nil {
		w.Header().Set("X-Request-Id", fmt.Sprint(*response.Headers.XRequestId))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// SystemHealth Check process liveness.
	// (GET /health)
	SystemHealth(ctx context.Context, request SystemHealthRequestObject) (SystemHealthResponseObject, error)
	// SystemPing Check API dependency connectivity.
	// (GET /ping)
	SystemPing(ctx context.Context, request SystemPingRequestObject) (SystemPingResponseObject, error)
	// SystemReady Check dependency readiness.
	// (GET /ready)
	SystemReady(ctx context.Context, request SystemReadyRequestObject) (SystemReadyResponseObject, error)
	// SystemVersion Read the deployed API version.
	// (GET /version)
	SystemVersion(ctx context.Context, request SystemVersionRequestObject) (SystemVersionResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// SystemHealth operation middleware
func (sh *strictHandler) SystemHealth(w http.ResponseWriter, r *http.Request) {
	var request SystemHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SystemHealth(ctx, request.(SystemHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SystemHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SystemHealthResponseObject); ok {
		if err := validResponse.VisitSystemHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SystemPing operation middleware
func (sh *strictHandler) SystemPing(w http.ResponseWriter, r *http.Request) {
	var request SystemPingRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SystemPing(ctx, request.(SystemPingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SystemPing")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SystemPingResponseObject); ok {
		if err := validResponse.VisitSystemPingResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SystemReady operation middleware
func (sh *strictHandler) SystemReady(w http.ResponseWriter, r *http.Request) {
	var request SystemReadyRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SystemReady(ctx, request.(SystemReadyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SystemReady")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SystemReadyResponseObject); ok {
		if err := validResponse.VisitSystemReadyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SystemVersion operation middleware
func (sh *strictHandler) SystemVersion(w http.ResponseWriter, r *http.Request) {
	var request SystemVersionRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SystemVersion(ctx, request.(SystemVersionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SystemVersion")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SystemVersionResponseObject); ok {
		if err := validResponse.VisitSystemVersionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"xFpZd9u4kv4rOJh+mqEsOU46HfWTYsunlbZlRZbTS9rjhoiShIQE2AAoW5Pj/z6nAK4iZSu2770PcbSQ",
	"qOWr5auivtFQxYmSIK2h/W90BYyDdi+PWbiCzrGSVqsIP+BgQi0SK5Skff814UJDaMUafiYstSuQVoTM",
	"AicaTKKkAUM4LFgaWWIVkapjrNJwQAMKdyxOIqB9mn9KA2rCFcQMhdlNgt8Zq4Vc0vv7gA5nbNlUYyit",
	"sBti2ZIslCaMhKgXm0dAlCZxat1LDUalOtwS/BddH3Z6hx9++v3j2z/f/Xp0/nr8ZvLjx7fTny7fzXqf",
	"/qKPaDRlFs5ELGzH/W0qd87uRJzGRMM/KRhrSAI6Fhb9IySxKyBhqjVISzSz0InwFHIrJFe3NU1/7LUo",
	"IqSFJegtTaYQMyFRw4Y201wLnV/zfVq8efcdWhho8ceVFHfEihiMZXFCblfwiHwEDqypqXH49qcfe0dH",
	"rx53Cli96QwWFnRTlXEaz0ETtSAGQiW5IXNYKA1OnwwvErMNmeNbqwXwmhZHNemxkAg07feCNk1+72S+",
	"74x4SyYprSFi+I6MTohJkyQSwMl8450TCfSN0mQJErTLruyrwWRUj+jdwfxgKN8HtMhX/P4945nC+C5U",
	"0oJ0LxmqFjpVu4lW8wji//li0IpvpRZ4B8fz3w9ObqbDj1fDyxkNKAfLRET7dFbx8FzxDQlVGnEilUVn",
	"c8C7nbOzi24Ef9Q0y2xqaP91DwEQ1jnjPeO5HFrAsrI2Mf1udxGlIK1mBxzWXdBaadOdM97Jb7iv+usH",
	"DQvap//VLYtl139ruhPvBu/FOrBVQ4UhMYsWSsfAEcsVM4RJIuSaRYJjBhilD1DssZKLSITPc/3xxfj0",
	"bHTc8LtKMIIw0sJMjCG3wq7qaZhVS4Juhaci8a5EojBpLxhyzV4aA3T8U8y/D+ip0nPBOchngTIZTs9H",
	"l5eji/HNyXA8Gp5U0flDpYQrlwUrtgbfKoxBXa3Cdxg7xK6EISxEgU/F5ajEZVLK4CAF8P0AKlXrZLe9",
	"FFJ1DsFCqzSJWPjVVN2Bfd75oUDTYTSSFrRk0SXoNeghqvostEbj2XA6HpxVQRpIkkq4SyBE/Zw7iApd",
	"4DyxYr2pVqzcBGKcDV7AfpiI7NYXgaJuZlWZwlqXNiq1BO4SZTyX8BoYh8ZY2VOVSv4sCMYXs5vTi6vx",
	"yY724XmmT9ZbZlzyLFDqU3PjdYnFOD9rP/9LZTv+8perWpllXIE3De6EcURA+PdrYQSyW6uKupD1EMwB",
	"EcKVZGsmIqTAz8LhZDgZjk+G4+M/bq7Gg0+D0dng/dmwlhgOEqGzcBEhoJIW4kRppkW0IWmpy1MzpVK5",
	"MgOrp+6HE4cEJAcZbjrVe18ka8iKaU5KCTlONcMrE9YWQW0Tm13drV7qRM+UOmdyk3P6Z8E7HcyGN2ej",
	"89Gs3pKcUMJQqGuQQvKsMrtcX7PoiXn2qsINZkqRmMlNMSTth2M5Krxk+/FucxMjs0D8KIJUbQ4gCdyF",
	"ABk3fSEYryS2PKXF/8HzSuXVeHA1+2U4no2OB1swTrRaCw6EEc81WRiCMcSqr/BkEnFYAjgoezZ257wO",
	"7AdjKmst/2XysK5QqIHjWxYZwjQQRyPkMsi5d4AVFe4S4Xr4fUA/4afu3lMmomfi8mlwNjoZzJDznQ5G",
	"Z3VkLqTfUuDcmQ8KCwER95pmCroRz7mL9j8XBw/PByPkJu562qc400c0oDEYw5bgVyOgC9Td94RxrsFg",
	"i75+Wua+KoEv/UQW3lF7Qb4ubutkt+0NeinxAfgfcKqXR0oNDtx4nh3vll5uDmvO6BcJ+yeFgFxNzzqG",
	"LSAb2AjIUHFkPwynBSwcRmmLElIgTHIyOqlP6LD58GX0RYnzL4PNWPRuL457t+Po4935ibp1/06VODv+",
	"kLhrToZvzl8Nj0ayh8AKeQZyaVe0fxhsj/AB/QVYhN9ta36ZunRfpBFJtHKZH4k1SHyhwaSRRQUTjWTa",
	"Cj//53A3NxVyIXRsiF0x61pCfqQwvu/LZVHHnd0yjWn/M1Vf6XXQskErikX/cy60vE7Nv4CfAicuoBva",
	"eAgSthTSh2EMlnFmGdFgUy0zlkpgDXpDUgO6s2Ah6hgJ02L2ipkbDJumqN9WYFeYTFK5/xO2BBIy6bdD",
	"ORdNHQ+WcGdv8nm+Ar3VKRS2zZWKgEk0LmrfHZYLKmEhNhUxxfyDWtREvOoFNPY7R9o/xMmiWEwdNhdT",
	"Aa2o+ljqZYmxDVrhstyOVvha15GVwBxMRlXaFCop3VZZ2M0zY3SijF1quPx45rJxClyYbDedNfKXCtGs",
	"IDW3rqfH5N3rN29JdgU5cdXfFBvypmm+wjf85etLzMKVkNDRwLj7wM9leE+90rR1noRZHNJon/7v50Hn",
	"z2v80+u8u7n+7x9oS03JG9W3BtN1NRDukohlqacW2Uzu50O5vWvfv9U1tBDSWCZD2LnRJglzKxxmsR7x",
	"NASeFyf0eF2RLktEd33YRd7R1bAUBslYi1gsJq7fcy5QHosmFZR8Nm8hxBYQ5FI7JoFQLERYVKWKcWXc",
	"VHvwQ4th4TjMQoB2+W/SJMFGg0Gt5lh62VxEwm6+Yx/csHhXSv0ym02I/9LFWWUD0462pwmNcpMRh5Zo",
	"WiltAxdUAVmlMZNleJs0jpnesusB6lGa4z/YkUZX01Hu0w1W7Uq8ELyxLu/7+ExAF0rHzNI+TbXoaFiA",
	"8xF9rL64b3M/FXgEviDUYqWtBE2B8c2DdXZ7PkUnixdgAr7Btky/qcnH3rzMaqfkcyptiX2x42sSwHyv",
	"Xis131lpS2B31tjp8OPVaOpKayP8MmK+ffiHy4uxV6dStlqIaY00Zty+pUZlZH9bypkKWSQM8GBHqa6Z",
	"h+LT7ceyQzcwCFNMdAePxq83uYjXXLuHUax0ThZFFws35Ow1+gXNSlIxKs9mRwET5H7O6ZmtphkM+Yy1",
	"feop3teJYA1Ri9PcQY6i7T+9+MAtShRlWrNNw5uZPk3vXaP/QBvhh866tieQRGoD3JGqeSoiTtb+2qbF",
	"612HZKcTZowKhVv5FI9JdCrds+Pi/K2Wc3B40Hs0UnLJTeOwD0GYamE3l+i47IkkMA0aJ3t8N3fvTvMi",
	"++E3/5yrpal0cNbh5DSr243dh8PGEXJ3ZH2C9UV1ocGsjpX6Klp7l1aWWT/3uCv92eVTXCWjjd/QQnFJ",
	"5cEF0hvap6E/P6CSOXWyK2/cYaVWLBG/wsZPvUIuVL6aYP5xYXZzYe2chV9BcmKBxTSgqY4qvWwp7Cqd",
	"H4QqLtpa8YK2rscy0IATxwhQsGahdXQgl3lAJuk8EmFpo3HFR4TCRhtiwJK/c3z75PP13z9n3cMPVuUD",
	"ujg1lnAII0cPbVmGKo+CDmi5jSiMHkxGNChDOwvI+4CqBCRLBO3ToyxGsQC78Oquiul52fbDhambJw0x",
	"vpeWv1zAJKjMwCxbx7tHJrVJuDBsxLHDbIyFOBvZtx6+v+r1Htg4tWya8h6NI8zeq5RM9o5F6JZZmERb",
	"S8/tnzQ8tPWsXXt/X01x2v98HdCM4yGvWEH4tbGocDizpXHMwLmOXuMp3SSbLFtBm/hnpnjMcmVvAf+2",
	"D4QhSjUZrQWCUe3YoFrsgs6NtP8R4CbFTzbaYUOrMF1EHAPH0l1SMgFbs++/C88H5vud0Oqcze6VkK7K",
	"uqzcg4u2AerJ84sh6rXfG1QvvW2XHW2zdgSRuSGa8c0LghjQN72jXTcVXum2PFl8HP+2kWMn8BVS8iD0",
	"tuxI+/OUNuhzKvVc8Ftazp5r7ezGHVnNq4yuwuX+9dmLYel8uUuFJoD10+rE7fP1PR7vfk7gn2W0s87D",
	"rId7vpItbNwTi0xeo9JHzLqfx/g27mogF2wplbEidKGWUaNM0fvr+/8PAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
