// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
)

// Defines values for HealthStatus.
const (
	HealthStatusOk HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case HealthStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for PingStatus.
const (
	PingStatusOk PingStatus = "ok"
)

// Valid indicates whether the value is a known member of the PingStatus enum.
func (e PingStatus) Valid() bool {
	switch e {
	case PingStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for ReadyStatus.
const (
	ReadyStatusReady ReadyStatus = "ready"
)

// Valid indicates whether the value is a known member of the ReadyStatus enum.
func (e ReadyStatus) Valid() bool {
	switch e {
	case ReadyStatusReady:
		return true
	default:
		return false
	}
}

// Cursor Opaque, URL-safe cursor encoding a stable sort value and ID.
type Cursor = string

// Health Successful process liveness result.
type Health struct {
	// Status Confirms that the process is serving requests.
	Status HealthStatus `json:"status"`
}

// HealthStatus Confirms that the process is serving requests.
type HealthStatus string

// Page Cursor pagination metadata returned with every user-facing list.
type Page struct {
	// HasMore Whether another page can be requested using next_cursor.
	HasMore bool `json:"has_more"`

	// Limit Number of items requested for this page.
	Limit int `json:"limit"`

	// NextCursor Opaque cursor for the next page, omitted when there is no next page.
	NextCursor *Cursor `json:"next_cursor,omitempty"`
}

// Ping Successful API dependency connectivity result.
type Ping struct {
	// Status Confirms that PostgreSQL and Redis responded.
	Status PingStatus `json:"status"`
}

// PingStatus Confirms that PostgreSQL and Redis responded.
type PingStatus string

// Problem RFC 9457 Problem Details response.
type Problem struct {
	// Code Stable machine-readable error code.
	Code string `json:"code"`

	// Detail A safe explanation of this occurrence.
	Detail *string `json:"detail,omitempty"`

	// Instance Request path that produced the problem.
	Instance *string `json:"instance,omitempty"`

	// Meta Safe, problem-specific metadata.
	Meta *map[string]interface{} `json:"meta,omitempty"`

	// RequestId Correlation identifier for support and observability.
	RequestId string `json:"request_id"`

	// Status HTTP status code for this occurrence.
	Status int `json:"status"`

	// Title A short, safe, human-readable summary.
	Title string `json:"title"`

	// Type Stable URI identifying the problem type.
	Type string `json:"type"`
}

// Ready Successful hard dependency readiness result.
type Ready struct {
	// Status Confirms that every hard dependency is usable.
	Status ReadyStatus `json:"status"`
}

// ReadyStatus Confirms that every hard dependency is usable.
type ReadyStatus string

// ValidationError One invalid request field.
type ValidationError struct {
	// Code Stable validation error code.
	Code string `json:"code"`

	// Field JSON field path that failed validation.
	Field string `json:"field"`

	// Message Localised, safe explanation of the validation failure.
	Message string `json:"message"`
}

// ValidationProblem defines model for ValidationProblem.
type ValidationProblem struct {
	// Code Stable machine-readable error code.
	Code string `json:"code"`

	// Detail A safe explanation of this occurrence.
	Detail *string `json:"detail,omitempty"`

	// Errors Field-level validation failures.
	Errors []ValidationError `json:"errors"`

	// Instance Request path that produced the problem.
	Instance *string `json:"instance,omitempty"`

	// Meta Safe, problem-specific metadata.
	Meta *map[string]interface{} `json:"meta,omitempty"`

	// RequestId Correlation identifier for support and observability.
	RequestId string `json:"request_id"`

	// Status HTTP status code for this occurrence.
	Status int `json:"status"`

	// Title A short, safe, human-readable summary.
	Title string `json:"title"`

	// Type Stable URI identifying the problem type.
	Type string `json:"type"`
}

// Version Deployed API build version.
type Version struct {
	// Version Version associated with the running API build.
	Version string `json:"version"`
}

// BadRequest RFC 9457 Problem Details response.
type BadRequest = Problem

// Conflict RFC 9457 Problem Details response.
type Conflict = Problem

// Forbidden RFC 9457 Problem Details response.
type Forbidden = Problem

// InternalServerError RFC 9457 Problem Details response.
type InternalServerError = Problem

// NotFound RFC 9457 Problem Details response.
type NotFound = Problem

// ServiceUnavailable RFC 9457 Problem Details response.
type ServiceUnavailable = Problem

// TooManyRequests RFC 9457 Problem Details response.
type TooManyRequests = Problem

// Unauthorized RFC 9457 Problem Details response.
type Unauthorized = Problem

// ValidationFailed defines model for ValidationFailed.
type ValidationFailed = ValidationProblem

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// SystemHealth Check process liveness.
	// (GET /health)
	SystemHealth(w http.ResponseWriter, r *http.Request)
	// SystemPing Check API dependency connectivity.
	// (GET /ping)
	SystemPing(w http.ResponseWriter, r *http.Request)
	// SystemReady Check dependency readiness.
	// (GET /ready)
	SystemReady(w http.ResponseWriter, r *http.Request)
	// SystemVersion Read the deployed API version.
	// (GET /version)
	SystemVersion(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// SystemHealth Check process liveness.
// (GET /health)
func (_ Unimplemented) SystemHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// SystemPing Check API dependency connectivity.
// (GET /ping)
func (_ Unimplemented) SystemPing(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// SystemReady Check dependency readiness.
// (GET /ready)
func (_ Unimplemented) SystemReady(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// SystemVersion Read the deployed API version.
// (GET /version)
func (_ Unimplemented) SystemVersion(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// SystemHealth operation middleware
func (siw *ServerInterfaceWrapper) SystemHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SystemHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SystemPing operation middleware
func (siw *ServerInterfaceWrapper) SystemPing(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SystemPing(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SystemReady operation middleware
func (siw *ServerInterfaceWrapper) SystemReady(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SystemReady(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SystemVersion operation middleware
func (siw *ServerInterfaceWrapper) SystemVersion(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SystemVersion(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/ping", wrapper.SystemPing)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.SystemHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/ready", wrapper.SystemReady)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/version", wrapper.SystemVersion)
	})

	return r
}

type BadRequestApplicationProblemPlusJSONResponse Problem

type ConflictApplicationProblemPlusJSONResponse Problem

type ForbiddenApplicationProblemPlusJSONResponse Problem

type InternalServerErrorApplicationProblemPlusJSONResponse Problem

type NotFoundApplicationProblemPlusJSONResponse Problem

type ServiceUnavailableResponseHeaders struct {
	RetryAfter *int
}
type ServiceUnavailableApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers ServiceUnavailableResponseHeaders
}

type TooManyRequestsResponseHeaders struct {
	RetryAfter *int
}
type TooManyRequestsApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers TooManyRequestsResponseHeaders
}

type UnauthorizedApplicationProblemPlusJSONResponse Problem

type ValidationFailedApplicationProblemPlusJSONResponse ValidationProblem

type SystemHealthRequestObject struct {
}

type SystemHealthResponseObject interface {
	VisitSystemHealthResponse(w http.ResponseWriter) error
}

type SystemHealth200ResponseHeaders struct {
	XRequestId *string
}

type SystemHealth200JSONResponse struct {
	Body    Health
	Headers SystemHealth200ResponseHeaders
}

func (response SystemHealth200JSONResponse) VisitSystemHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.XRequestId != nil {
		w.Header().Set("X-Request-Id", fmt.Sprint(*response.Headers.XRequestId))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SystemPingRequestObject struct {
}

type SystemPingResponseObject interface {
	VisitSystemPingResponse(w http.ResponseWriter) error
}

type SystemPing200ResponseHeaders struct {
	XRequestId *string
}

type SystemPing200JSONResponse struct {
	Body    Ping
	Headers SystemPing200ResponseHeaders
}

func (response SystemPing200JSONResponse) VisitSystemPingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.XRequestId != nil {
		w.Header().Set("X-Request-Id", fmt.Sprint(*response.Headers.XRequestId))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SystemReadyRequestObject struct {
}

type SystemReadyResponseObject interface {
	VisitSystemReadyResponse(w http.ResponseWriter) error
}

type SystemReady200ResponseHeaders struct {
	XRequestId *string
}

type SystemReady200JSONResponse struct {
	Body    Ready
	Headers SystemReady200ResponseHeaders
}

func (response SystemReady200JSONResponse) VisitSystemReadyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.XRequestId != nil {
		w.Header().Set("X-Request-Id", fmt.Sprint(*response.Headers.XRequestId))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SystemReady503ApplicationProblemPlusJSONResponse struct {
	ServiceUnavailableApplicationProblemPlusJSONResponse
}

func (response SystemReady503ApplicationProblemPlusJSONResponse) VisitSystemReadyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type SystemVersionRequestObject struct {
}

type SystemVersionResponseObject interface {
	VisitSystemVersionResponse(w http.ResponseWriter) error
}

type SystemVersion200ResponseHeaders struct {
	XRequestId *string
}

type SystemVersion200JSONResponse struct {
	Body    Version
	Headers SystemVersion200ResponseHeaders
}

func (response SystemVersion200JSONResponse) VisitSystemVersionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.XRequestId != nil {
		w.Header().Set("X-Request-Id", fmt.Sprint(*response.Headers.XRequestId))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// SystemHealth Check process liveness.
	// (GET /health)
	SystemHealth(ctx context.Context, request SystemHealthRequestObject) (SystemHealthResponseObject, error)
	// SystemPing Check API dependency connectivity.
	// (GET /ping)
	SystemPing(ctx context.Context, request SystemPingRequestObject) (SystemPingResponseObject, error)
	// SystemReady Check dependency readiness.
	// (GET /ready)
	SystemReady(ctx context.Context, request SystemReadyRequestObject) (SystemReadyResponseObject, error)
	// SystemVersion Read the deployed API version.
	// (GET /version)
	SystemVersion(ctx context.Context, request SystemVersionRequestObject) (SystemVersionResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// SystemHealth operation middleware
func (sh *strictHandler) SystemHealth(w http.ResponseWriter, r *http.Request) {
	var request SystemHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SystemHealth(ctx, request.(SystemHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SystemHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SystemHealthResponseObject); ok {
		if err := validResponse.VisitSystemHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SystemPing operation middleware
func (sh *strictHandler) SystemPing(w http.ResponseWriter, r *http.Request) {
	var request SystemPingRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SystemPing(ctx, request.(SystemPingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SystemPing")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SystemPingResponseObject); ok {
		if err := validResponse.VisitSystemPingResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SystemReady operation middleware
func (sh *strictHandler) SystemReady(w http.ResponseWriter, r *http.Request) {
	var request SystemReadyRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SystemReady(ctx, request.(SystemReadyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SystemReady")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SystemReadyResponseObject); ok {
		if err := validResponse.VisitSystemReadyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SystemVersion operation middleware
func (sh *strictHandler) SystemVersion(w http.ResponseWriter, r *http.Request) {
	var request SystemVersionRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SystemVersion(ctx, request.(SystemVersionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SystemVersion")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SystemVersionResponseObject); ok {
		if err := validResponse.VisitSystemVersionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"xFprd9s2k/4rONh+2qUsOU6aRv2k2PKpUltWZDm9pF4XIkYSEhJgAVC2Nsf/fc8AvIqUrdh+3/dDU0sk",
	"MZdnLs8M9Y2GKk6UBGkN7X+jK2ActPvzmIUr6BwrabWK8AsOJtQisUJJ2veXCRcaQivW8DNhqV2BtCJk",
	"FjjRYBIlDRjCYcHSyBKriFQdY5WGAxpQuGNxEgHt0/xbGlATriBmKMxuErxmrBZySe/vAzqcsWVTjaG0",
	"wm6IZUuyUJowEqJebB4BUZrEqXV/ajAq1eGW4L/o+rDTO/zw0+8f3/757tej89fjN5MfP76d/nT5btb7",
	"9Bd9RKMps3AmYmE77t+mcufsTsRpTDT8k4KxhiSgY2HRP0ISuwISplqDtEQzC50ITyG3QnJ1W9P0x16L",
	"IkJaWILe0mQKMRMSNWxoM8210Pk936fFm3ffoYWBFn9cSXFHrIjBWBYn5HYFj8hH4MCamhqHb3/6sXd0",
	"9Opxp4DVm85gYUE3VRmn8Rw0UQtiIFSSGzKHhdLg9MnwIjHbkDl+tFoAr2lxVJMeC4lA034vaNPk907m",
	"+86It2SS0hoihp/I6ISYNEkiAZzMN945kUDfKE2WIEG77MouDSajekTvDuYHQ/k+oEW+4vX3jGcK46dQ",
	"SQvS/clQtdCp2k20mkcQ/88Xg1Z8K7XAJzie/35wcjMdfrwaXs5oQDlYJiLap7OKh+eKb0io0ogTqSw6",
	"mwM+7Zyd3XQj+KOmWWZTQ/uvewiAsM4Z7xnP5dAClpW1iel3u4soBWk1O+Cw7oLWSpvunPFO/sB91V8/",
	"aFjQPv2vblksu/6q6U68G7wX68BWDRWGxCxaKB0DRyxXzBAmiZBrFgmOGWCUPkCxx0ouIhE+z/XHF+PT",
	"s9Fxw+8qwQjCSAszMYbcCruqp2FWLQm6FZ6KxLsSicKkvWDINXtpDNDxTzH/PqCnSs8F5yCfBcpkOD0f",
	"XV6OLsY3J8PxaHhSRecPlRKuXBas2Bp8qzAGdbUKP2HsELsShrAQBT4Vl6MSl0kpg4MUwPcDqFStkz32",
	"UkjVOQQLrdIkYuFXU3UH9nnnhwJNh9FIWtCSRZeg16CHqOqz0BqNZ8PpeHBWBWkgSSrhLoEQ9XPuICp0",
	"gfPEivWmWrFyE4hxNngB+2EiskdfBIq6mVVlCmtd2qjUErhLlPFcwmtgHBpjZU9VKvmzIBhfzG5OL67G",
	"Jzvah+eZPllvmXHJs0CpT82N1yUW4/ys/fwvle3421+uamWWcQXeNLgTxhEB4T+vhRHIbq0q6kLWQzAH",
	"RAhXkq2ZiJACPwuHk+FkOD4Zjo//uLkaDz4NRmeD92fDWmI4SITOwkWEgEpaiBOlmRbRhqSlLk/NlErl",
	"ygysnrofThwSkBxkuOlUn32RrCErpjkpJeQ41QyvTFhbBLVNbHZ3t3qrEz1T6pzJTc7pnwXvdDAb3pyN",
	"zkezektyQglDoa5BCsmzyuxyfc2iJ+bZqwo3mClFYiY3xZC0H47lqPCS7ce7zU2MzALxowhStTmAJHAX",
	"AmTc9IVgvJLY8pQW/wfPK5VX48HV7JfheDY6HmzBONFqLTgQRjzXZGEIxhCrvsKTScRhCeCg7NnYnfM6",
	"sB+Mqay1/JfJw7pCoQaOH1lkCNNAHI2QyyDn3gFWVLhLhOvh9wH9hN+6Z0+ZiJ6Jy6fB2ehkMEPOdzoY",
	"ndWRuZB+S4FzZz4oLARE3GuaKehGPOcu2v9cHDw8H4yQm7j7aZ/iTB/RgMZgDFuCX42ALlB31wnjXIPB",
	"Fn39tMx9VQJf+oksvKP2gnxdPNbJHtsb9FLiA/A/4FQvj5QaHLjxPDveLb3cHNac0S8S9k8KAbmannUM",
	"W0A2sBGQoeLIfhhOC1g4jNIWJaRAmORkdFKf0GHz4cvoixLnXwabsejdXhz3bsfRx7vzE3Xr/jtV4uz4",
	"Q+LuORm+OX81PBrJHgIr5BnIpV3R/mGwPcIH9BdgEV7b1vwydem+SCOSaOUyPxJrkPiHBpNGFhVMNJJp",
	"K/z8n8Pd3FTIhdCxIXbFrGsJ+ZHC+L4vl0Udd3bLNKb9z1R9pddBywatKBb9z7nQ8j41/wJ+Cpy4gG5o",
	"4yFI2FJIH4YxWMaZZUSDTbXMWCqBNegNSQ3ozoKFqGMkTIvZK2ZuMGyaon5bgV1hMknl/p+wJZCQSb8d",
	"yrlo6niwhDt7k8/zFeitTqGwba5UBEyicVH77rBcUAkLsamIKeYf1KIm4lUvoLHfOdL+IU4WxWLqsLmY",
	"CmhF1cdSL0uMbdAKl+V2tMLXuo6sBOZgMqrSplBJ6bbKwm6eGaMTZexSw+XHM5eNU+DCZLvprJG/VIhm",
	"Bam5dT09Ju9ev3lLsjvIiav+ptiQN03zFb7hL19fYhauhISOBsbdF34uw2fqlaat8yTM4pBG+/R/Pw86",
	"f17jP73Ou5vr//6BttSUvFF9azBdVwPhLolYlnpqkc3kfj6U27v2/VtdQwshjWUyhJ0bbZIwt8JhFusR",
	"T0PgeXFCj9cV6bJEdNeHXeQdXQ1LYZCMtYjFYuL6PecC5bFoUkHJZ/MWQmwBQS61YxIIxUKERVWqGFfG",
	"TbUHP7QYFo7DLARol/8mTRJsNBjUao6ll81FJOzmO/bBDYt3pdQvs9mE+IsuziobmHa0PU1olJuMOLRE",
	"00ppG7igCsgqjZksw9ukccz0ll0PUI/SHP/FjjS6mo5yn26walfiheCDdXnfx2cCulA6Zpb2aapFR8MC",
	"nI/oY/XFXc39VOAR+IJQi5W2EjQFxjcP1tnt+RSdLF6ACfgG2zL9piYfe/Myq52Sz6m0JfbFjq9JAPO9",
	"eq3UfGelLYHdWWOnw49Xo6krrY3wy4j59uEfLi/GXp1K2WohpjXSmHH7lhqVkf1tKWcqZJEwwIMdpbpm",
	"HopPt1/LDt3AIEwx0R08Gr/e5CJec+0eRrHSOVkUXSzckLPX6Bc0K0nFqDybHQVMkPs5p2e2mmYw5DPW",
	"9qmn+FwngjVELU5zBzmKtv/04gO3KFGUac02DW9m+jS9d43+A22EHzrr2p5AEqkNcEeq5qmIOFn7e5sW",
	"r3cdkp1OmDEqFG7lU7wm0al0746L87dazsHhQe/RSMklN43DPgRhqoXdXKLjsjeSwDRonOzx09x9Os2L",
	"7Iff/HuulqbSwVmHk9Osbjd2Hw4bR8jdkfUJ1hfVhQazOlbqq2jtXVpZZv3c4+70Z5dvcZWMNn5DC8Ut",
	"lRcXSG9on4b+/IBK5tTJ7rxxh5VasUT8Chs/9Qq5UE2FZpjZ3rnAievcoULTQ+vadu6JAzJJ55EIS12M",
	"KxIiFDbaEAOW/J3j0Cefr//+OavyfgAqX6TFqbGEQxg5GmfLclF5ZXNAy61BAcVgMqJBGYJZ4NwHVCUg",
	"WSJonx5lsYSF0oVBd1VMucu2HxhM3dxniPE9r/yFAQZrZVZl2drcvdqoTayFYSOOnWBjLMTZaL31kvxV",
	"r/fAZqhlI5T3Uhw19l55ZLJ3LCy3zMJg31pObv/04KHtZO3e+/tqKtL+5+uAZlwM+/8Kwq+NhYLDmS2N",
	"6+DOdfQaT+km2QTYCtrEv9vEY5Yrewv4b/vgFqJUk9FPIBjVjrWpxS7o3Oj5HwFuUvy0oh02tArTRcQx",
	"cCyxJXUSsDWj/rvwfGAO3wmtzlnnXgnpqqHLyj04YxugnuS+GKJe+71B9dLbds7RNrtGEJkbdhnfvCCI",
	"AX3TO9r1UOGVbssbwMfxbxsNdgJfIQ8PQm/LjrQ/n2iDPqc8zwW/peXsuX7OHtyR1bzKvCqc61+fvRiW",
	"zpe7VGgCWD+tTrA+X9/j8e61v3/n0M4OD7MenuqoXKy4NwuZvEalj5h1P2PxbdzVQC7YUipjRehCLeM/",
	"maL31/f/HwAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
